### ISSUE TITLE
README building is incomplete

### ISSUE THREAD

**Issue by laeubi** [ClickHouse/clickhouse-jdbc#1014]
The readme suggest that one can run `mvn -Drelease clean install` but this results in
```
[ERROR] Failures: 
[ERROR]   ClickHouseServerForTest.beforeSuite:202 » IllegalState Could not find a valid Docker environment. Please see logs and check configuration
```

I then simply used `mvn -Drelease clean install -DskipTests`, but it would be good to note that in the readme that one actual needs docker, how to setup and alike or what are the alternatives (allowing arbitrary code to create docker containers could be seen as a security risk)

**Comment by zhicwu** [comment]
Thanks @laeubi. Yes, by default it uses testcontainer for integration test, although it's optional. On the other hand, `clickhouse-cli-client` is probably the only module requiring either clickhouse binary or docker to run. I'll improve the error message and readme to cover that.
