### ISSUE TITLE
Caused by: java.sql.SQLFeatureNotSupportedException: ClickHouse does not support auto generated keys

### ISSUE THREAD

**Issue by zhilinli123** [ClickHouse/clickhouse-jdbc#1024]
Clickhouse Verison:
     <dependency>
            <groupId>com.clickhouse</groupId>
            <artifactId>clickhouse-jdbc</artifactId>
            <version>0.3.2</version>
Java Demo:
   statement = (ClickHousePreparedStatement) connection.prepareStatement(sql, keyNames);
How can I avoid this problem

**Comment by zhicwu** [comment]
Hi @zhilinli123, I think the error message is clear. Could you explain what are you trying to achieve?

**Comment by zhilinli123** [comment]
I want to turn off auto generated with the parameter

**Comment by zhilinli123** [comment]
I consulted this blog
我参考了这个博客 https://blog.csdn.net/binbinwan51a/article/details/123453501 
I wonder if clickhouse-JDBC has this parameter?

**Comment by zhicwu** [comment]
I think you're talking about an option in mybatis, not JDBC driver?

**Comment by zhilinli123** [comment]
> I think you're talking about an option in mybatis, not JDBC driver?
I understand that MyBatis undergoes Java API and uses Clickhouse JDBC to connect. I wonder if similar parameters can be supported

**Comment by zhicwu** [comment]
To answer your question, there's no such option in this jdbc driver. Is there any specific reason you must call Connection.prepareStatement(sql, keyNames) method? Why not use prepareStatement(sql) instead? I may help if the use case is clear.
