### ISSUE TITLE
use insert (a,b,c) values (a,b,c) in jdbc  get wrong order

### ISSUE THREAD

**Issue by chengbi7** [ClickHouse/clickhouse-jdbc#1044]
When I use insert, I use setXXX to transform java entity into PreparedStatement.
But in some cases,  I get wrong order like 'Too many digits (11 > 10) in decimal value:  at row 0' 
And when I change the column order, I will get different error. So I suspect that I get the wrong order.
I find that the httpclient will return 400 error.

But not every entity will get error. Most of the examples will be inserted correctly, So I cant find out what problem it is.

This is the error example :
String json = "{\"market\":\"xx\",\"source\":\"xxx\",\"origin\":\"xxx\",\"destination\":\"xxx\",\"outboundDate\":1672243200000,\"inboundDate\":1673539200000,\"flightGroup\":\"xxxx,xxxx;xxxx,xxxx\",\"minPrice\":123.12,\"rmbMinPrice\":0,\"currency\":\"xxx\",\"priceProvider\":\"xxx\",\"priceItems\":[{\"price\":123.12,\"provider\":\"xxx\"}],\"attrs\":{},\"parseTime\":1660123919974}";

And the correct example :
String json = "{\"market\":\"xx\",\"source\":\"xxx\",\"origin\":\"xxx\",\"destination\":\"xxx\",\"outboundDate\":1684425600000,\"inboundDate\":1685721600000,\"flightGroup\":\"xxx,xxx;xxx,xxx\",\"minPrice\":123.12,\"rmbMinPrice\":0,\"currency\":\"xxx\",\"priceProvider\":\"xxx\",\"priceItems\":[{\"price\":123.12,\"provider\":\"xxx\"},{\"price\":123.12,\"provider\":\"xxx\"},{\"price\":222.22,\"provider\":\"xxx\"},{\"price\":123.41,\"provider\":\"xxx\"},{\"price\":123.99,\"provider\":\"xxx\"},{\"price\":234.69,\"provider\":\"xxx xx\"},{\"price\":123.99,\"provider\":\"xxx\"},{\"price\":321.69,\"provider\":\"xxx\"},{\"price\":123.0,\"provider\":\"xxx.xx\"}],\"attrs\":{},\"parseTime\":1660148409694}";

**Comment by zhicwu** [comment]
Hi @chengbi7, thanks for the report. Could you provide minimal code for reproducing?

**Comment by chengbi7** [comment]
> Hi @chengbi7, thanks for the report. Could you provide minimal code for reproducing?

            // price items
            List<PriceItem> priceItemList = value.getPriceItems();
            BigDecimal[] price = new BigDecimal[priceItemList.size()];
            String[] provider = new String[priceItemList.size()];
            for (int i = 0; i < priceItemList.size(); ++i) {
                PriceItem priceItem = priceItemList.get(i);
                price[i] = priceItem.getPrice();
                provider[i] = priceItem.getProvider();
            }

            // date
            Date inboundDate = value.getInboundDate() == null ? null
                    : new Date(value.getInboundDate().getTime());
            Date outboundDate = new Date(value.getOutboundDate().getTime());

            // attrs
            Map<Object, Object> attrs = new HashMap<>();
            value.getAttrs().forEach((k, v) -> {
                attrs.put(k, v.toString());
            });

            ps.setObject(1, attrs);
            ps.setString(2, value.getCurrency());
            ps.setString(3, value.getDestination());
            ps.setString(4, value.getFlightGroup());
            ps.setDate(5, inboundDate);
            ps.setString(6, value.getMarket());
            ps.setBigDecimal(7, value.getMinPrice());
            ps.setString(8, value.getOrigin());
            ps.setDate(9, outboundDate);
            ps.setString(10, value.getPriceProvider());
            ps.setString(11, value.getSource().name());
            ps.setBigDecimal(12, value.getRmbMinPrice());
            ps.setLong(13, value.getParseTime());
            ps.setArray(14, ps.getConnection().createArrayOf("arrayPrice", price));
            ps.setArray(15, ps.getConnection().createArrayOf("arrayProvider", provider));

            int affectRows = ps.executeUpdate();

**Comment by chengbi7** [comment]
> Hi @chengbi7, thanks for the report. Could you provide minimal code for reproducing?

public interface FlightPrice extends Serializable {

    /**
     * Flight Market
     */
    String getMarket();

    /**
     * Price source
     */
    @Nonnull
    PriceSource getSource();

    /**
     * Depart citycode
     */
    @Nonnull
    String getOrigin();

    /**
     * Arrive citycode
     */
    @Nonnull
    String getDestination();

    /**
     *
     */
    @Nonnull
    Date getOutboundDate();

    /**
     *
     */
    @Nullable
    Date getInboundDate();

    /**
     * 航组信息，去程和返程之间用;分隔，同一程之间用逗号分割
     * 例如: A001,A002;B001,B002
     */
    String getFlightGroup();

    /**
     * 真实最低价
     */
    BigDecimal getMinPrice();

    /**
     * 币种
     */
    String getCurrency();

    /**
     * 人民币下真实最低价
     */
    BigDecimal getRmbMinPrice();


    /**
     * 价格提供商
     *
     * @return
     */
    @Nullable
    String getPriceProvider();

    /**
     * @return
     */
    List<PriceItem> getPriceItems();

    /**
     * 不同源独有的属性
     *
     * @return
     */
    Map<String, Object> getAttrs();


    @Nonnull
    default Long getParseTime() {
        return System.currentTimeMillis();
    }

    /**
     * toString测试用例判断
     *
     * @return
     */
    default String toStringForAssert() {
        return getMarket() + getSource() + getOrigin() + getDestination() +
                getOutboundDate() + getInboundDate() + getFlightGroup() + getMinPrice() +
                getMinPrice() + getCurrency() + getRmbMinPrice() + getPriceProvider() +
                getPriceItems() + (getAttrs() != null ? new TreeMap<>(getAttrs()) : null);
    }

}

public interface PriceItem extends Serializable {

    /**
     * 价格
     */
    BigDecimal getPrice();

    /**
     * 价格供应商
     */
    String getProvider();

}

**Comment by zhicwu** [comment]
Thanks @chengbi7. What's the table structure and the code for creating the prepared statement?

As to the specific error, did you check ClickHouse/ClickHouse#10202?

**Comment by chengbi7** [comment]
> Thanks @chengbi7. What's the table structure and the code for creating the prepared statement?
> 
> As to the specific error, did you check [ClickHouse/ClickHouse#10202](https://github.com/ClickHouse/ClickHouse/issues/10202)?

Thanks for reply. When I change the column order in insert SQL， the error will change. I think its not because the long or decimal column

**Comment by chengbi7** [comment]
> > Thanks @chengbi7. What's the table structure and the code for creating the prepared statement?
> > As to the specific error, did you check [ClickHouse/ClickHouse#10202](https://github.com/ClickHouse/ClickHouse/issues/10202)?
> 
> Thanks for reply. When I change the column order in insert SQL， the error will change. I think its not because the long or decimal column


CREATE TABLE fltbickdbchdb.bluespace_parser ( `pricesource` String COMMENT 'field1comment', `origin` String COMMENT 'field2comment', `destination` String COMMENT 'field1comment', `outbounddate` DateTime COMMENT 'field2comment', `inbounddate` DateTime COMMENT 'field1comment', `flightgroup` String COMMENT 'field2comment', `minprice` Decimal(10, 2) COMMENT 'field1comment', `currency` String COMMENT 'field2comment', `rmbminprice` Decimal(10, 2) COMMENT 'field1comment', `priceprovider` String COMMENT 'field2comment', `attrs` Map(String, String) COMMENT 'field2comment', `ts` DateTime DEFAULT now() COMMENT 'tscomment', `market` String, `priceitems.price` Array(Decimal(10, 2)), `priceitems.provider` Array(String), `parsetime` Int64 ) ENGINE = ReplicatedMergeTree('/clickhouse/tables/ck100040066-{shard}/fltbickdbchdb/bluespace_parser', '{replica}') PARTITION BY toYYYYMMDD(ts) ORDER BY pricesource SETTINGS index_granularity = 8192

**Comment by chengbi7** [comment]
> Thanks @chengbi7. What's the table structure and the code for creating the prepared statement?
> 
> As to the specific error, did you check [ClickHouse/ClickHouse#10202](https://github.com/ClickHouse/ClickHouse/issues/10202)?

Can you get the same error ? Or shall I product complete data?

**Comment by zhicwu** [comment]
> Can you get the same error ? Or shall I product complete data?

Below works for me. What's the query you used for inserting? Can you modify below code to reproduce the issue at your end?

```java
Properties props = new Properties();
try (ClickHouseConnection conn = newConnection(props);
        ClickHouseStatement stmt = conn.createStatement()) {
    stmt.execute("drop table if exists test_write_decimals; "
            + "create table test_write_decimals(id Int8, d1 Decimal(10,2), d2 Decimal(10,2))engine=Memory");

    try (PreparedStatement ps = conn
            .prepareStatement("insert into test_write_decimals(id, d1, d2) values(?,?,?)")) {
        ps.setInt(1, 1);
        ps.setBigDecimal(2, new BigDecimal("123.12"));
        ps.setBigDecimal(3, new BigDecimal("321.69"));
        ps.executeUpdate();
    }

    try (ResultSet rs = stmt.executeQuery("select * from test_write_decimals")) {
        Assert.assertTrue(rs.next());
        Assert.assertEquals(rs.getInt(1), 1);
        Assert.assertEquals(rs.getBigDecimal(2), new BigDecimal("123.12"));
        Assert.assertEquals(rs.getBigDecimal(3), new BigDecimal("321.69"));
        Assert.assertFalse(rs.next());
    }
}
```

**Comment by chengbi7** [comment]
> > Can you get the same error ? Or shall I product complete data?
> 
> Below works for me. What's the query you used for inserting? Can you modify below code to reproduce the issue at your end?
> 
> ```java
> Properties props = new Properties();
> try (ClickHouseConnection conn = newConnection(props);
>         ClickHouseStatement stmt = conn.createStatement()) {
>     stmt.execute("drop table if exists test_write_decimals; "
>             + "create table test_write_decimals(id Int8, d1 Decimal(10,2), d2 Decimal(10,2))engine=Memory");
> 
>     try (PreparedStatement ps = conn
>             .prepareStatement("insert into test_write_decimals(id, d1, d2) values(?,?,?)")) {
>         ps.setInt(1, 1);
>         ps.setBigDecimal(2, new BigDecimal("123.12"));
>         ps.setBigDecimal(3, new BigDecimal("321.69"));
>         ps.executeUpdate();
>     }
> 
>     try (ResultSet rs = stmt.executeQuery("select * from test_write_decimals")) {
>         Assert.assertTrue(rs.next());
>         Assert.assertEquals(rs.getInt(1), 1);
>         Assert.assertEquals(rs.getBigDecimal(2), new BigDecimal("123.12"));
>         Assert.assertEquals(rs.getBigDecimal(3), new BigDecimal("321.69"));
>         Assert.assertFalse(rs.next());
>     }
> }
> ```

Thanks for reply.

When I use addBatch and executeBatch, the error disappear.
And I also find that sometimes my data has wrong decimal, maybe thats the reason.

Thanks again.

**Comment by zhicwu** [comment]
Good to know that it's been resolved. Please feel free to reopen this if you're certain there's no data issue at your end but something wrong with the driver(e.g. batch insert works but not executeUpdate).
