### ISSUE TITLE
Can I customize queryId in JDBC Driver?

### ISSUE THREAD

**Issue by zhengwenhao07** [ClickHouse/clickhouse-jdbc#1047]
Can I customize queryId in JDBC Driver?
![image](https://user-images.githubusercontent.com/101534190/185560307-5ce3190b-229c-45d3-ad5e-2fed70198ae6.png)

**Comment by zhicwu** [comment]
Hi @zhengwenhao07, looks like the question is same as ClickHouse/ClickHouse#40344.

Yes you can customize query but since it's not of jdbc standard, you'll have to use Java client. Besides implementing a `ClickHouseRequestManager` to customize query id for all queries, you can use below if you only want to customize query id for specific queries:

```java
try (ClickHouseResponse response = statement.unwrap(ClickHouseRequest.class).query("my-query-id", "select * from nytable").executeAndWait()) {
  for (Clickhouse record r : response.records()) {
    int i = r.getValue(0).asInteger();
    ...
  }
}
```

**Comment by zhengwenhao07** [comment]
> Hi @zhengwenhao07, looks like the question is same as [ClickHouse/ClickHouse#40344](https://github.com/ClickHouse/ClickHouse/issues/40344).
> 
> Yes you can customize query id, but since it's not part of jdbc standard, you'll have to use Java client. Besides implementing a `ClickHouseRequestManager` to customize query id for all queries, you can use below if you only want to customize query id for specific queries:
> 
> ```java
> try (ClickHouseResponse response = statement.unwrap(ClickHouseRequest.class).query("my-query-id", "select * from mytable").executeAndWait()) {
>   for (Clickhouse record r : response.records()) {
>     int i = r.getValue(0).asInteger();
>     ...
>   }
> }
> ```

Thank you for your help [zhicwu](https://github.com/zhicwu) ! It can work now!

**Comment by ltl0814** [comment]
> @zhicwu Hello, I saw that it’s possible to set a queryId before executing a query. My question is: can I use this queryId to cancel a specific query?

of course, u can use kill query where query_id ='{query_id}'

> @zhicwu Hello, I saw that it’s possible to set a queryId before executing a query. My question is: can I use this queryId to cancel a specific query?

yes u can ,  use : kill query where query = '{query_id}'
