### ISSUE TITLE
can not connect to clickhouse server

### ISSUE THREAD

**Issue by PromiseNev** [ClickHouse/clickhouse-jdbc#1049]
i use  
```
 <dependency>
           <groupId>com.clickhouse</groupId>
           <artifactId>clickhouse-jdbc</artifactId>
           <version>0.3.2-patch11</version>
       </dependency>
```

url = jdbc:ch://xxx.compute-1.amazonaws.com:8123/dbname

but this error log :

java.sql.SQLException: No client available, server ClickHouseNode

**Comment by viskvortsov** [comment]
same here

**Comment by zhicwu** [comment]
Hi @PromiseNev & @viskvortsov, could you use shaded jar as suggested in [readme](../clickhouse-jdbc/tree/master/clickhouse-jdbc#maven-dependency)?

```xml
<dependency>
    <!-- please stop using ru.yandex.clickhouse as it's been deprecated -->
    <groupId>com.clickhouse</groupId>
    <artifactId>clickhouse-jdbc</artifactId>
    <version>0.3.2-patch11</version>
    <!-- use uber jar with all dependencies included, change classifier to http for smaller jar -->
    <classifier>all</classifier>
    <exclusions>
        <exclusion>
            <groupId>*</groupId>
            <artifactId>*</artifactId>
        </exclusion>
    </exclusions>
</dependency>
```

**Comment by PromiseNev** [comment]
> 你好@PromiseNev&@viskvortsov[，你能按照自述](../clickhouse-jdbc/tree/master/clickhouse-jdbc#maven-dependency)文件中的建议使用阴影罐吗？
> 
> ```
> <dependency>
>     
>     <groupId>com.clickhouse</groupId>
>     <artifactId>clickhouse-jdbc</artifactId>
>     <version>0.3.2-patch11</version>
>     
>     <classifier>all</classifier>
>     <exclusions>
>         <exclusion>
>             <groupId>*</groupId>
>             <artifactId>*</artifactId>
>         </exclusion>
>     </exclusions>
> </dependency>
> ```

if  i use this, my project other code will error 
```
import org.apache.http.client.config.RequestConfig
import org.apache.http.client.methods.HttpGet
import org.apache.http.impl.client.HttpClientBuilder
```
all these package will not found
<img width="877" alt="Xnip2022-08-25_10-01-52" src="https://user-images.githubusercontent.com/16667188/186557237-25beab9f-0f15-417c-9cf3-fab0e6943313.png">

**Comment by zhicwu** [comment]
I see. The missing dependencies have been added back in ClickHouse/clickhouse-jdbc#1039.

You can add Apache http client dependency in your pom file if your code dependents on that.

**Comment by PromiseNev** [comment]
> I see. The missing dependencies have been added back in #1039.
> 
> You can add Apache http client dependency in your pom file if your code dependents on that.

it's work~

But  error log  this : 

```
java.sql.SQLException: Cannot set null to non-nullable column #19 [log_end_time DateTime64(3)]
```

now i use  this maven package,  no this error

```
  <dependency>
            <groupId>ru.yandex.clickhouse</groupId>
            <artifactId>clickhouse-jdbc</artifactId>
            <version>0.3.2</version>
        </dependency>
```

**Comment by zhicwu** [comment]
Is that possible that you were trying to insert `null` to the non-nullable column `log_end_time DateTime64(3)`? If you're uncertain, you may try to set nullAsDefault to see if it will fix the issue(e.g. `jdbc:ch://localhost/db?nullAsDefault=2`).

> now i use this maven package, no this error

The legacy driver uses text-based data format so it might work.

**Comment by PromiseNev** [comment]
> Is that possible that you were trying to insert `null` to the non-nullable column `log_end_time DateTime64(3)`? If you're uncertain, you may try to set nullAsDefault to see if it will fix the issue(e.g. `jdbc:ch://localhost/db?nullAsDefault=2`).
> 
> > now i use this maven package, no this error
> 
> The legacy driver uses text-based data format so it might work.


OK, i will test this parameter

**Comment by PromiseNev** [comment]
> Is that possible that you were trying to insert `null` to the non-nullable column `log_end_time DateTime64(3)`? If you're uncertain, you may try to set nullAsDefault to see if it will fix the issue(e.g. `jdbc:ch://localhost/db?nullAsDefault=2`).
> 
> > now i use this maven package, no this error
> 
> The legacy driver uses text-based data format so it might work.


After testing can be fully compatible, thank you very much! I would like to ask, where is the documentation of jdbc url related parameters can be viewed?

**Comment by zhicwu** [comment]
> where is the documentation of jdbc url related parameters can be viewed?

Please refer to [JDBC specific configuration](https://github.com/ClickHouse/clickhouse-jdbc/blob/master/clickhouse-jdbc/src/main/java/com/clickhouse/jdbc/JdbcConfig.java) and client options([common](https://github.com/ClickHouse/clickhouse-jdbc/blob/master/clickhouse-client/src/main/java/com/clickhouse/client/config/ClickHouseClientOption.java), [http](https://github.com/ClickHouse/clickhouse-jdbc/blob/master/clickhouse-http-client/src/main/java/com/clickhouse/client/http/config/ClickHouseHttpOption.java), [grpc](https://github.com/ClickHouse/clickhouse-jdbc/blob/master/clickhouse-grpc-client/src/main/java/com/clickhouse/client/grpc/config/ClickHouseGrpcOption.java), and [cli](https://github.com/ClickHouse/clickhouse-jdbc/blob/master/clickhouse-cli-client/src/main/java/com/clickhouse/client/cli/config/ClickHouseCommandLineOption.java)) for more.

**Comment by PromiseNev** [comment]
> > jdbc url相关参数的文档在哪里可以查看？
> 
> 有关更多信息，请参阅[JDBC 特定配置](https://github.com/ClickHouse/clickhouse-jdbc/blob/master/clickhouse-jdbc/src/main/java/com/clickhouse/jdbc/JdbcConfig.java)和客户端选项（[common](https://github.com/ClickHouse/clickhouse-jdbc/blob/master/clickhouse-client/src/main/java/com/clickhouse/client/config/ClickHouseClientOption.java)、[http](https://github.com/ClickHouse/clickhouse-jdbc/blob/master/clickhouse-http-client/src/main/java/com/clickhouse/client/http/config/ClickHouseHttpOption.java)、[grpc](https://github.com/ClickHouse/clickhouse-jdbc/blob/master/clickhouse-grpc-client/src/main/java/com/clickhouse/client/grpc/config/ClickHouseGrpcOption.java)和[cli](https://github.com/ClickHouse/clickhouse-jdbc/blob/master/clickhouse-cli-client/src/main/java/com/clickhouse/client/cli/config/ClickHouseCommandLineOption.java)）。

 
thank u very very much, this issue can close ~
