### ISSUE TITLE
What is the right way to specify wait_end_of_query HTTP setting in 0.3.1?

### ISSUE THREAD

**Issue by slvrtrn** [ClickHouse/clickhouse-jdbc#1060]
Currently, one of the projects is tied to that particular version and I wonder if it is (was) possible to pass [`wait_end_of_query=1`](https://clickhouse.com/docs/en/interfaces/http/#response-buffering) for the requests somehow.

**Comment by zhicwu** [comment]
Hi @slvrtrn, you can use: https://github.com/ClickHouse/clickhouse-jdbc/blob/9b72c8afc3ead981bb62b998ff64280095ceb317/clickhouse-jdbc/src/main/java/ru/yandex/clickhouse/settings/ClickHouseProperties.java#L976-L982

For example: https://github.com/ClickHouse/clickhouse-jdbc/blob/9b72c8afc3ead981bb62b998ff64280095ceb317/clickhouse-jdbc/src/test/java/ru/yandex/clickhouse/integration/ResultSummaryTest.java#L50-L64

**Comment by slvrtrn** [comment]
@zhicwu thank you very much! That's it, I was looking in the wrong place :)
