### ISSUE TITLE
BasicAuthentication Support

### ISSUE THREAD

**Issue by tpoll** [ClickHouse/clickhouse-jdbc#1069]
Is basic authentication supported in the most recent version of the clickhouse JDBC drivers? (`clickhouse-jdbc-0.3.2-patch11` is my version).

I found an older PR saying that everyone got switched over https://github.com/ClickHouse/clickhouse-jdbc/issues/522, but looks like it may not be true in the most revent version.

I tried using the `custom_http_headers` property to set my own auth header, but the client complains about double auth because https://github.com/ClickHouse/clickhouse-jdbc/blob/f285b73d45597e29cf36dff4daf4cb4f9f53453a/clickhouse-http-client/src/main/java/com/clickhouse/client/http/ClickHouseHttpConnection.java#L166 this method is still always attempting to add the `X-Clickhouse` user and password methods. I can't find anywhere in the codebase that ever attempts to set an accessToken based method.

Am I missing a way to properly configure the client to use a `BasicAuth` header?

**Comment by zhicwu** [comment]
Thank you @tpoll for the report. I'll fix it later today so that you can verify using nightly build.

**Comment by tpoll** [comment]
Thanks for the fast response @zhicwu. What time does the nightly build kickoff? Happy to test it out on our setup once it's available.

**Comment by zhicwu** [comment]
It's schedule to build at 3:55pm UTC and the packages will be generated in a few minutes. You can download latest snapshot from https://s01.oss.sonatype.org/content/repositories/snapshots/com/clickhouse/clickhouse-jdbc/0.3.3-SNAPSHOT/.

**Comment by tpoll** [comment]
@zhicwu  thanks, this seems to have allowed us to use the auth header!
