### ISSUE TITLE
How to enable multi-statement query?

### ISSUE THREAD

**Issue by LinhaiXu** [ClickHouse/clickhouse-jdbc#1084]
I got serval statement in one query, but I got exception like this `Syntax error (Multi-statements are not allowed)`, is there any relative configs or parameters that can add behind the url? Or where I can see all the parameters that supported in url

**Comment by zhicwu** [comment]
Hi @LinhaiXu, multi-statmenent query is supported by default without any config. It's a known issue that PreparedStatement does not support that. Could you share the exact query here? It sounds like a bug.

**Comment by LinhaiXu** [comment]
@zhicwu Thanks for answer! I was trying to use temporary  table and the query like this:
```
drop temporary table if exists temp_data;
create temporary table temp_data as
select ... from ...;

drop temporary table if exists ...;
......
```
BTW, jdbc version is `ru.yandex.clickhouse:clickhouse-jdbc:0.2.4` and then I changed to `com.clickhouse:clickhouse-jdbc:0.3.2` it's still not wok

**Comment by zhicwu** [comment]
Below works for me on DBeaver:
```sql
drop temporary table if exists temp_data;
create temporary table temp_data as
select number n, toString(number) s from numbers(10);
select * from temp_data
```

If you prefer programmatic way, please refer:

https://github.com/ClickHouse/clickhouse-jdbc/blob/42b1b2193931dc68b86cb5dfc86392d4c6d6601b/clickhouse-jdbc/src/test/java/com/clickhouse/jdbc/ClickHouseStatementTest.java#L238-L243

**Comment by LinhaiXu** [comment]
@zhicwu OK I got it, Thanks a lot! It does work for `Statement`, `PreparedStatement ` doesn't. But in most cases, `PreparedStatement ` is used more, will multi-statement be supported in future versions?

**Comment by zhicwu** [comment]
Sorry no plan at this point as I need to close v0.3.3 first. See my comments at #1065.
