### ISSUE TITLE
Table engine is not specified in CREATE query when executing df.write from pyspark to clickhouse

### ISSUE THREAD

**Issue by Vinhbuster** [ClickHouse/clickhouse-jdbc#1100]
Hello everyone, i was trying to write a new table from spark to clickhouse (this table ddl was not created in clickhouse yet) by this piece of code: 
```
df2.write\
    .format("jdbc")\
    .mode("overwrite")\
    .option("driver", "com.clickhouse.jdbc.ClickHouseDriver")\
    .option("url", "")\
    .option("user", "")\
    .option("password", "")\
    .option("dbtable", "default.test_write_from_spark")\
    .option("truncate", "true")\
    .option("batchsize", 10000)\
    .option("isolationLevel", "NONE")\
    .save()
```

Then i encounter the error :"**java.sql.SQLException: Code: 119. DB::Exception: Table engine is not specified in CREATE query. (ENGINE_REQUIRED) (version 22.10.1.61 (official build))**"

I think that i need to define the DDL and engine of the table in clickhouse in advance . But the question is, if i do not define the table in clickhouse first, can i write from spark to clickhouse by df.write ? If yes, what type of options should i put in the above code in order to do that? Thanks you guys very much.

**Comment by amosdoublec** [comment]
also looking for a solution here
any ways to pass parameters from spark to jdbc?
does any one know if this is a spark issue corresponding to this?

**Comment by Vinhbuster** [comment]
> also looking for a solution here any ways to pass parameters from spark to jdbc? does any one know if this is a spark issue corresponding to this?

I found an answer, you can take a look at my sample code:
```

dfFromRDD1.write\
    .format("jdbc")\
    .mode("overwrite")\
    .option("driver", "com.clickhouse.jdbc.ClickHouseDriver")\
    .option("url", "jdbc:clickhouse://your_connection_string here")\
    .option("user", "default")\
    .option("password", "default")\
    .option("dbtable", "default.test_write_from_spark")\
    .option("batchsize", 10000)\
    .option("isolationLevel", "NONE")\
    .option("truncate", "true")\
    .option("createTableOptions", "ENGINE=MergeTree ORDER BY (name)")\
    .save()
```

Also, you can find more detail about write option at here:
https://spark.apache.org/docs/latest/sql-data-sources-jdbc.html
