### ISSUE TITLE
JDBC4 is support or not?

### ISSUE THREAD

**Issue by modoojunko** [ClickHouse/clickhouse-jdbc#1109]
Hi,

I found hikariCP has one property：

__**connectionTestQuery**
If your driver supports JDBC4 we strongly recommend not setting this property. This is for "legacy" drivers that do not support the JDBC4 Connection.isValid() API. This is the query that will be executed just before a connection is given to you from the pool to validate that the connection to the database is still alive. Again, try running the pool without this property, HikariCP will log an error if your driver is not JDBC4 compliant to let you know. Default: none_

I use clickhouse-jdbc with hikariCP, so I want to know does this jdbc support jdbc4?

**Comment by zhicwu** [comment]
> I use clickhouse-jdbc with hikariCP, so I want to know does this jdbc support jdbc4?

Yes. Did you run into any issue?

**Comment by modoojunko** [comment]
> > I use clickhouse-jdbc with hikariCP, so I want to know does this jdbc support jdbc4?
> 
> Yes. Did you run into any issue?

I want to confirm that 'connectionQueryTest' is needed to anything like 'SELECT 1' or not.
