### ISSUE TITLE
ClickHouseGeoMultiPolygonValue And ClickHouseGeoPolygonValue Doubt

### ISSUE THREAD

**Issue by FWLamb** [ClickHouse/clickhouse-jdbc#1112]
**I have a question.**

![image](https://user-images.githubusercontent.com/58908699/196457785-39feecd0-5abf-4393-8029-0c55483b44d6.png)
![image](https://user-images.githubusercontent.com/58908699/196459225-3d83496d-3a1f-4ec3-bab6-e369de416e90.png)

Why is value converted to double[] instead of double[][][] or double[][][][], and how should value meet the conditions in the picture?

**Comment by zhicwu** [comment]
Hi @FWLamb, thanks for pointing out the bugs. It's a copy-paste issue again and I'll fix that in local when I get home.
