### ISSUE TITLE
String value 'NULL' corresponds to null value in ClickHouseResultSet.getArray method

### ISSUE THREAD

**Issue by lelik112** [ClickHouse/clickhouse-jdbc#1121]
https://github.com/ClickHouse/clickhouse-jdbc/blob/eb8b0878d33853ecfcfc4b81f7d0f618900bbb7b/clickhouse-jdbc/src/main/java/ru/yandex/clickhouse/response/ClickHouseResultSet.java#L351
In the case of Sting Array ['null', 'nUll', 'yulya', 'NULL']:
Actual result: 
ClickHouseArray with values ('null', 'nUll', 'yulya', null)
Expected result:
ClickHouseArray with values ('null', 'nUll', 'yulya', 'NULL')

**Comment by zhicwu** [comment]
Hi @lelik112, have you considered to upgrade driver?

**Comment by lelik112** [comment]
It is reproduced on the "0.3.1" version. Unfortunately currently, I can not check it on "0.3.2". Could you please close the issue if it has been already fixed?

**Comment by zhicwu** [comment]
Yes I can confirm the issue does not exist in new driver.

Unless you're stuck with JDK 7 or old version of ClickHouse, it's highly recommended to upgrade the driver for better stability and performance.
