### ISSUE TITLE
Problems with batch data insertion using JDBC0.2.6

### ISSUE THREAD

**Issue by trifolium-wang** [ClickHouse/clickhouse-jdbc#1122]
When I use JDBC0.2.6 for batch update, ParentStatment is used to set the parameter as follows:
```
String writeSql = "INSERT INTO bi_applet_ingredients(code, name, like_count," +
                "share_count,collect_count,add_basket_count)"
                + " VALUES (?,generateUUIDv4(),?,?,?,?)";

paramsBatch = [[1,1,1,1,1], [2,2,2,2,2]]

PreparedStatement ps = conn.prepareStatement(sql);
		final Map<Integer, Integer> nullTypeMap = new HashMap<>();
		for (Object[] params : paramsBatch) {
			// ..... set  Params...
			ps.addBatch();
		}
		ps.executeBatch()
```
This works fine when a function like generateUUIDv4() is not used, but when a function is used, the inserted data is wrong, as follows:
| Code | Name            | like_count | share_count | collect_count | add_basket_count |
| ---- | --------------- | ---------- | ----------- | ------------- | ---------------- |
| 1    | enerateUUIDv4( | 1          | 1           | 1             | 1                |
| 2    | enerateUUIDv4( | 2          | 2           | 2             | 2                |

**Comment by zhicwu** [comment]
Thanks for the report @trifolium-wang, it sounds like a bug in legacy driver. Could you upgrade driver and refer to batch insert examples at [here](https://github.com/ClickHouse/clickhouse-jdbc/blob/42b1b2193931dc68b86cb5dfc86392d4c6d6601b/examples/jdbc/src/main/java/com/clickhouse/examples/jdbc/Basic.java#L87)?

**Comment by zhicwu** [comment]
Close as legacy driver is no longer supported
