### ISSUE TITLE
INSERT INTO SELECT statement updateCount attribute is 1

### ISSUE THREAD

**Issue by trifolium-wang** [ClickHouse/clickhouse-jdbc#1125]
I use the` INSERT INTO t1 SELECT c FROM t2` statement for database INSERT operations, but the executeUpdate method returns 1

**Comment by zhicwu** [comment]
Hi @trifolium-wang, if you're using most recent ClickHouse releases(22.8 or above), it should work by default. In case you're running an older version, you may set `custom_settings` to `send_progress_in_http_headers=1` to make it work.

Moreover, the number returned from server may not match your expectation all the time, for example: ClickHouse/ClickHouse#18237.

**Comment by trifolium-wang** [comment]
Thank's,  I'm will use version numbers for count.
