### ISSUE TITLE
Write time field data loss precision.

### ISSUE THREAD

**Issue by gaaraG** [ClickHouse/clickhouse-jdbc#1126]
By checking the code, it is found that the time field will be converted to the time zone before writing. When my time zone is the same, it will also be converted. Can the comparison of time zones be more reasonable? But the precision should not be lost when converting time zone.
![截图_选择区域_20221115135704](https://user-images.githubusercontent.com/85996062/202058410-95ad973b-24f3-4d29-8068-7b6e9c4c7efc.png)

**Comment by gaaraG** [comment]
I will submit a PR later.

**Comment by zhicwu** [comment]
The fix has been merged into develop branch and will be available in nightly build later today.

A workaround would be use setObject and LocalDateTime instead.
