### ISSUE TITLE
Master build error: package not found

### ISSUE THREAD

**Issue by JackyWoo** [ClickHouse/clickhouse-jdbc#1142]
```
[INFO] -------------------------------------------------------------
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] 未与 -source 8 一起设置引导类路径
/Users/wujianchao5/project/github/clickhouse-jdbc/clickhouse-jdbc/src/main/java/ru/yandex/clickhouse/jdbc/parser/ClickHouseSqlParser.java:[5,16] 错误: 程序包org.slf4j不存在
[ERROR] /Users/wujianchao5/project/github/clickhouse-jdbc/clickhouse-jdbc/src/main/java/ru/yandex/clickhouse/jdbc/parser/ClickHouseSqlParser.java:[6,16] 错误: 程序包org.slf4j不存在
[ERROR] /Users/wujianchao5/project/github/clickhouse-jdbc/clickhouse-jdbc/src/main/java/ru/yandex/clickhouse/jdbc/parser/ClickHouseSqlParser.java:[20,25] 错误: 找不到符号
  符号:   类 Logger
  位置: 类 ClickHouseSqlParser

...
```

**Comment by zhicwu** [comment]
`mvn compile` (JDK8) or `mvn -Drelease clean compile` will generate the parser. The latest code is on develop branch by the way.

**Comment by zhicwu** [comment]
It looks like `clickhouse-client` is not available in your maven repo. If you're building `clickhouse-cli-client` manually, you'd better install `clickhouse-java` (the parent module) and `clickhouse-client` (dependency) first.

**Comment by JackyWoo** [comment]
I built the whole project not `clickhouse-cli-client`.

**Comment by JackyWoo** [comment]
> It's a multi-module project. Could you try `mvn -Drelease -DskipTests clean install`?

Yes I used this.

**Comment by zhicwu** [comment]
> I used this.

But the command line you posted above uses `compile` not `install`.

**Comment by JackyWoo** [comment]
Thanks for your patience.  I built seccessfully with JDK8 with command `mvn -DskipITs -DskipTests -Drelease clean verify`.
