### ISSUE TITLE
mvn tests

### ISSUE THREAD

**Issue by antip00** [ClickHouse/clickhouse-jdbc#1150]
Can you describe, how I can run maven tests for clickhouse jdbc?

**Comment by zhicwu** [comment]
Hi @antip00, if you're using JDK 8, try `mvn clean install` to build, test, and install all modules. For JDK 11 or above, `~/.m2/toolchains.xml` is required and please use `mvn -Drelease clean install` instead.

More details are available in [README](/ClickHouse/clickhouse-jdbc#build-with-maven).

**Comment by antip00** [comment]
Thanks, I figured out how to do it.
