### ISSUE TITLE
0.3.2.11 UInt64 values seems to be Int64 (negative values)

### ISSUE THREAD

**Issue by wizzard0** [ClickHouse/clickhouse-jdbc#1158]
```
Version: 0.3.2.11
Clickhouse Server: 22.8, 22.12 (doesn't matter)
```
How to reproduce:

- open DataGrip (any version)
- select "official driver"
- run the following in the query console:
```
select toString(toUInt64(toUInt128('18402707827004109123'))); -- 18402707827004109123
select (toUInt64(toUInt128('18402707827004109123'))); -- -44036246705442493
```
Workaround: use https://github.com/housepower/ClickHouse-Native-JDBC (if native tcp connection is available ofc)

**Comment by zhicwu** [comment]
Hi @wizzard0, this should have been fixed. Could you try the most recent nightly build at [here](https://s01.oss.sonatype.org/content/repositories/snapshots/com/clickhouse/clickhouse-jdbc/0.3.3-SNAPSHOT/)?

**Comment by wizzard0** [comment]
Yes, at first glance seems to be fixed, thanks! Will try more today.
