### ISSUE TITLE
Alternatives to BalancedClickhouseDataSource in com.clickhouse.jdbc

### ISSUE THREAD

**Issue by mywrong** [ClickHouse/clickhouse-jdbc#1159]
I have a piece of java code as follows：

```
BalancedClickhouseDataSource ckDataSource = new BalancedClickhouseDataSource(url, properties);
return ckDataSource.getConnection();
```
It uses ru.yandex.clichouse to get connection.
Now I want to change to com.clickhouse.jdbc, is there any alternative feasible way?

**Comment by zhicwu** [comment]
Hi @mywrong, you just need to specify multiple hosts in connection string. Please refer to #956 for more options and usage.
