### ISSUE TITLE
How to pass session parameters with the request?

### ISSUE THREAD

**Issue by Blackmorse** [ClickHouse/clickhouse-jdbc#1180]
I want to pass `insert_quorum` parameter along with my insert request:

```
import com.clickhouse.jdbc.ClickHouseDataSource

var props = new Properties()
props.setProperty("insert_quorum", "3")
props.setProperty("user", "some_user")
props.setProperty("password", "some_password")

var clickhouseDS = new ClickHouseDataSource("jdbc:clickhouse://localhost:8123", props)
var connection = clickhouseDS.getConnection()

var statement = connection.prepareStatement("INSERT INTO default.aaa values (?)")

statement.setLong(1, 12L)

statement.addBatch()
statement.executeBatch()
```

This approach does not work and `insert_quorum` is not applied.  Howerver, `user` and `password` are passed correctly.

In case I'm changing import to `import ru.yandex.clickhouse.ClickHouseDataSource`, it's working again.

So seems that in old version passing params throught the properties is working. What approach should be used in the current version?

Edit: passing through URL is not working as well: `jdbc:clickhouse://localhost:8123?insert_quorum=3`

**Comment by zhicwu** [comment]
Hi @Blackmorse, many server settings were removed in new driver, because you can use `custom_http_headers` or (`custom_settings` in v0.4+) instead. For examples:
1. specify in connection string
  ```java
  String connectionString = "jdbc:ch:http://localhost/default?custom_http_headers=setting1%3Dvalue1%2Csetting2%3Dvalue2";
  ```
2. specify in connection properties
  ```java
  Properties props = new Properties();
  props.setProperty("custom_http_headers", "setting1=value1,setting2=value2");
  ```

Alternatively, you can specify setting in your insert query(pay attention the grammar changed after 22.10), or better managed in user profile.

**Comment by Blackmorse** [comment]
@zhicwu 
I've tried all 3 options (using 3.2 version):

```
    val props = new Properties()
    props.setProperty("custom_http_headers", "insert_quorum=3")
    val clickhouseDS = new ClickHouseDataSource("jdbc:clickhouse://localhost:8123?custom_http_headers=insert_quorum%3D3", props)
    val connection = clickhouseDS.getConnection()

    val statement = connection.prepareStatement("INSERT INTO default.test values (?) SETTINGS insert_quorum=3")

    statement.setLong(1, 12L)

    statement.addBatch()
    statement.executeBatch()
```

`insert_quorum` is still not applied

**Comment by zhicwu** [comment]
By `3.2`, did you mean `0.3.2` or `0.3.2-patch11`? It should work if you're using the latter. Will check this one right after submitting a new PR.

**Comment by Blackmorse** [comment]
@zhicwu , Sorry, my current version is `0.3.2-patch11`

**Comment by zhicwu** [comment]
Sorry for the typo, it should be `custom_http_params`, not `custom_http_headers`. Just tried below code. I saw the query was posted to URL `/?insert_quorum=3&extremes=0`, which was expected. And then I checked `system.query_log.Settings`, which also contains the same setting.

```java
Properties props = new Properties();
props.setProperty("custom_http_params", "insert_quorum=3");
```

**Comment by Blackmorse** [comment]
This does help, thank you

Also, what is the reason for choosing that way of design? Previously it was very straightforward to pass parameters to request.
Currently, passing some `http_params` to JDBC driver looks very tricky. Also user should concatenate them if there are more than one parameter.

**Comment by zhicwu** [comment]
> This does help, thank you

Good to know :)

> Also, what is the reason for choosing that way of design? Previously it was very straightforward to pass parameters to request.

Understood. In the past all supported server settings were maintained in a large class `ClickHouseProperties`, which is never up-to-date. I figured it's easier to provide an extensible option for user to custom settings as needed.

> Currently, passing some `http_params` to JDBC driver looks very tricky. Also user should concatenate them if there are more than one parameter.

Yes and it's limited to http protocol. That's why it will be soon replaced by `custom_settings` added in #1059.
