### ISSUE TITLE
No client available error occured.

### ISSUE THREAD

**Issue by myabcc17** [ClickHouse/clickhouse-jdbc#1185]
I'm configuring a placement schedule in the Spark2.4.5-scala2.12 environment.

In local tests, the dataframe is inserted well into the Clickhouse table. However, spark-submit does not work on the yarn cluster.

A specific domain 80 port is in service as a k8s 8123 port.

I did not specify the database name in jdbc-url. Because when I save the data frame, I tried to write db in the table name.

But if you look at the error, I suspect that it's caused by jdbc-url with a db named default.
```
curl http://{host}
-> Ok.

curl http://{host}/default
-> There is no handle /default
(Could this be the cause?)
```

This is an error caused by a spark-job.
```
client token: Token { kind: YARN_CLIENT_TOKEN, service:  }
	 diagnostics: User class threw exception: java.sql.SQLException: No client available, server ClickHouseNode [uri=http://{host}:80/default]@-323215936
```

This code is stored in clickhouse using dataframe.
```
val url = "jdbc:clickhouse://{host}:80"

val properties = new Properties()
properties.setProperty("user", "user")
properties.setProperty("password", "password")
properties.setProperty("ssl", "false")

df.write
  .mode(SaveMode.Append)
  .option("driver", "com.clickhouse.jdbc.ClickHouseDriver")
  .jdbc(url, s"{db_name}.$table", properties)
```

**Comment by zhicwu** [comment]
Hi @myabcc17, could you use shaded jar(uber jar with all required dependencies), for example: `clickhouse-jdbc-0.3.2-patch11-all.jar`? You can get that from either maven central or github releases.

> curl http://{host}/default
> -> There is no handle /default
> (Could this be the cause?)

Maybe not. What will you get from `http_proxy='' ALL_PROXY='' curl -v 'http://{host}:80/?query=select+1'`?

**Comment by myabcc17** [comment]
I'm using "com.clickhouse" % "clickhouse-jdbc" % "0.3.2-patch11",

result is 1.

**Comment by zhicwu** [comment]
> I'm using "com.clickhouse" % "clickhouse-jdbc" % "0.3.2-patch11",

Can you add `classifier "all"` as well?

> result is 1.

That means no connectivity issue between your container and CH server.

**Comment by myabcc17** [comment]
@zhicwu 
I'm using sbt build tool. But, `0.3.2-patch-11-all` is not found, also `clickhouse-jdbc-all` too.
Where i add classifier "all"?

**Comment by myabcc17** [comment]
@zhicwu 
wow. it solved !! thank you
