### ISSUE TITLE
The output for Date and DateTime types is incorrect for JDBC-driver (versions 0.3.2.9, 0.3.2.11)

### ISSUE THREAD

**Issue by InquisitorGray** [ClickHouse/clickhouse-jdbc#1187]
The output for Date and DateTime types is incorrect if JDBC-driver (versions 0.3.2.9, 0.3.2.11) with the com.clickhouse.jdbc.ClickHouseDriver class is used. (The JDBC-driver with ru.yandex.clickhouse.ClickHouseDriver class returns correct results)
For example, the query
`SELECT (toDateTime64(DATE_ADD(YEAR, -50, parseDateTime64BestEffort('1980-01-01 00:00:00.000001' ,6,'UTC')) , 6));`
is expected to return `1930-01-01 00:00:00.000001`, but incorrectly returns `1929-12-31T23:59:59.999999`

The internal DBMS representation of Date and DateTime types is still correct, since the query
`SELECT toString(toDateTime64(DATE_ADD(YEAR, -50, parseDateTime64BestEffort('1980-01-01 00:00:00.000001' ,6,'UTC')) , 6));`
returns the string `"1930-01-01 00:00:00.000001"`

The issue reproduces on ClickHouse (ver. 21.8.13.6).

**Comment by zhicwu** [comment]
Hi @InquisitorGray, it's probably a server side issue. I can reproduce the issue on 21.8 but the same JDBC driver works well on 22.8. Perhaps you can upgrade database to a more recent release?

```bash
curl -H 'X-ClickHouse-Format: RowBinary' \
  -d "SELECT (toDateTime64(DATE_ADD(YEAR, -50, parseDateTime64BestEffort('1980-01-01 00:00:00.000001' ,6,'UTC')) , 6))" \
  -s 'localhost:8123' | xxd

# 21.8.13.6
0000000: ff3f 7bf2 f083 fbff

# 22.8.6.71
0000000: 0140 7bf2 f083 fbff
```
