### ISSUE TITLE
Sessions support

### ISSUE THREAD

**Issue by Aivean** [ClickHouse/clickhouse-jdbc#127]
Hi,

Since sessions [are now supported for http interface](https://github.com/yandex/ClickHouse/blob/58db4b7be4f326f5c30dccf3372172d83912f282/dbms/tests/queries/0_stateless/00463_sessions_in_http_interface.sh) it would be nice to have them supported in JDBC as well.

Thanks.

**Comment by alex-krash** [comment]
@Aivean , it is supported via using ru.yandex.clickhouse.ClickHousePreparedStatement and ru.yandex.clickhouse.ClickHouseStatement. They have a methods, executeQuery, that will allow you to pass ru.yandex.clickhouse.settings.ClickHouseQueryParam#SESSION_ID as an argument.

**Comment by filimonov** [comment]
To make the session last you may also need to make keepalive pings.

**Comment by zhicwu** [comment]
FYI, session will be enabled automatically when you execute multi-statement SQL. Starting from 0.3.1, you can do below:
```java
try (Statetement s = connection.createStatement()) {
  s.execute("select 1"); // no session as it's single statement

  // session will be enabled automatically with a generated id(if no session id found in the context)
  s.execute(
    "set allow_experimental_map_type=1;"
    + "create table if not exists test_map_support(m Map(UInt8, String)) engine=Memory;"
    + "insert into ...");
}
```
