### ISSUE TITLE
Arbitrary Query Parameter?

### ISSUE THREAD

**Issue by jcdang** [ClickHouse/clickhouse-jdbc#158]
We are load balancing queries on clickhouse with affinity based on a query string parameter.   It would be useful if there was some arbitrary parameter we could use to route the queries.  We're using temp tables and a group of queries need to go to the same box.

**Comment by blinkov** [comment]
Why can't you just keep separate jdbc connections to all instances and choose the appropriate one depending on that query parameter?

**Comment by jcdang** [comment]
We can, although it's more of an architectural design reason to keep this kind of logic out of the application.  You don't generally don't want to manage load balancing as a concern at an app level.

**Comment by meshpaul** [comment]
Sounds like you need a single instance of CH DB for temp work. Or it should be replicated.

**Comment by jcdang** [comment]
Correct.  It's a bit of both since the primary tables are replicated.  The temp tables are used for short term filtering and processing.

**Comment by zhicwu** [comment]
Starting from 0.3.2, both request headers and query parameters can be customized. Of course this is limited to http protocol.

* Java Client - use `CUSTOM_HEADERS` and `CUSTOM_PARAMS` options:
  ```java
  request.option(ClickHouseHttpOption.CUSTOM_HEADERS, "Header 1=value1,Header 2=value2")
    .option(ClickHouseHttpOption.CUSTOM_PARAMS, "parameter1=value1,parameter2=value2")
  ```
* JDBC - use `custom_http_headers` and `custom_http_params` two properties.
