### ISSUE TITLE
ClickHouse exception, code: 1002 failed to respond

### ISSUE THREAD

**Issue by kingbacks** [ClickHouse/clickhouse-jdbc#174]
**description**

a function run two sql that we mark them as A and B,following is my tests:
1、remove A, B is fine;
2、put Thread.sleep(1000) between A and B, is fine;
3、set keep-alive-timeout to bigger such as 50s, is fine;
4、otherwise,it run as exception:failed to respond.

I resolve it by setting keep-alive-timeout to 50s,but I don't know it will effect to the clickhouse server.

**Comment by perez1987** [comment]
Any solution?¿

**Comment by kingbacks** [comment]
tks
