### ISSUE TITLE
[Suggestion] change the log4j level in ClickHouseDriver's constructor

### ISSUE THREAD

**Issue by lamber-ken** [ClickHouse/clickhouse-jdbc#196]
Hi，when use dataSource.scheduleActualization(1, TimeUnit.SECONDS), the `logger.info("Creating connection");` create many logs. it's better to change `info` to `debug`

here's the link 
[https://github.com/yandex/clickhouse-jdbc/blob/master/src/main/java/ru/yandex/clickhouse/ClickHouseDriver.java](https://github.com/yandex/clickhouse-jdbc/blob/master/src/main/java/ru/yandex/clickhouse/ClickHouseDriver.java)

```java
public ClickHouseConnection connect(String url, ClickHouseProperties properties) throws SQLException {
        if (!acceptsURL(url)) {
            return null;
        }
        logger.info("Creating connection");
        ClickHouseConnectionImpl connection = new ClickHouseConnectionImpl(url, properties);
        registerConnection(connection);
        return LogProxy.wrap(ClickHouseConnection.class, connection);
    }
```

**Comment by gedOHub** [comment]
Hello,
I'm effected also. Generates tons of useless info messages about "Creating connection"

**Comment by AlexMAS** [comment]
I vote for this improvement too. :)
