### ISSUE TITLE
How to set timezone? For example Atlantic/Canada

### ISSUE THREAD

**Issue by den-crane** [ClickHouse/clickhouse-jdbc#202]
<groupId>ru.yandex.clickhouse</groupId>
    <artifactId>clickhouse-jdbc</artifactId>
    <version>0.1.39</version>

```
                String url = "jdbc:clickhouse://ch:8123/default";

                ClickHouseProperties props = new ClickHouseProperties();
                props.setUseServerTimeZone(false);
                props.setUseServerTimeZoneForDates(false);

                props.setUseTimeZone("Canada/Atlantic");
                props.setUser("default");
                props.setPassword("");


                ClickHouseDataSource ds = new ClickHouseDataSource(url,props);
                System.out.println(ds.getProperties().getUseTimeZone());
                Connection connection = ds.getConnection();


                Statement stmt = connection.createStatement();
                ResultSet rs;

                rs = stmt.executeQuery("select toDate(0), now()");
                while ( rs.next() ) {
                    System.out.println( rs.getString(1));
                    System.out.println( rs.getString(2));
                }
                connection.close();
```
Output:
```
Canada/Atlantic
0000-00-00
2018-04-09 18:59:39
```
But 18:59:39 === UTC, my time is:
| => date
Mon  9 Apr 2018 16:00:12 ADT

**Comment by serebrserg** [comment]
Timezone doesn't affect getString(), but only affects getDate() and getTime() by parsing the textual value returned from the server in the timezone you set (or server timezone by default).
To achieve correct Date object, the timezone set to driver must be the timezone of server (it prints date to text in its timezone, and to achieve correct result it must be parsed in same timezone).
If getString() returns time in UTC, I guess your server has UTC timezone, so you either should not override server timezone or set it explicitly to UTC to achieve correct Date object through getDate()

**Comment by den-crane** [comment]
OK.
My goal is to remove a dependency of client's TZ.
I want to fix jdbc timezone to UTC only (servers is always = UTC) how to achieve this?
I would like to disable all time conversion in clickhouse-jdbc

I need something like this: 
select toDateTime('2017-03-01 23:59:11') .rs.getTimestamp() === '2017-03-01 23:59:11'

BUT:
```
                props.setUseServerTimeZone(false);
                props.setUseServerTimeZoneForDates(false);
                props.setUseTimeZone("UTC");
                rs = stmt.executeQuery("select toDateTime('2017-03-01 23:59:11')");
                    System.out.println(  rs.getTimestamp(1));
```
output is wrong: 2017-03-01 19:59:11.0


```
                props.setUseServerTimeZone(true);
                props.setUseServerTimeZoneForDates(true);
```
output is wrong again:  2017-03-01 19:59:11.0


```
                props.setUseServerTimeZone(false);
                props.setUseServerTimeZoneForDates(false);
                props.setUseTimeZone("Canada/Atlantic");```
output is right: 2017-03-01 23:59:11.0

which is really confusing, to achieve the UTC results need to set the right client's TZ.

**Comment by enqueue** [comment]
Hello @den-crane Please note that calling `toString` on a `TimeStamp` uses the JVM's time zone. The timestamp itself is only a number, but Java reconstructs a Calendar based on your current time zone to format the output. Consider the following (ClickHouse server running with UTC):

```
 // set JVM time zone
TimeZone.setDefault(TimeZone.getTimeZone("US/Pacific"));
     
// init connection
String url = "jdbc:clickhouse://localhost:8123/default";
ClickHouseProperties props = new ClickHouseProperties();
props.setUseServerTimeZone(true);
props.setUseServerTimeZoneForDates(true);
ClickHouseDataSource ds = new ClickHouseDataSource(url,props);
        
ResultSet rs = ds.getConnection().createStatement().executeQuery(
    "SELECT toDateTime('2019-01-08 13:37:00')");
rs.next();
Timestamp ts = rs.getTimestamp(1);
```
output time stamp as millis:
``` System.out.println(ts.getTime());```
1546954620000

output using JVM time zone:
```System.out.println(ts);```
2019-01-08 05:37:00.0 (as you observed)

parse and output using US/Pacific
```
LocalDateTime dt = LocalDateTime.ofInstant(
    Instant.ofEpochMilli(ts.getTime()),
    ZoneId.of("US/Pacific"));
System.out.println(dt.toString());
```
2019-01-08T05:37

parse and output using UTC:
```
LocalDateTime dtUTC = LocalDateTime.ofInstant(
    Instant.ofEpochMilli(ts.getTime()),
    ZoneId.of("UTC"));
System.out.println(dtUTC.toString());```

2019-01-08T13:37

I think you were already on the right track, but Java output sometimes uses your JVM's time zone for formatting time stamps.

**Comment by zhicwu** [comment]
See #680.
