### ISSUE TITLE
Change logging level from info to debug

### ISSUE THREAD

**Issue by gedOHub** [ClickHouse/clickhouse-jdbc#210]
Hello,

Can logging level be changed from info to debug level. While using this driver generates lots of useless log entries about regenerated connection list. I have located line which generates thous entries.

https://github.com/yandex/clickhouse-jdbc/blob/3b9907b7b6fcd2966eb75bbe1de6b11c9a5fcdc6/src/main/java/ru/yandex/clickhouse/ClickHouseDriver.java#L57

**Comment by meshpaul** [comment]
I am not so sure this should be debug. Ex we are running regression/load tests on our CH and app that's fronted by VIP to CH and thanks to that found an issue with VIP/network configuration to CH.  Not sure what your setup is but we did not see it when we have pointed our app to different VIP made for our PROD. Or at least we see much much less off these.  Meaning is all works as expected on your end you can set this WARN in your logger Config

**Comment by gedOHub** [comment]
I'm getting lots of this messages printed out to my STDOUT.
My `log4j` config:
```java
log4j.rootLogger=INFO, stdout

log4j.appender.stdout=org.apache.log4j.ConsoleAppender
log4j.appender.stdout.layout=org.apache.log4j.PatternLayout

log4j.appender.stdout.layout.ConversionPattern=%d %5p (%F:%L) %m%n
```

STDOUT output example:
```
...
May 03 12:41:26  java[1947]: 2018-05-03 12:41:26,892  INFO (ClickHouseDriver.java:57) Creating connection
May 03 12:41:26  java[1947]: 2018-05-03 12:41:26,903  INFO (ClickHouseDriver.java:57) Creating connection
May 03 12:41:26  java[1947]: 2018-05-03 12:41:26,913  INFO (ClickHouseDriver.java:57) Creating connection
May 03 12:41:27  java[1947]: 2018-05-03 12:41:27,892  INFO (ClickHouseDriver.java:57) Creating connection
May 03 12:41:27  java[1947]: 2018-05-03 12:41:27,902  INFO (ClickHouseDriver.java:57) Creating connection
May 03 12:41:27  java[1947]: 2018-05-03 12:41:27,911  INFO (ClickHouseDriver.java:57) Creating connection
May 03 12:41:28  java[1947]: 2018-05-03 12:41:28,892  INFO (ClickHouseDriver.java:57) Creating connection
May 03 12:41:28  java[1947]: 2018-05-03 12:41:28,904  INFO (ClickHouseDriver.java:57) Creating connection
May 03 12:41:28  java[1947]: 2018-05-03 12:41:28,919  INFO (ClickHouseDriver.java:57) Creating connection
...
```

I'm constantly checking if connection to clickhouse-server are down or not with
```java
...
this.clickhouse.scheduleActualization(1, TimeUnit.SECONDS);
...
```

So, may be problem in code?

**Comment by meshpaul** [comment]
I suggest to read about how your logging implementation works.  And what it's capable off.  Check this exaple out https://gist.github.com/chetan/1528709#file-log4j-properties use it and experiment with  logging prop file for that class  ru.yandex.clickhouse.ClickHouseDriver warn

**Comment by AlexMAS** [comment]
I vote for this improvement too. :)
