### ISSUE TITLE
support thin jdbc jar

### ISSUE THREAD

**Issue by cmdares** [ClickHouse/clickhouse-jdbc#217]
current dependence is too large.
so mark to build in thin jdbc.

**Comment by doom369** [comment]
+ for this one.

The first candidate for removal is Guava library.
Also, for those who use only tcp httclient dependency could be dropped too.

**Comment by doom369** [comment]
@cmdares check it here - https://github.com/blynkkk/clickhouse4j

**Comment by zhicwu** [comment]
The new JDBC driver in 0.3.2 supports both http and grpc interfaces. If you only need http, the shaded jar is around 770KB. Guava, Jackson, and Apache HTTP Client are all removed.
