### ISSUE TITLE
CREATE TABLE IF NOT EXISTS should not throw an exception when the table exists.

### ISSUE THREAD

**Issue by HunterSherms** [ClickHouse/clickhouse-jdbc#226]
"IF NOT EXISTS" implies that nothing should be done if the table already exists.

Currently an exception is thrown:

```Caused by: ru.yandex.clickhouse.except.ClickHouseException: ClickHouse exception, code: 253, host: xxx.xx.xx.xx, port: xxxx; Code: 253, e.displayText() = DB::Exception: There was an error on ip-xxx-xx-xx-xx.ec2.internal: Code: 253, e.displayText() = DB::Exception: Replica /clickhouse/tables/13/table_name/replicas/hostname-us-east-1 already exists., e.what() = DB::Exception, e.what() = DB::Exception```

**Comment by serebrserg** [comment]
Hello,
This is the server who throws the exception, while the driver just
translates it into Java exception.
As I see in the error message the thing is not in table itself, but in
replica.
I guess you are trying to create a replicated table with zookeeper path
that is already used in another table.

вт, 21 авг. 2018 г., 17:29 Hunter Sherman <notifications@github.com>:

**Comment by HunterSherms** [comment]
> I guess you are trying to create a replicated table with zookeeper path
> that is already used in another table.

This is because the table already exists.
