### ISSUE TITLE
executeUpdate only return 1 for mulitiple row insert.

### ISSUE THREAD

**Issue by etah000** [ClickHouse/clickhouse-jdbc#227]
String sqlStr="insert into tab1 values (1, 'a'), (2, 'b);";
int ret = stmt.executeUpdate(sqlStr);

"ret" is always equal to one, it should return 2 for the above example. The same statement returns correct result in "clickhouse-client", that is, "2 rows in set. Elapsed: 0.023 sec."

**Comment by zhicwu** [comment]
Fixed on develop and will be released as part of 0.2.6. You'll need to set query parameter `send_progress_in_http_headers` to true.

**Comment by arjenzhou** [comment]
hi, @zhicwu 
it seems same issue in 0.3.1-patch
