### ISSUE TITLE
How can I get ResultSetMetaData without actual execution query ?

### ISSUE THREAD

**Issue by tac0x2a** [ClickHouse/clickhouse-jdbc#235]
Hello.

Now, I'm trying to implement of `ClichHousePreparedStatementImpl#getMetaData()` for making runnable on [embulk-input-jdbc](https://github.com/embulk/embulk-input-jdbc).

This implementation of method needs result of execution query first.
But we don't want to execute query actual.
So I want to know how can I get `ResultSetMetaData` without execute query actual like `QUERY_DESCRIBE_ONLY` in [pgjdbc](https://github.com/pgjdbc/pgjdbc).

I guess, it is possible by setting arguments `additionalDBParams` or `additionalRequestParams` for `ClickHouseStatementImpl#executeQuery`....

Best regards,

**Comment by serebrserg** [comment]
Hello. To get metadata without executing query one should add limit 0 to the query.
Connecting the issue with your PR https://github.com/yandex/clickhouse-jdbc/pull/238

**Comment by enqueue** [comment]
@tac0x2a have you tried querying meta data using a recent clickhouse-jdbc release? What are your experiences?
