### ISSUE TITLE
PreparedStatementParser - VALUES Pattern

### ISSUE THREAD

**Issue by RazieI** [ClickHouse/clickhouse-jdbc#276]
Добрый день.

В классе PreparedStatementParser, возможно, неверно написан паттерн:
```
  private static final Pattern VALUES = Pattern.compile(
        "(?i)INSERT\\s+INTO\\s+[^\'\"]+VALUES\\s*\\(");
```

Он устанавливает значение valuesMode из-за чего запросы вида:

- INSERT INTO tmp.table("enclosed column") VALUES (?) не работают корректно т.к. valuesMode false.
- INSERT INTO tmp.table(enclosed column) VALUES (?) не работают т.к. очевидно, что подобный sql неверен.

Каким образом подразумевается вставка данных в таблицы с именами колонок, содержащими, например, пробел?

**Comment by enqueue** [comment]
Hi @RazieI, sorry I do not understand any Russian. Judging from your SQL statements I would assume that you have an issue with PreparedStatements not working nicely with escaped column names. Have you tried to use backtick-style escape pattern for your column, e.g.

```
INSERT INTO tmp.table(`enclosed column`) VALUES (?)
```

The parser is currently very simple.

**Comment by RazieI** [comment]
> Hi @RazieI, sorry I do not understand any Russian. Judging from your SQL statements I would assume that you have an issue with PreparedStatements not working nicely with escaped column names. Have you tried to use backtick-style escape pattern for your column, e.g.
> 
> ```
> INSERT INTO tmp.table(`enclosed column`) VALUES (?)
> ```
> The parser is currently very simple.

Hello. You are right about problem with escaped column names. Is there any reason this part was added to pattern: `(?i)INSERT\\s+INTO\\s+**_[^\'\"]_**+VALUES\\s*\\(")`

**Comment by enqueue** [comment]
Hi @RazieI can you please try again with the most recent driver version?

**Comment by zhicwu** [comment]
Close since the issue has been fixed already.
