### ISSUE TITLE
Batch Update Partial Failure

### ISSUE THREAD

**Issue by aimhighmp** [ClickHouse/clickhouse-jdbc#316]
Hi, we are batching up data for bulk update. But i noticed if any records failed in batch update will ignore entire batch records? Is there any plan to make change in JDBC bulk update to rejects only failed records and load all other records and return position of failed record like other Datastore supports?

Thanks

**Comment by zhicwu** [comment]
Starting from 0.3.2, you can set connection property `continueBatchOnError` to `true`, and then later check whether any of the results equals to `EXECUTION_FAILED`.
