### ISSUE TITLE
Security vulnerability in Guava version 19.0

### ISSUE THREAD

**Issue by dougbaber** [ClickHouse/clickhouse-jdbc#331]
Unbounded memory allocation in Google Guava 11.0 through 24.x before 24.1.1 allows remote attackers to conduct denial of service attacks against servers that depend on this library and deserialize attacker-provided data, because the AtomicDoubleArray class (when serialized with Java serialization) and the CompoundOrdering class (when serialized with GWT serialization) perform eager allocation without appropriate checks on what a client has sent and whether the data size is reasonable.

Suggested Remediation
Upgrade Guava To Version 24.1.1 or later

**Comment by zhicwu** [comment]
Bumped to 29.0-jre in 47747d1a60935ec5028571438bbfa31dd8498aed.
