### ISSUE TITLE
Run against new Clickhouse

### ISSUE THREAD

**Issue by simPod** [ClickHouse/clickhouse-jdbc#332]
https://github.com/yandex/clickhouse-jdbc/issues/319

> Sometimes, we need to rephrase integration tests because the CI environment uses an older ClickHouse server version. I propose to upgrade to a newer version.

Can we run against something like v19.5.2.6? I'd have sent PR but there are no new tagged images right now.

**Comment by enqueue** [comment]
Integration tests are currently run against `latest` image. Do you see any issue with that? Is there any popular production baseline version you would recommend to run test against, in addition to `latest`?

**Comment by simPod** [comment]
Yes, the version is not constrained so CI can produce different results. Eg. when `latest` gets cached.

I have created https://github.com/yandex/clickhouse-jdbc/pull/375

If desired, I can extend it so tests are run on a matrix of versions.

**Comment by enqueue** [comment]
Ah, I see. I would not know what the best version is, though.

**Comment by alex-krash** [comment]
Testing against latest version of ClickHouse means, that driver is up to date, and is ready to be used.
We would like to keep it as it is now.
In order to test that driver is backward compatible, we need to have a list of several releases for last half-year. We'll add these releases as testing profiles, which would raise up docker containers with previous versions.

**Comment by simPod** [comment]
@alex-krash but still you should run tests against concrete tag, not `latest`, hm? Eg. when running localy, `latest` is stored in cache while in CI it may already be different version.

**Comment by zhicwu** [comment]
It's been a while, but in case you still need to run tests against specific version of clickhouse, please try below:
`mvn -DclickhouseVersion=19.5.2.6 verify`
