### ISSUE TITLE
Provide a way to add interceptors

### ISSUE THREAD

**Issue by AntonKuzValid** [ClickHouse/clickhouse-jdbc#334]
I want to implement database audit and i think that the easiest way to do it is to add intersceptor to clcikhosue http client. I think it's good idea to add hooks for custom logic via HttpRequestInterceptor and HttpResponseInterceptor. I have implemented it myself and can create pull request if these functionality is needed. My example of using it - 
```
@Bean
    @ConfigurationProperties("click-house.datasource")
    fun clickHouseProperties() = ClickHouseProperties().apply {
        interceptors = listOf(HttpRequestInterceptor { req, con ->
            SecurityContextHolder.getContext().authentication?.let {
                println(
                    "${it.name} requets is ${req.requestLine}"
                )
            }
        })
    }
```

**Comment by zhicwu** [comment]
Thanks for your suggestion and pull request. Have you tried `system.query_log`? On the other hand, JDBC driver uses http basic auth by default(since `0.2.6`), so it's better to use proxy like apache/nginx/traefik/ch-proxy between JDBC clients and ClickHouse server.
