### ISSUE TITLE
RuntimeException is thrown instead of SQLException in ClickHouseConnectionImpl.initTimeZone()

### ISSUE THREAD

**Issue by fish-karamazov** [ClickHouse/clickhouse-jdbc#345]
I notice that in `ClickHouseConnectionImpl.initTimeZone()`, a `SQLException` will firstly be converted to a `RuntimeException` before it being thrown out.
```
private void initTimeZone(ClickHouseProperties properties) {
            ...
            try {
                timezone = TimeZone.getTimeZone("UTC"); // just for next query
                rs = createStatement().executeQuery("select timezone()");
                rs.next();
                String timeZoneName = rs.getString(1);
                timezone = TimeZone.getTimeZone(timeZoneName);
            } catch (SQLException e) {
                throw new RuntimeException(e);
            } 
            ...
}
```
When we use clickhouse-jdbc with [druid](https://github.com/alibaba/druid), if the clickhouse connection can not be made correctly, for example, because of the address of the clickhouse server is wrong or the clickhouse server is suddenly down, it will cause an endless loop and druid will keep trying to reconnect until being shut down or the connection is remade correctly.
From the [implementation](https://github.com/alibaba/druid/blob/master/src/main/java/com/alibaba/druid/pool/DruidDataSource.java#L2575) of druid's `CreateConnectionTask`, it seems that it treats a `RuntimeException` as an unknow fatal exception, and only thing worth to do is trying to reconnect and hope the connection can be remade. However, a `SQLException` can be handled correctly according to user set policy.
```
private void runInternal() {
    for (;;) {
        ...
        try {
            physicalConnection = createPhysicalConnection();
        } catch (OutOfMemoryError e) {
            ...
        } catch (SQLException e) {
           // handle according to user set policy
           ...
        } catch (RuntimeException e) {
            LOG.error("create connection RuntimeException", e);
            // unknow fatal exception
            setFailContinuous(true);
            continue;
        } catch (Error e) {
            ...
            break;
        }
    }
}
```
I'm wondering why we are converting `SQLException` to `RuntimeException` in `initTimeZone()` , and can we keep it as it is or make it more clear so connection pools can get a more meaningful exception and handle it correctly?

**Comment by zhicwu** [comment]
Thank you @fish-karamazov. I don't see a good reason of using `RuntimeException` instead of `SQLException`. However, the change may introduce compatibility issue in `ClickHouseConnectionImpl`, so I think we'd fix it in 0.3.0.
