### ISSUE TITLE
JDBC 4.2 Support

### ISSUE THREAD

**Issue by enqueue** [ClickHouse/clickhouse-jdbc#406]
The driver should support JDBC 4.2 API, because clients expect driver to work with API as included in Java SE 8. 

* Major changes: [JDBC 4.2](https://docs.oracle.com/javase/8/docs/technotes/guides/jdbc/jdbc_42.html)
* Spec: [JSR 221 maintenance release 2](https://jcp.org/aboutJava/communityprocess/mrel/jsr221/index2.html)

This also means dropping support for Java SE 6.

**Comment by zhicwu** [comment]
@enqueue, I hope it's not too late to get back to this. I'm working on `0.2.5` release which is just about small changes like but fixing and small enhancement. I hope it can be released in mid of Jan, and then if you have time, maybe we can make JDBC 4.2 support as part of `0.3.0` in Feb/Mar?

**Comment by zhicwu** [comment]
Will timezone issue #590 in PR #589.
