### ISSUE TITLE
ClickHouse JDBC Driver (Generate JAR File)

### ISSUE THREAD

**Issue by wirkix** [ClickHouse/clickhouse-jdbc#417]
Hello,

Can you please provide detailed instructions to compile and generate JAR file or, even better, generate and upload JAR file for download? I need to use ClickHouse JDBC Driver for a project in Pentaho Data Integration.

Thanks in advance!!

**Comment by enqueue** [comment]
Simply clone this git repository, run `mvn package` and you shall find a jar file in the `target` directory.

**Comment by alex-krash** [comment]
In next release, we'll add JAR fiile to https://github.com/ClickHouse/clickhouse-jdbc/releases

**Comment by Lavedonio** [comment]
Just a heads up, you should probably include the compiled JARs (or at least a direct link) on ClickHouse's documentation: https://clickhouse.tech/docs/en/interfaces/jdbc/
