### ISSUE TITLE
Is batch insert an atomic operation?

### ISSUE THREAD

**Issue by BernieJiangDL** [ClickHouse/clickhouse-jdbc#429]
Is each batch insert an atomic operation when we use batch insert operation in clickhouse-jdbc. For example,  we run "execute" function for a batch insert of 1000 size,  but get some exceptions when doing this. For clickhouse, do these 1000 records all fail or some success some fail?

**Comment by alex-krash** [comment]
Thanks for your question.
It has nothing with JDBC driver, but relies on ClickHouse itself.
From JDBC terms, your batch is sent to server in a single request. But on server, depending on your table engine and partitioning guaranties are varying.

**Comment by BernieJiangDL** [comment]
> Thanks for your question.
> It has nothing with JDBC driver, but relies on ClickHouse itself.
> From JDBC terms, your batch is sent to server in a single request. But on server, depending on your table engine and partitioning guaranties are varying.

Thanks for your reply. I really appreciate it. If my table engine is ReplicatedMergeTree, how does it work when those exceptions happen?

**Comment by BernieJiangDL** [comment]
> Thanks for your question.
> It has nothing with JDBC driver, but relies on ClickHouse itself.
> From JDBC terms, your batch is sent to server in a single request. But on server, depending on your table engine and partitioning guaranties are varying.

And records are inserted into a local table(ReplicatedMergeTree engine not distributed engine ) directly
