### ISSUE TITLE
Test containers for testing

### ISSUE THREAD

**Issue by strogiyotec** [ClickHouse/clickhouse-jdbc#442]
Right now README says to skip tests from compilation stage. I saw that all tests have hard coded url to clickhouse, do you plan to migrate tests to https://www.testcontainers.org/modules/databases/clickhouse/ ?

**Comment by strogiyotec** [comment]
I can contribute to it if you are interested . Please let me know

**Comment by zhicwu** [comment]
Thanks @strogiyotec. The change has been merged into `develop` branch, and it will be merged into `master` after 0.2.5 release.
