### ISSUE TITLE
 Can't get JDBC type for array<string>

### ISSUE THREAD

**Issue by BernieJiangDL** [ClickHouse/clickhouse-jdbc#449]
As the title mentioned:

I created Array<String> field type for a certain clickhouse table.

And generated the dataframe with the same format like:
`rows.add(Row(20191202L, 1234567L, Array("1","2","3","4")))`

But when I called the API of jdbc save, this exception occurs:
Caused by: java.lang.IllegalArgumentException: Can't get JDBC type for array<string>

Any solutions to this problem?

**Comment by BernieJiangDL** [comment]
I soleved it! It has nothing to do with clickhouse-jdbc. Thanks~

**Comment by javaside** [comment]
How did you solve？
