### ISSUE TITLE
assumeNotNull doens't work correctly for Date and DateTime.

### ISSUE THREAD

**Issue by CallOfCrutches** [ClickHouse/clickhouse-jdbc#451]
Hello! I found some inconsistencies with results using assumeNotNull. All nullable types, except Nullable(Date) and Nullable(DateTime), return there default values. BUT Nullable(Date) and Nullable(DateTime)return null despite this function. 

Interesting to point, that if I call result.getString(...) with assumeNotNull for Nullable(Date) and Nullable(DateTime) it returns correctly default values, BUT all other functions(getObject, getDate, getTimestamp) return null.

I assume that this happens due to this [commit](https://github.com/ClickHouse/clickhouse-jdbc/commit/93df5999ddaa46649f139e00aa34ef98115325e1). 
**P.S.** If you approve, that this behaviour should be changed, I could fix it.

**Comment by den-crane** [comment]
Probably it's better to make it configurable to don't break compatibility.

**Comment by CallOfCrutches** [comment]
Ok, I see. And set default value as it was in previous versions?

**Comment by den-crane** [comment]
Not an issue anymore. 
Deprecate special printing of zero Date/DateTime values as 0000-00-00 and 0000-00-00 00:00:00. #12442 
```
SELECT
    toDate(0),
    toDateTime(0)

┌──toDate(0)─┬───────toDateTime(0)─┐
│ 1970-01-01 │ 1970-01-01 00:00:00 │
└────────────┴─────────────────────┘
```

**Comment by CallOfCrutches** [comment]
Thank you! I'm closing the issue.
