### ISSUE TITLE
host failed to respond

### ISSUE THREAD

**Issue by huzekang** [ClickHouse/clickhouse-jdbc#452]
ru.yandex.clickhouse.except.ClickHouseUnknownException: ClickHouse exception, code: 1002, host: cdh06, port: 8123; cdh06:8123 failed to respond

**Comment by iceyung** [comment]
I have the same problem as you. At present, this error is reported by httpclient used by jdbc itself;
The critical point of survival of keep-alive, it may happen that the client thinks that the current connection is available, but the server has closed the current connection;
We temporarily disabled the long connection of jdbc httpclient, or we can also encapsulate the retry mechanism to avoid this problem:
E.g ClickHouseStatementImpl-> getInputStream:
 ```
HttpPost post = new HttpPost(uri);
 post.setEntity(requestEntity);
post.setHeader("Connection", "close");
```
Whether this problem is the problem of httpclient, hope to analyze it concretely

**Comment by huzekang** [comment]
> I have the same problem as you. At present, this error is reported by httpclient used by jdbc itself;
> The critical point of survival of keep-alive, it may happen that the client thinks that the current connection is available, but the server has closed the current connection;
> We temporarily disabled the long connection of jdbc httpclient, or we can also encapsulate the retry mechanism to avoid this problem:
> E.g ClickHouseStatementImpl-> getInputStream:
> 
> ```
> HttpPost post = new HttpPost(uri);
> post.setEntity(requestEntity);
> post.setHeader("Connection", "close");
> ```
> 
> Whether this problem is the problem of httpclient, hope to analyze it concretely

It  does not work  when i modiy the code like your recommand.

![](http://image-picgo.test.upcdn.net/img/20200610141326.png)

The same problem still appear when i batch insert Bulk data in clickhouse using jdbc.

**Comment by iceyung** [comment]
> > I have the same problem as you. At present, this error is reported by httpclient used by jdbc itself;
> > The critical point of survival of keep-alive, it may happen that the client thinks that the current connection is available, but the server has closed the current connection;
> > We temporarily disabled the long connection of jdbc httpclient, or we can also encapsulate the retry mechanism to avoid this problem:
> > E.g ClickHouseStatementImpl-> getInputStream:
> > ```
> > HttpPost post = new HttpPost(uri);
> > post.setEntity(requestEntity);
> > post.setHeader("Connection", "close");
> > ```
> > 
> > 
> > Whether this problem is the problem of httpclient, hope to analyze it concretely
> 
> It does not work when i modiy the code like your recommand.
> 
> ![](https://camo.githubusercontent.com/165779e5271fac2bf29082fa85629a1e9c209b50/687474703a2f2f696d6167652d706963676f2e746573742e757063646e2e6e65742f696d672f32303230303631303134313332362e706e67)
> 
> The same problem still appear when i batch insert Bulk data in clickhouse using jdbc.

We got this error when selecting. I don’t know much about the scenario you are using, maybe you use the packet capture tool(eg:wireshark) to see the connection status.

**Comment by iceyung** [comment]
ClickHouseStatementImpl-> sendStream  :
```
void sendStream(Writer writer, HttpEntity content) throws ClickHouseException {
        HttpEntity entity = null;
        try {

            URI uri = buildRequestUri(writer.getSql(), null, writer.getAdditionalDBParams(), writer.getRequestParams(), false);
            uri = followRedirects(uri);

            content = applyRequestBodyCompression(content);

            HttpPost httpPost = new HttpPost(uri);
            httpPost.setEntity(content);
          //add ?
            httpPost.setHeader("Connection", "close");
            HttpResponse response = client.execute(httpPost);
            entity = response.getEntity();
            checkForErrorAndThrow(entity, response);
        } catch (ClickHouseException e) {
            throw e;
        } catch (Exception e) {
            throw ClickHouseExceptionSpecifier.specify(e, properties.getHost(), properties.getPort());
        } finally {
            EntityUtils.consumeQuietly(entity);
        }
    }
```

**Comment by plinyar** [comment]
We have similar cases. Sometimes we get error ru.yandex.clickhouse.except.ClickHouseUnknownException: ClickHouse exception, code: 1002, host: ..., port: ..; host:port failed to respond. It is raised in 1-4 milliseconds after request (in our case it is batch insert into TinyLog table, see call stack below). Our cnn string has the following query param: ?socket_timeout=90000, we use connection pooling. A retry in 3-5 seconds of the same action always succeeds.


	at ru.yandex.clickhouse.except.ClickHouseExceptionSpecifier.getException(ClickHouseExceptionSpecifier.java:88)
	at ru.yandex.clickhouse.except.ClickHouseExceptionSpecifier.specify(ClickHouseExceptionSpecifier.java:55)
	at ru.yandex.clickhouse.except.ClickHouseExceptionSpecifier.specify(ClickHouseExceptionSpecifier.java:24)
	at ru.yandex.clickhouse.ClickHouseStatementImpl.sendStream(ClickHouseStatementImpl.java:800)
	at ru.yandex.clickhouse.ClickHouseStatementImpl.sendStream(ClickHouseStatementImpl.java:778)
	at ru.yandex.clickhouse.ClickHousePreparedStatementImpl.executeBatch(ClickHousePreparedStatementImpl.java:363)
	at ru.yandex.clickhouse.ClickHousePreparedStatementImpl.executeBatch(ClickHousePreparedStatementImpl.java:348)
	at io.ebean.datasource.delegate.PreparedStatementDelegator.executeBatch(PreparedStatementDelegator.java:357)
