### ISSUE TITLE
DBeaver connect Clickhouse

### ISSUE THREAD

**Issue by vkingnew** [ClickHouse/clickhouse-jdbc#461]
>Can't create driver instance
  Error creating driver 'ClickHouse' instance.
Most likely required jar files are missing.
You should configure jars in driver settings.
Reason: can't load driver class 'ru.yandex.clickhouse.ClickHouseDriver'
  Error creating driver 'ClickHouse' instance.
Most likely required jar files are missing.
You should configure jars in driver settings.
 Reason: can't load driver class 'ru.yandex.clickhouse.ClickHouseDriver'
    org/slf4j/LoggerFactory
    org/slf4j/LoggerFactory
      org.slf4j.LoggerFactory
      org.slf4j.LoggerFactory
>Run Environment
Clickhouse：20.4.4.18
DBeaver：7.1.0 community
Driver：clickhouse-jdbc-0.2.4-shaded.jar OR  clickhouse-jdbc-0.2.4.jar

Could you provide an jar with dependencies? at present it's not directly,users should compile it self.
like this :clickhouse-native-jdbc-1.7-stable-jar-with-dependencies.jar

**Comment by blinkov** [comment]
@vkingnew hm, I thought dbeaver handles installing drivers on its own, isn't it?

**Comment by vkingnew** [comment]
Yes,you're right.But I have an another Idea.
![image](https://user-images.githubusercontent.com/5238970/84911445-be507080-b0ea-11ea-8349-e829cc5afeca.png)
IF I use driver with DBeaver，I should download dependencies like the picture show.Could your provide an jar which including these dependencies .The user could use it directly and then don't need download everytime. 
I Test the current jar:clickhouse-jdbc-0.2.4-shaded.jar OR clickhouse-jdbc-0.2.4.jar ,it'll have error informations as above.

**Comment by dmolotkov** [comment]
I have the same trouble. Guys, have somebody fix it?

**Comment by thangntt** [comment]
if you connect to clickhouse-server with http port, try use: http://ui.tabix.io/. It is so simple, eazy to use.

**Comment by zhicwu** [comment]
Fixed on `develop` branch and will be merged into `master` after 0.2.5 release this weekend.
