### ISSUE TITLE
Settings toLowerCase causes issues for Turkish locale (needs Locale.ENGLISH)

### ISSUE THREAD

**Issue by den-crane** [ClickHouse/clickhouse-jdbc#463]
https://github.com/ClickHouse/clickhouse-jdbc/blob/5ff82e2f902450ad5679d8a654f7557d2220c1cd/src/main/java/ru/yandex/clickhouse/settings/ClickHouseQueryParam.java#L285-L288

>return name().toLowerCase();

        return name().toLowerCase( Locale.ENGLISH );

https://github.com/ClickHouse/ClickHouse/issues/8659

**Comment by zhicwu** [comment]
Fixed by changing to `Locale.ROOT` in 47747d1a60935ec5028571438bbfa31dd8498aed.
