### ISSUE TITLE
Support RowBinaryWithNamesAndTypes format

### ISSUE THREAD

**Issue by martsv** [ClickHouse/clickhouse-jdbc#476]
Could we add RowBinaryWithNamesAndTypes format to ClickHouseFormat enum to make it possible to select in this format with ClickHouseStatement::executeQueryClickhouseRowBinaryStream method

**Comment by zhicwu** [comment]
`ClickhouseRowBinaryInputStream` now has `getColumns` method to retrieve names and types returned from the server.
