### ISSUE TITLE
How to insert empty array

### ISSUE THREAD

**Issue by sliontc** [ClickHouse/clickhouse-jdbc#488]
When I insert empty array ( [] in Javascript ), it always throw NPE.

**Comment by den-crane** [comment]
Javascript? What do you mean? How it's related to JDBC?

**Comment by enqueue** [comment]
Please clarify or close. These common options are available to JDBC users:

Raw:
```
connection.createStatement().execute("INSERT INTO db.table (col) VALUES ([])");
```
Prepared statement using Object array directly:
```
PreparedStatement stmt = connection.prepareStatement("INSERT INTO tb.table (col) VALUES (?)");
stmt.setObject(1, new Integer[0]);
stmt.execute();
```
Prepared statement using JDBC Array mechanism (not very popular outside Oracle world, I think):
```
PreparedStatement stmt = connection.prepareStatement("INSERT INTO db.table (col) VALUES (?)");
stmt.setArray(1, connection.createArrayOf("Int32", new Integer[0]));
stmt.execute();
```
