### ISSUE TITLE
If u encounter error with msg:clickhouse cannot read all data. bytes read: xxx. bytes expected: xxx while insert data in binnary format, make sure you have handled nullable column properly

### ISSUE THREAD

**Issue by haiwenzhu** [ClickHouse/clickhouse-jdbc#491]
While insert data in binary format, nullable column must treat specialized.
More info see [Link](https://github.com/ClickHouse/clickhouse-jdbc/blob/60f4f0c7e50e172f13b0d45198f3cb01ce17279d/src/main/java/ru/yandex/clickhouse/util/ClickHouseRowBinaryStream.java#L305)

**Comment by den-crane** [comment]
RowBinary or Native?

**Comment by haiwenzhu** [comment]
RowBinary
