### ISSUE TITLE
DatabaseMetadata.getColumns returns 0 or 1 for "IS_NULLABLE", should be "YES" or "NO" instead

### ISSUE THREAD

**Issue by aaime** [ClickHouse/clickhouse-jdbc#496]
According to the official Javadocs, the IS_NULLABLE column of the resultset returned by DatabaseMetadata.getColumns should contain either "YES" or "NO":
https://docs.oracle.com/javase/8/docs/api/java/sql/DatabaseMetaData.html#getColumns-java.lang.String-java.lang.String-java.lang.String-java.lang.String-

However, the current code is returning "0" or "1" instead (from a decompiled version). Looking at the code, it seems there are references to the wrong constants from DatabaseMetadata instead (which do indeed evaluate to 0 and 1):
https://github.com/ClickHouse/clickhouse-jdbc/blob/master/src/main/java/ru/yandex/clickhouse/ClickHouseDatabaseMetadata.java#L855

**Comment by aaime** [comment]
Never mind, looked at the wrong column (NULLABLE vs IS_NULLABLE)

**Comment by zhicwu** [comment]
Close as this seems not an issue.
