### ISSUE TITLE
DateTime64 as ClickHouseDataType

### ISSUE THREAD

**Issue by trolley813** [ClickHouse/clickhouse-jdbc#517]
Not long ago, CH introduced new `DateTime64` type. Despite this, it's not mentioned in `ClickHouseDataType.java`, so the corresponding `java.sql.Types` instance returned for `DateTime64` is a very generic `OTHER`.

It probably should return a more suitable type (e.g. `TIMESTAMP` or even `BIGINT`, since technically it's a 64-bit integer), since the current setting has some problems with JDBC apps that don't support generic annotations like `OTHER`. Most notably, Apache Spark cannot write into a `DateTime64` column using the JDBC layer (and it probably could, since integers can be safely written into a `DateTime64` column).

**Comment by trolley813** [comment]
Created PR #520 for fixing this.

**Comment by zhicwu** [comment]
Thanks @trolley813. Do you have time to enhance the PR to support sub-second precision as well?

**Comment by trolley813** [comment]
@zhicwu Yes, I do. But unfortunately I don't know yet what I have to do. Will try to do it nevertheless.
