### ISSUE TITLE
clickhouse-go compatible DSN

### ISSUE THREAD

**Issue by yuzhichang** [ClickHouse/clickhouse-jdbc#524]
[clickhouse-go DSN](https://github.com/ClickHouse/clickhouse-go#dsn):
- alt_hosts - comma separated list of single address host for load-balancing
- connection_open_strategy - random/in_order (default random).

These parameters enables load-balance and fault- toleration.

**Comment by zhicwu** [comment]
In general all clients should use similar settings as in official `clickhouse-client`, and behave in the same way. It's a good suggestion and we'll revisit this in 0.4.

**Comment by zhicwu** [comment]
Not going to use the exact same DSN, because Java client and JDBC driver support multiple formats(TSV and RowBinary) and protocols(http, https, grpc, tcp and tcp secure) as of 0.3.2. It's more natural to use nested URLs as mentioned in #894.
