### ISSUE TITLE
 there is no writeUUIDArray method?

### ISSUE THREAD

**Issue by shawel** [ClickHouse/clickhouse-jdbc#527]
I have a column Array(UUID) but i am not sure how to write it for rowBinary inserts  - thanks

**Comment by enqueue** [comment]
Sorry, I do not know about how this works in the RowBinary API, have you tried sending the String representation instead?

With JDBC API, you can simply do it like this:
```
PreparedStatement statement = connection.prepareStatement(
    "INSERT INTO test.uuid_array (foo) VALUES (?)");
statement.setArray(1, connection.createArrayOf("UUID", myUUIDArray));
statement.executeUpdate();
```
or shorter
```
statement.setObject(1, myUUIDArray});
```

**Comment by shawel** [comment]
@enqueue thanks. 
Since I am using  RowBinary API writeUUIDArray is missing but there is writeUUID so a work around is to do something like

in scala 
values = is UUID arrays 
```
values = is UUID arrays 
stream.writeUnsignedLeb128(values.length)
values.foreach({
            uuid =>
              stream.writeUUID(uuid)
          })
```
