### ISSUE TITLE
Not Found Can't open 'https://repo1.maven.org/maven2/ru/yandex/clickhouse/clickhouse-jdbc/${revision}/clickhouse-jdbc-${revision}.jar': Not Found

### ISSUE THREAD

**Issue by denisgolius** [ClickHouse/clickhouse-jdbc#556]
Does it problem with my dbeaver version?
![Screenshot_1](https://user-images.githubusercontent.com/5650611/106431839-1ff0ff80-646e-11eb-9def-b4d926aa6f7f.png)

**Comment by zhicwu** [comment]
Sorry it's caused by [the updated pom file](../blob/v0.2.5/pom.xml#L7). Can you use https://repo1.maven.org/maven2/ru/yandex/clickhouse/clickhouse-jdbc/0.2.5/clickhouse-jdbc-0.2.5-shaded.jar instead for now? I'll fix this in next release.

**Comment by denisgolius** [comment]
> Sorry it's caused by [the updated pom file](../blob/v0.2.5/pom.xml#L7). Can you use https://repo1.maven.org/maven2/ru/yandex/clickhouse/clickhouse-jdbc/0.2.5/clickhouse-jdbc-0.2.5-shaded.jar instead for now? I'll fix this in next release.

Can't understand how to do this... Copying jar file into plugins path don't help...( meh

**Comment by denisgolius** [comment]
Solved. Thank you for help :D
