### ISSUE TITLE
как удалить таблицу?

### ISSUE THREAD

**Issue by NikolayPraydkin** [ClickHouse/clickhouse-jdbc#565]
Хотел создать таблицу
CREATE TABLE test(
    arar Array(UUID),
    id UInt8
    )ENGINE = MergeTree()
ORDER BY id;
Но возникли проблемы с UUID, записать значение возможно, но прочитать не получалось
Создал другую 
CREATE TABLE test(
    arar Array(String),
    id UInt8
    )ENGINE = MergeTree()
ORDER BY id;

вставил одну строку

потом вот таким запросом всё сломалось, теперь не получить значение не удалить таблицу не получается(Read timeout)

alter table test update arar = (select arrayPushBack((SELECT arar from test where id = 3), '5ff22319-793d-4e6c-bdc1-916095a5a496')) where id = 3;

Могу я удалить её корректно просто удалив папку по пути var/lib/clickhouse/data ?

**Comment by zhicwu** [comment]
Thank @nikitamikhaylov for reporting the two issues. I created #569 which is English version of the first issue, while for the second one, I'd suggest you to create a separate issue in [ClickHouse repo](https://github.com/ClickHouse/ClickHouse/issues).

**Comment by nikitamikhaylov** [comment]
Thanks to @NikolayPraydkin , not to me :)

**Comment by zhicwu** [comment]
> Thanks to @NikolayPraydkin , not to me :)

LOL, when you drove 8 hours a day, you started to believe names starting with N are all the same ;) If you have time, you may want to check the second issue - I was able to reproduce that on 20.8.

**Comment by nikitamikhaylov** [comment]
@NikolayPraydkin  Better to create an issue with reproduction in ClickHouse repo. 

> Могу я удалить её корректно просто удалив папку по пути var/lib/clickhouse/data ?

Yes, since you created simple MergeTree instead of ReplicatedMergeTree all you need to do is to stop server and delete data and metadata of this table (not whole data of your server).

Data path for your table is `var/lib/clickhouse/data/default/test` and metadata path is `var/lib/clickhouse/metadata/default/test`

**Comment by NikolayPraydkin** [comment]
> @NikolayPraydkin Better to create an issue with reproduction in ClickHouse repo.
> 
> > Могу я удалить её корректно просто удалив папку по пути var/lib/clickhouse/data ?
> 
> Yes, since you created simple MergeTree instead of ReplicatedMergeTree all you need to do is to stop server and delete data and metadata of this table (not whole data of your server).
> 
> Data path for your table is `var/lib/clickhouse/data/default/test` and metadata path is `var/lib/clickhouse/metadata/default/test`

i deleted folder from var/lib/clickhouse/data/ and saw what it linked by real data in folder /var/lib/clickhouse/store/ and deleted too
