### ISSUE TITLE
Code: 26, e.displayText() = DB::ParsingException: Cannot parse quoted string: expected opening quote ''', got '\' (version 21.2.2.8 (official build))

### ISSUE THREAD

**Issue by NikolayPraydkin** [ClickHouse/clickhouse-jdbc#566]
I create table with Array(String) type.

Single prepareStastement like this   executing fine.
                
List<String> gg = new ArrayList<>();
        gg.add("ssasda");
        gg.add("ssasdsdas");
        gg.add("sdfsdthhtrh");

String s = ClickHouseArrayUtil.toString(gg, TimeZone.getDefault(), TimeZone.getDefault());

 try (ClickHouseConnection connection = dataSource.getConnection()) {
            PreparedStatement prepare = connection.prepareStatement("insert into test (arrTest) values(?)");
            prepare.setObject(1, s); (or setString)
            prepare.execute();
}

But  batchPrepareStatement  throwing exeprion .
try (ClickHouseConnection connection = dataSource.getConnection()) {
             PreparedStatement prepare = connection.prepareStatement("insert into test (arrTest) values(?)");
            prepare.setString(1, s);
            prepare.addBatch();     
            prepare.executeBatch();
        }

I use spring jdbc NamedParameterJdbcOperations, behaviour identical.. thowing exeption.

**Comment by enqueue** [comment]
You could simply let the driver take care of the serialization by using JDBC API. Please see the following examples:
```
String[] myStrings = new String[] {"foo", "bar"};
PreparedStatement st = connection.prepareStatement(
    "INSERT INTO test.test (arrTest) VALUES (?)");
```
Option 1 - Use SQL Array:
```
st.setArray(1, connection.createArrayOf(ClickHouseDataType.String.name(), myStrings));
```
Option 2 - Use list directly:
```
st.setObject(1, Arrays.asList(myStrings));
```
Option 3 - Use Array directly:
```
st.setObject(1, myStrings);
```

**Comment by NikolayPraydkin** [comment]
I solved my problem like this

String sql= "insert into test(test) values (:test)";
List<Map<String, Object>> batch = new ArrayList<>();
 List<String> list= new ArrayList<>();
list.add("foo");
list.add("bar");
Map<String, Object> map = new HashMap<>();
map.put("test", new ClickHouseArray(ClickHouseDataType.String,list.toArray()).getArray());
batch.add(map);
SqlParameterSource[] batch = SqlParameterSourceUtils.createBatch(batch.toArray());
namedParameterJdbcOperations.batchUpdate(sql, batch);
this sample uses spring jdbc

**Comment by zhicwu** [comment]
@NikolayPraydkin, could you close the issue if it's been resolved?

@enqueue, is [this](https://github.com/ClickHouse/clickhouse-jdbc/blob/v0.2.6/src/main/java/ru/yandex/clickhouse/ClickHousePreparedStatementParameter.java#L52) a defect? I think we should use `ClickHouseSqlUtils.escape(stringValue)` or so to fix that.

**Comment by newfield** [comment]
I solved my problem like this:  use spark insert （scala）
use clickhouse-jdbc-0.3.2 
my ] code：
val data_map=fieldVal.asInstanceOf[scala.collection.immutable.Map[_,_]].toMap
preparedStatement.setObject(fieldIdx + 1, scala.collection.JavaConversions.mapAsJavaMap(data_map))
