### ISSUE TITLE
error while read compressed stream Magic is not correct: 10

### ISSUE THREAD

**Issue by victortony** [ClickHouse/clickhouse-jdbc#591]
when i use 
` ClickHouseStatement sth = (ClickHouseStatement) connection.createStatement();
        sth.write()
            .table("table1")
            .option("format_csv_delimiter", "\t")
            .data(new File("/path/to/testfile.txt"), ClickHouseFormat.TabSeparatedRaw, ClickHouseCompression.none)
            .send();`

the exception throws which says that error while read compressed stream Magic is not correct: 10
the content of testfile.txt is 

122334	sjjabbd0999999	20210309
122345	sjjabbd0999988	20210309

Will you please help me to check what problem with the my code, thank you very much.

**Comment by den-crane** [comment]
What CH version do you use? Try without `ClickHouseCompression.none`

**Comment by victortony** [comment]
> What CH version do you use? Try without `ClickHouseCompression.none`

Hi, I use 19.16.3.6. 
The problem have been solved, when i put the "?compress=0" in many jdbc url;

**Comment by den-crane** [comment]
But compress is disabled by default?

So the issue reproduce with compress=1 ?

**Comment by victortony** [comment]
No，compress is enabled by default, so i have to put "compress = 0" in my jdbc url, or it throws exception.

**Comment by zhicwu** [comment]
@victortony, you can use latest code on `develop` branch or wait for `0.3.0` release. It should work with both new version and old version like `19.14` and `19.16`. Moreover, I'd suggest you to upgrade to an up-to-date LTS like `20.8` or `21.3` as the old versions are no longer supported.

**Comment by victortony** [comment]
thank you very much.

**Comment by victortony** [comment]
> @victortony, you can use latest code on `develop` branch or wait for `0.3.0` release. It should work with both new version and old version like `19.14` and `19.16`. Moreover, I'd suggest you to upgrade to an up-to-date LTS like `20.8` or `21.3` as the old versions are no longer supported.

thank you very much.
