### ISSUE TITLE
 Connection reset by peer, while reading from socket

### ISSUE THREAD

**Issue by victortony** [ClickHouse/clickhouse-jdbc#593]
I have a clickhouse cluster which contains two node. One node of the cluster prints error logs every 5 seconds. But the databases works right, when querying, inserting data. The error log list below.
Would you please help me find what happens.
So many error logs is from which service. And the ip "10.115.xxx.x:62543" is not my network segment, what service is it?

`
**/var/log/clickhouse-server/clickhouse-server.log:**

2021.03.09 18:00:38.897646 [ 50 ] {} TCPHandlerFactory: TCP Request. Address: 10.115.xxx.x:62543
2021.03.09 18:00:38.897790 [ 50 ] {} ServerErrorHandler: Poco::Exception. Code: 1000, e.code() = 107, e.displayText() = Net Exception: Socket is not connected (version 19.16.3.6
2021.03.09 18:00:39.014314 [ 49 ] {} TCPHandlerFactory: TCP Request. Address: 10.115.xxx.x:20469
2021.03.09 18:00:39.015025 [ 49 ] {} ServerErrorHandler: Code: 210, e.displayText() = DB::NetException: Connection reset by peer, while reading from socket (10.115.xxx.x:20469), Stack trace:

0x34fcf10 StackTrace::StackTrace() /usr/bin/clickhouse
0x350715f DB::Exception::Exception(std::string const&, int) /usr/bin/clickhouse
0x33f2658 ? /usr/bin/clickhouse
0x357c52c DB::TCPHandler::runImpl() /usr/bin/clickhouse
0x357cb6c DB::TCPHandler::run() /usr/bin/clickhouse
0x6d4bb6f Poco::Net::TCPServerConnection::start() /usr/bin/clickhouse
0x6d4c265 Poco::Net::TCPServerDispatcher::run() /usr/bin/clickhouse
0x71d1771 Poco::PooledThread::run() /usr/bin/clickhouse
0x71cd4f8 Poco::ThreadImpl::runnableEntry(void*) /usr/bin/clickhouse
0x78ac0ff ? /usr/bin/clickhouse
0x7fac442b1dc5 start_thread /usr/lib64/libpthread-2.17.so
0x7fac43ddc73d __clone /usr/lib64/libc-2.17.so
(version 19.16.3.6)

`

**Comment by victortony** [comment]
I have a clickhouse cluster which contains two node. One node of the cluster prints error logs every 5 seconds. But the databases works right, when querying, inserting data. The error log list below.
Would you please help me find what happens.
So many error logs is from which service. And the ip "10.115.xxx.x:62543" is not my network segment, what  service is it?


2021.03.09 18:00:38.897646 [ 50 ] {} TCPHandlerFactory: TCP Request. Address: 10.115.xxx.x:62543
2021.03.09 18:00:38.897790 [ 50 ] {} ServerErrorHandler: Poco::Exception. Code: 1000, e.code() = 107, e.displayText() = Net Exception: Socket is not connected (version 19.16.3.6
2021.03.09 18:00:39.014314 [ 49 ] {} TCPHandlerFactory: TCP Request. Address: 10.115.xxx.x:20469
2021.03.09 18:00:39.015025 [ 49 ] {} ServerErrorHandler: Code: 210, e.displayText() = DB::NetException: Connection reset by peer, while reading from socket (10.115.xxx.x:20469), Stack trace:

0x34fcf10 StackTrace::StackTrace() /usr/bin/clickhouse
0x350715f DB::Exception::Exception(std::string const&, int) /usr/bin/clickhouse
0x33f2658 ? /usr/bin/clickhouse
0x357c52c DB::TCPHandler::runImpl() /usr/bin/clickhouse
0x357cb6c DB::TCPHandler::run() /usr/bin/clickhouse
0x6d4bb6f Poco::Net::TCPServerConnection::start() /usr/bin/clickhouse
0x6d4c265 Poco::Net::TCPServerDispatcher::run() /usr/bin/clickhouse
0x71d1771 Poco::PooledThread::run() /usr/bin/clickhouse
0x71cd4f8 Poco::ThreadImpl::runnableEntry(void*) /usr/bin/clickhouse
0x78ac0ff ? /usr/bin/clickhouse
0x7fac442b1dc5 start_thread /usr/lib64/libpthread-2.17.so
0x7fac43ddc73d __clone /usr/lib64/libc-2.17.so
(version 19.16.3.6)

**Comment by den-crane** [comment]
It's not the real error.
It's looks like a loadbalancer probing / checking that Clickhouse is alive.

What is the behind this 10.115.xxx.x address?

The issue is unrelated to clickhouse-jdbc.
