### ISSUE TITLE
Connection Pool in clickhouse-jdbc

### ISSUE THREAD

**Issue by deepprakash345** [ClickHouse/clickhouse-jdbc#594]
Hi, 
I am trying to figure out the working of clickhouse-jdbc client. Is there any default concept of connection pooling. I can seethe options of 
    clickHouseProperties.setMaxTotal
    clickHouseProperties.setDefaultMaxPerRoute
but when i am trying to get connection from my balanced datasource object i am getting new connection object everytime.

This is my code which i am using for this. ideally the result of a.size should be equal to maxTotal. but i am geeting a.size=i everytime.

@Repository
public class ClickhouseRepository {

  @PostConstruct
  public void checkConnection() throws SQLException {
    ClickHouseProperties clickHouseProperties = new ClickHouseProperties();
    clickHouseProperties.setMaxTotal(100);
    clickHouseProperties.setDefaultMaxPerRoute(100);
    clickHouseProperties.setConnectionTimeout(2000);
    clickHouseProperties.setSocketTimeout(2000);

    clickHouseProperties.setDatabase("ONTIME");
    BalancedClickhouseDataSource dataSource = new BalancedClickhouseDataSource("jdbc:clickhouse://localhost:8124,localhost:8125,localhost:8126/ONTIME"
        ,clickHouseProperties);
    try {
      HashMap<Integer,Integer> a=new HashMap<>();
      int i=300;
      while(i>0) {
        System.out.println(i);
        ClickHouseConnection clickHouseConnection = dataSource.getConnection();
        if(a.containsKey(clickHouseConnection.hashCode())){
          int b=a.get(clickHouseConnection.hashCode());
          a.put(clickHouseConnection.hashCode(),b+1);
        }else{
          a.put(clickHouseConnection.hashCode(),1);
        }
        String query = "select * from OntimeReplicatioN limit 10";
        Statement statement = clickHouseConnection.createStatement();
        ResultSet rs = statement.executeQuery(query);

        System.out.println("\n\n\n\n\nconnection established successfully\n\n\n\n\n");
        //System.out.println("\nResultSet:-" + rs);
        i--;
      }
      System.out.println(a.size());
    }catch (Exception e){
      System.out.println("\n\n\n\n\nexception thrown\n\n\n\n\n"+e);
    }
  }

}

**Comment by zhicwu** [comment]
@deepprakash345, thanks for sharing your findings. At this point, the JDBC driver is built on top of Apache Http Client, which is used to talk to ClickHouse server via http. The Connection object you saw is just a wrapper of `CloseableHttpClient`, which is created by [ClickHouseHttpClientBuilder](https://github.com/ClickHouse/clickhouse-jdbc/blob/v0.2.6/src/main/java/ru/yandex/clickhouse/util/ClickHouseHttpClientBuilder.java#L70). The two options you set are for configuring [PoolingHttpClientConnectionManager](https://github.com/ClickHouse/clickhouse-jdbc/blob/v0.2.6/src/main/java/ru/yandex/clickhouse/util/ClickHouseHttpClientBuilder.java#L144).

However, using pooled HttpClient has some drawback especially when you want to implement load balancing and fail-over. In that case, you may want to add a proxy in the middle as a workaround. Other than that, you may wait until version `0.4.0` or so for the ability of client-side load balancing(or at least an option to configure whether pooled http client should be used or not).
