### ISSUE TITLE
Question of Bitmap querying optimization

### ISSUE THREAD

**Issue by victortony** [ClickHouse/clickhouse-jdbc#595]
Hi, I have two query below:
The first one is :
`select bitmapAndCardinality ( \
(SELECT uv FROM table1 WHERE (label_name = 'sex') AND (label_value = 2)) , \
(SELECT uv FROM table1 WHERE (label_name = 'age') AND (label_value = 1)) \
)`

The second one is:
`select id, bitmapAndCardinality(b1, b2) from
( SELECT 1 as id, uv as b1 FROM table1 WHERE (label_name = 'sex') AND (label_value = 2) ) a
inner join 
(SELECT 1 as id, uv as b2 FROM table1 WHERE (label_name = 'age') AND (label_value = 1) ) b
on a.id = b.id`

Could you please tell me why the 1th query is slower than the 2th query. When the data become more and more, the gap is bigger. Normally, for the same situation: 1th query cost 5 seconds, 2th query cost 0.012 seconds.

**Comment by zhicwu** [comment]
Close as this is irrelevant to the JDBC driver.

I'm no expert. You may try `explain` and see metrics in `system.query_log` to understand more. Also it's unclear which exact version of ClickHouse you're using. To my knowledge, `19.16` has problem supporting 64-bit bitmap although this has nothing to do with your question.

I think you have better chance to get support if you submit the question in Slack/Telegram or [ClickHouse repository](https://github.com/ClickHouse/ClickHouse/issues).

**Comment by victortony** [comment]
> Close as this is irrelevant to the JDBC driver.
> 
> I'm no expert. You may try `explain` and see metrics in `system.query_log` to understand more. Also it's unclear which exact version of ClickHouse you're using. To my knowledge, `19.16` has problem supporting 64-bit bitmap although this has nothing to do with your question.
> 
> I think you have better chance to get support if you submit the question in Slack/Telegram or [ClickHouse repository](https://github.com/ClickHouse/ClickHouse/issues).

Thank you @zhicwu. Would you please to share with me what problem supporting 64-bit bitmap in 19.16?
