### ISSUE TITLE
Extract Clickhouse cityhash into separate module

### ISSUE THREAD

**Issue by smagellan** [ClickHouse/clickhouse-jdbc#600]
Hello. 
Do you have any objections against extraction ru.yandex.clickhouse.util.ClickHouseCityHash into separate maven module/artifact? I will create PR if this is acceptable.
P.S. I need this to implement vertx async binary driver. This in turn may fix https://github.com/ClickHouse/clickhouse-jdbc/issues/477

**Comment by smagellan** [comment]
ping @zhicwu

**Comment by zhicwu** [comment]
Cool. ru.yandex.clickhouse.util.ClickHouseCityHash stays in `clickhouse-jdbc` until 0.4.0. It will be copied to `clickhouse-client` under new package name `tech.clickhouse`(instead of `ru.yandex.clickhouse`) in 0.3.1.

I'll come up with a new PR to address this in the coming days :)

**Comment by smagellan** [comment]
Great, thank you. Anemic (without other external dependencies) artifact is a good solution here.

**Comment by zhicwu** [comment]
Link to #610.

**Comment by zhicwu** [comment]
It's now `com.clickhouse.client.data.ClickHouseCityHash` in `clickhouse-client` module.
