### ISSUE TITLE
Could not find com.github.RoaringBitmap:RoaringBitmap:0.9.9

### ISSUE THREAD

**Issue by sneakythr0ws** [ClickHouse/clickhouse-jdbc#603]
Gradle
`implementation 'ru.yandex.clickhouse:clickhouse-jdbc:0.3.0'`

```
A problem occurred configuring root project 'project'.
> Could not resolve all files for configuration ':runtimeClasspath'.
   > Could not find com.github.RoaringBitmap:RoaringBitmap:0.9.9.
     Searched in the following locations:
       - https://repo.maven.apache.org/maven2/com/github/RoaringBitmap/RoaringBitmap/0.9.9/RoaringBitmap-0.9.9.pom
     If the artifact you are trying to retrieve can be found in the repository but without metadata in 'Maven POM' format, you need to adjust the 'metadataSources { ... }' of the repository declaration.
     Required by:
         project : > ru.yandex.clickhouse:clickhouse-jdbc:0.3.0

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html

```

**Comment by zhicwu** [comment]
Could you add repository https://jitpack.io? They didn't push latest artifact to maven central. Alternatively, you can use shaded jar and exclude all its dependencies.

**Comment by sneakythr0ws** [comment]
I added an exclusion(I don't use bitmaps in jdbc). But I don't think it is good idea to publish artifact to storage without dependency.

**Comment by zhicwu** [comment]
Right. Maybe we should make RoaringBitmap dependency as optional("provided" in maven).

**Comment by zhicwu** [comment]
RoaringBitmap is now an optional dependency. It's downgraded to 0.9.3 so that we can use maven central in order to compile, and it's no longer included in the shaded jar.
