### ISSUE TITLE
support createDatabaseIfNotExist parameter settings

### ISSUE THREAD

**Issue by melin** [ClickHouse/clickhouse-jdbc#605]
mysql createDatabaseIfNotExist parameters，support createDatabaseIfNotExist parameter settings？

**Comment by zhicwu** [comment]
This could be convenient for DBA/DataOps. I'm going to add support for multi-statement in 0.3.1, which allows you to pass a SQL script with statement like `create database if not exists my_db;` in front of others. Will the feature solve your problem? If not, do you mind to create a PR?

**Comment by melin** [comment]
> This could be convenient for DBA/DataOps. I'm going to add support for multi-statement in 0.3.1, which allows you to pass a SQL script with statement like `create database if not exists my_db;` in front of others. Will the feature solve your problem? If not, do you mind to create a PR?

Pass a SQL script，Can solve my problem

**Comment by zhicwu** [comment]
Starting from 0.3.1, you can execute multi-statement SQL at a time. For example:
```java
try (Statement stmt = connection.createStatement()) {
    stmt.execute("create database if not exists my_db;"
        + "create table if not exists ...";
        + "insert into...");
    ...
}
```

Session will be used automatically and only the last result will be returned for now.
