### ISSUE TITLE
ClickHouseValueFormatter.formatTime can't formar timestamp correctly

### ISSUE THREAD

**Issue by luoyuxia** [ClickHouse/clickhouse-jdbc#613]
https://github.com/ClickHouse/clickhouse-jdbc/blob/094ed0b9d2dd8a18ae0c7b3f8f22c35e595822a6/clickhouse-jdbc/src/main/java/ru/yandex/clickhouse/util/ClickHouseValueFormatter.java#L133

I wonder why use `time.getNanos() % 1000000 > 0`,  for example when the timestamp is 2021-11-12 12:34:45.349, and the timestamp's Nanos is 349 * 1000000, then `time.getNanos() % 1000000` will be 0, and will skip the following code 
https://github.com/ClickHouse/clickhouse-jdbc/blob/094ed0b9d2dd8a18ae0c7b3f8f22c35e595822a6/clickhouse-jdbc/src/main/java/ru/yandex/clickhouse/util/ClickHouseValueFormatter.java#L134
 then the `formatted` will not be '2021-11-12 12:34:45.349'.

I am not sure it's exactly what it is supposed to do.

**Comment by zhicwu** [comment]
The driver has no idea what the column type is, so it took a wild guess...

Now starting from 0.3.2, you can either pass string with nanoseconds, or use [input function](../blob/eb8b0878d33853ecfcfc4b81f7d0f618900bbb7b/clickhouse-jdbc/src/test/java/com/clickhouse/jdbc/ClickHousePreparedStatementTest.java#L307-L324) and/or [named parameter](../blob/eb8b0878d33853ecfcfc4b81f7d0f618900bbb7b/clickhouse-jdbc/src/test/java/com/clickhouse/jdbc/ClickHousePreparedStatementTest.java#L405-L438) for type inferring.
