### ISSUE TITLE
ClickHousePreparedStatementImpl add setMap method

### ISSUE THREAD

**Issue by ruanwenjun** [ClickHouse/clickhouse-jdbc#622]
If is necessary to add `setMap` method in statement, although we can directly use `setObject`

**Comment by zhicwu** [comment]
I agree that `setMap` is more explicit. Actually it's been added in the upcoming `clickhouse-client` for ease of use. `clickhouse-jdbc` on the other hand has to obey JDBC specification, so you have to use `setObject` for now.

**Comment by ruanwenjun** [comment]
Ok
