### ISSUE TITLE
SetDate can not work

### ISSUE THREAD

**Issue by ruanwenjun** [ClickHouse/clickhouse-jdbc#624]
When I use `setDate` method in `ClickHousePreparedStatementImpl` like below
```java
statement_1.setDate(19, new Date(System.currentTimeMillis()));
```
It throw a exception and tell me `garbage after DateTime('America/Phoenix'): "08<TAB>9169210"`

and I change to `statement_1.setString(19, "1970-01-01 16:00:00");` it can work success

**Comment by zhicwu** [comment]
Are you using ClickHouse 21.3?

**Comment by ruanwenjun** [comment]
> Are you using ClickHouse 21.3?

The version of clickhouse is 21.2.2.8 and clickhouse-jdbc is 0.3.0.

**Comment by zhicwu** [comment]
> The version of clickhouse is 21.2.2.8 and clickhouse-jdbc is 0.3.0.

Is it related to batch insertion? I'll write a test case to see if I can reproduce after lunch.

**Comment by ruanwenjun** [comment]
> > The version of clickhouse is 21.2.2.8 and clickhouse-jdbc is 0.3.0.
> 
> Is it related to batch insertion? I'll write a test case to see if I can reproduce after lunch.

Yeah, it can work well when I call `statement_1.execute()`, but has a problem in batch. And in batch mode， there also seems to be a problem with using setObject to insert Map column, I am not sure whether these two are caused by the same  cause.

**Comment by zhicwu** [comment]
Thanks for the extra information. I thought the driver only has issue with 21.3 but looks like it has problem with 21.2 too. I believe there's issue introduced on server side causing the problem, but I'll fix this by replacing text-based format to binary.

**Comment by zhicwu** [comment]
Now the new driver uses RowBinary format instead of TabSeparated so it should work. I don't have a full example to verify but in general it's better to use `java.time.LocalDate` instead of `java.sql.Date`, and use `PreparedStatement.setObject` to set parameter.
