### ISSUE TITLE
How to drop cache for protobuf insert 

### ISSUE THREAD

**Issue by Hugues514** [ClickHouse/clickhouse-jdbc#625]
I am inserting data in ClickHouse using jdbc with protobuf format. 
As I am still doing modification on the protobuf file and the structure ot my table, I happen to have errors because of the cache for the protobuf file (the insert is still using the old version of the file). I was not able to find any system command (SYSTEM DROP xxx CACHE) to drop this cache. 
The only workaround found is to restart clickhouse, (which is fine on a single node for dev...)
Any other idea ?
Thanks in advance

**Comment by zhicwu** [comment]
This seems not related to JDBC driver. Perhaps you can consult in Telegram/Slack/server repository? Since you're using protobuf, have you considered to use [gRPC](https://github.com/ClickHouse/ClickHouse/blob/master/src/Server/grpc_protos/clickhouse_grpc.proto) directly?

**Comment by den-crane** [comment]
related https://github.com/ClickHouse/ClickHouse/issues/31964
