### ISSUE TITLE
Connection Setting

### ISSUE THREAD

**Issue by ruanwenjun** [ClickHouse/clickhouse-jdbc#627]
Would you consider providing some configuration instructions about the connection setting in clickhouse-jdbc client. I found some in `ClickHouseConnectionSettings`. I think sometimes we need to use properties to init the connetion,  it would be great if there is a document to introduce this part.

**Comment by zhicwu** [comment]
Thanks for the suggestion. I think I can add some more examples in README to make it easier.

**Comment by ruanwenjun** [comment]
> Thanks for the suggestion. I think I can add some more examples in README to make it easier.

Cool

**Comment by zhicwu** [comment]
I only added an example in README. Starting from 0.3.2, it's better to use `clickhouse-client` instead of JDBC or extended API, and the usage will be very different. Below is an example showing what it looks like in future releases:
```java
ClickHouseNode target = ClickHouseNode.builder()
    .withHost("localhost")
    .withPort(8123)
    .withTags("dc1", "rack1", "server1")
    .build();

try (ClickHouseClient client = ClickHouseClient.builder()
    .addOption(ClickHouseClientOption.CLIENT_NAME, "Agent #1")
    .withCredentails(ClickHouseCredentials.fromUserAndPassword("default", ""))
    .build()) {
    Future<ClickHouseResponse> asyncResp = client.connect(target)
        .use("my_db")
        .option(ClickHouseHttpRequestOption.SESSION_ID, "new-session-id")
        .set("max_execution_time", 120)
        .sql("select * from my_table")
        .execute();
    ...
}
```
