### ISSUE TITLE
support allow_experimental_map_type=1

### ISSUE THREAD

**Issue by theonedemon** [ClickHouse/clickhouse-jdbc#631]
driver not support custom option  https://clickhouse.tech/docs/ru/sql-reference/data-types/map/
```
allow_experimental_map_type=1
```

**Comment by zhicwu** [comment]
Added the parameter in `ClickHouseQueryParam`. Since multi-statement SQL is now supported, you can alternatively execute below SQL in one run:
```sql
set allow_experimental_map_type=1;

create table if not exists system.test_map_support(
    m Map(UInt8, String)
) engine=Memory
```
