### ISSUE TITLE
not support  HikariDataSource connect pool

### ISSUE THREAD

**Issue by devon-ye** [ClickHouse/clickhouse-jdbc#639]

**Comment by zhicwu** [comment]
Could you elaborate? [This](https://github.com/ClickHouse/clickhouse-jdbc-bridge/blob/master/misc/quick-start/jdbc-bridge/config/datasources/ch-server.json) worked for me.

**Comment by devon-ye** [comment]
Sorry, this issue double Datasource configuration error. I had to solute it
