### ISSUE TITLE
Missing maven artifact

### ISSUE THREAD

**Issue by maxp** [ClickHouse/clickhouse-jdbc#642]
Maven reports an error when trying to use clickhouse-jdbc 0.3.0.

Error building classpath. Could not find artifact com.github.RoaringBitmap:RoaringBitmap:jar:0.9.9 in central (https://repo1.maven.org/maven2/)

Previous version 0.2.6 works well.

**Comment by zhicwu** [comment]
This has been fixed. You may use code on `develop` branch or wait for a few more hours to use 0.3.1.
