### ISSUE TITLE
Data type DateTime(3), ResultSetMetaData.getColumnTypeName return String

### ISSUE THREAD

**Issue by melin** [ClickHouse/clickhouse-jdbc#647]
![image](https://user-images.githubusercontent.com/1145830/116402125-9bd8c900-a85e-11eb-80fc-b6914d69ad56.png)

**Comment by zhicwu** [comment]
Which version of JDBC driver are you using? I wasn't able to reproduce the issue using 0.3.1 on ClickHouse 21.3.

**Comment by melin** [comment]
> Which version of JDBC driver are you using? I wasn't able to reproduce the issue using 0.3.1 on ClickHouse 21.3.

v0.2.6

**Comment by zhicwu** [comment]
> v0.2.6

`DateTime64` was added in 0.3.0. It's treated as String before that. If you think the issue is critical, please upgrade JDBC driver to the latest version.
