### ISSUE TITLE
After update to 0.3.1 datasource ignores database from url

### ISSUE THREAD

**Issue by sneakythr0ws** [ClickHouse/clickhouse-jdbc#648]
I use `new ClickHouseDataSource(url, clickHouseProperties());` for datasource creation
After update to 0.3.1 it ignores database from url and uses `default`
Downgrading to 0.3.0 fixes the problem

**Comment by zhicwu** [comment]
Thanks for the reporting issue and this has been fixed on develop branch.

**Comment by sneakythr0ws** [comment]
Is it fixed in v0.3.1-patch?

**Comment by zhicwu** [comment]
> @zhicwu Is it fixed in v0.3.1-patch?

Yes.
