### ISSUE TITLE
Fail to batch insert bitmap

### ISSUE THREAD

**Issue by Nicemo** [ClickHouse/clickhouse-jdbc#670]
My ck-jdbc version is 0.3.1 
<dependency>
      <groupId>ru.yandex.clickhouse</groupId>
      <artifactId>clickhouse-jdbc</artifactId>
      <version>0.3.1</version>
 </dependency>
When I insert bitmap one by one, it success.

But i use executeBatach() method to insert bitmap, the bitmapCardinality(usr_bit) return 0 incontradicts with the former result.

```scala
val initSQL =
      """
        |INSERT INTO xxx.xxxxxxx
        |(user_bit, tag_id, shard_id)
        |VALUES
        |(?,?,?)
        |""".stripMargin

val conn = ckJdbcUtils.getLocalConnection
    val ps = conn.prepareStatement(initSQL)
    val bitmap = new RoaringBitmap()
    bitmap.add(110)
    bitmap.add(125)
    var i = 0
    var num =0
  for (i <- 1 to 100) {
    val bitmap = new RoaringBitmap()

    bitmap.add(i)
    ps.setObject(1, ClickHouseBitmap.wrap(bitmap,ClickHouseDataType.UInt32))
    ps.setLong(2, 8877)
    ps.setInt(3, 56)
    ps.addBatch()
    num+=1
    if (num >= 10) {
      println(s"record size ${num}")
      ps.executeBatch()
      num = 0
    }
  }

  if (num != 0) {
    println(s"record size ${num}")
    ps.executeBatch()
    ps.close()
  }
```

**Comment by zhicwu** [comment]
Hi @Nicemo, this is a known issue. I'd suggest you to use extended API like below:
```java
// use extended API - recommended in 0.3.0
try (ClickHouseStatement statement = connection.createStatement()) {
    statement.sendRowBinaryStream("insert into my_bitmap_table", new ClickHouseStreamCallback() {
        public void writeTo(ClickHouseRowBinaryStream stream) throws IOException {
            ...
            // RoaringBitmap bitmap = RoaringBitmap.bitmapOf(1,2,3,...);
            // In addition to RoaringBitmap, you can pass:
            // ImmutableRoaringBitmap, MutableRoaringBitmap and even Roaring64NavigableMap
            stream.writeBitmap(ClickHouseBitmap.wrap(bitmap, ClickHouseDataType.UInt32));
            ...
        }
    });
}
```

Current implementation of this driver has limited support for serializing binary data like bitmap in text format and send to server. I hope I can enhanced the driver in 0.3.2 by switching to RowBinary format.

**Comment by zhicwu** [comment]
`insert into table values(?,?,?)` was converted to a larger SQL with multiple values for batch insertion. It does not work with binary data very well, because we were using text-based data format and UTF-8 for encoding.

It's better to use input function(similar as external table but more like a pipe line) as example shown [here](../issues/661#issuecomment-985222705) instead.
