### ISSUE TITLE
cannot select column value which contains tab

### ISSUE THREAD

**Issue by fancy27** [ClickHouse/clickhouse-jdbc#676]
https://github.com/ClickHouse/clickhouse-jdbc/blob/5e6f74b89354e60af7d0c9437eef0520ee9ffda1/clickhouse-jdbc/src/main/java/ru/yandex/clickhouse/response/ClickHouseResultSet.java#L201

**Comment by den-crane** [comment]
????

For TSV CH encode tab as \t. Tab  = 0x09 can be returned only as column separator.

**Comment by fancy27** [comment]
> ????
> 
> For TSV Format CH encodes TAB as \t. Tab = 0x09 can be returned only as a column separator.

Sorry, I forgot the format. The sample query is "select x from db.tbl format csv", while x contains tab

**Comment by den-crane** [comment]
JDBC driver does not support queries with FORMAT.

**Comment by zhicwu** [comment]
@den-crane, I'll enhance JDBC driver to support multi-format for better usability. Taking above query as an example, when a header is missing from response, we can use `results Nullable(String)` as default. Special character(e.g. delimiter of fields/rows) handling will be improved after switching default format from TSV to RowBinary in 0.3.2.

Will get back to this after I'm done with the two new modules: `clickhouse-client` and `clickhouse-grpc-client` :sweat_smile:
