### ISSUE TITLE
Add force_optimize_skip_unused_shards and optimize_skip_unused_shards to ClickHouseQueryParam

### ISSUE THREAD

**Issue by ruanwenjun** [ClickHouse/clickhouse-jdbc#679]
see https://clickhouse.tech/docs/en/operations/settings/settings/#force-optimize-skip-unused-shards

**Comment by zhicwu** [comment]
In the new client/driver, you’ll be able to specify any setting as needed. But I think you can try any of below two approaches:
1. Use multi-statement query like below:
  ```sql
  set setting1=value1,setting2=value2;
  select * from mytable;
  ```
2. Add settings in your query
  ```sql
  select *
  from mytable
  settings setting1=value1,setting2=value2
  ```

**Comment by zhicwu** [comment]
With new option `custom_http_params`(comma separated) you should be able to customize settings as needed.
* application scope
  use connection url like `jdbc:ch://localhost/system?custom_http_params=force-optimize-skip-unused-shards%3D1` or set connection property `custom_http_params` to `A=1,B=2`.
* request scope
  ```java
  Statement s = conn.createStatement();
  ClickHouseRequest<?> req = s.unwrap(ClickHouseRequest.class);
  req.set("force-optimize-skip-unused-shards", 1);
  s.executeQuery("...");
  ```
