### ISSUE TITLE
[QUESTION] How to insert collection json strings into a table

### ISSUE THREAD

**Issue by cadet354** [ClickHouse/clickhouse-jdbc#681]
Hi, how to insert collection json strings into a table?
For example, I have a collection of objects, convert them to json strings and send them to a table.
```
// sorry for scala code
val sb = new StringBuilder()
events.map(ev => json.eventToString(ev)).foreach(s => sb.append(s +"\n"))
val stream = new ByteArrayInputStream(sb.toString().getBytes("UTF-8") )
try {
     sth.write().sendToTable(table, stream, ClickHouseFormat.JSONStringEachRow)
 } catch {
     case ex: java.sql.SQLException => log.error("An error occurred when inserting data into clickhouse", ex)
 }
```
but an exception occurs:
DB::Exception: Format JSONStringEachRow is not suitable for input (with processors).

I didn't find an example of using JSONStringEachRow in unit tests.

**Comment by zhicwu** [comment]
What's the table look like? `JSONStringEachRow` seems incorrect here as I only saw `JSONStringsEachRow` at https://clickhouse.tech/docs/en/interfaces/formats/. If it's just a string, then you probably should use `TabSeparated`(make sure your JSON strings are all escaped).

Anyway, below is an example in SQL:
``` sql
drop table aaa if exists;
create table aaa(a String, b String, c UInt32) engine = Memory;
insert into aaa format JSONStringsEachRow
{"a":"1","b":"2","c":"3"}
{"a":"4","b":"5","c":"6"}

```

**Comment by cadet354** [comment]
Okay, it works with ClickHouseFormat.JSONEachRow
