### ISSUE TITLE
system.columns.comment column was introduced only in 18.16.0

### ISSUE THREAD

**Issue by den-crane** [ClickHouse/clickhouse-jdbc#684]
https://github.com/ClickHouse/clickhouse-jdbc/blob/5e6f74b89354e60af7d0c9437eef0520ee9ffda1/clickhouse-jdbc/src/main/java/ru/yandex/clickhouse/ClickHouseDatabaseMetadata.java#L804

```
18.14.18

ClickHouse exception, code: 47, host: ....., port: 8123; Code: 47, e.displayText() = 
DB::Exception: Unknown identifier: comment, e.what() = DB::Exception [DB Errorcode=47]
```

ClickHouse Release 18.16.0
Now you can specify comments for a column in the table description https://github.com/ClickHouse/ClickHouse/pull/3377

**Comment by zhicwu** [comment]
Is 18.16 still supported? We can add it into below list for regression.
https://github.com/ClickHouse/clickhouse-jdbc/blob/5e6f74b89354e60af7d0c9437eef0520ee9ffda1/.github/workflows/build.yml#L37

Last time I was told that 19.16(and 20.3?) was no longer supported. I myself think the driver can support wider range. JDK 7 is probably not the case but we can add it back too.

**Comment by zhicwu** [comment]
@alexey-milovidov, am I supposed to be use below list for regression? Would be great if there's a similar configuration in ClickHouse server repo.

``` json
      {"code": "18.14.19",    "name": "18.14.19 Altinity Stable"},
      {"code": "19.11.12.69", "name": "19.11.12.69 Altinity Stable"},
      {"code": "19.13.7.57",  "name": "19.13.7.57 Altinity Stable"},
      {"code": "19.16.19.85", "name": "19.16.19.85 Altinity Stable"},
      {"code": "20.3.21.2",   "name": "20.3.21.2 Altinity Stable"},
      {"code": "20.8.12.2",   "name": "20.8.12.2 Altinity Stable"},
      {"code": "21.1.9.41",   "name": "21.1.9.41 Altinity Stable"},
      {"code": "21.3.13.9",   "name": "21.3.13.9 Altinity Stable"},
      {"code": "21.5.9.4",    "name": "21.5.9.4"},
      {"code": "21.6.7.57",   "name": "21.6.7.57"}
```
https://github.com/Altinity/ch-stable-versions/blob/c83b2b51e98ea156dd2c31e95c69a41a360f64b8/versions.json#L22-L31

**Comment by alexey-milovidov** [comment]
Yes, you can check against these versions.

PS. "Altinity stable" is just a tag for some old frozen release. It does not mean that this release is somehow supported.
Neither it means that release is somehow stable. In fact, old releases contains issues of high severety that were fixed long time ago. Nevertheless, you can find these releases in production for use cases where they work perfectly.

**Comment by alexey-milovidov** [comment]
We don't maintain the list of https://github.com/Altinity/ch-stable-versions/blob/c83b2b51e98ea156dd2c31e95c69a41a360f64b8/versions.json#L22-L31 - it contains outdated info and not updated in a timely fashion.

**Comment by zhicwu** [comment]
> We don't maintain the list of https://github.com/Altinity/ch-stable-versions/blob/c83b2b51e98ea156dd2c31e95c69a41a360f64b8/versions.json#L22-L31 - it contains outdated info and not updated in a timely fashion.

Thanks @alexey-milovidov. Wouldn't it better to maintain a list of all supported versions(mostly in format of major.minor) in a text(yaml/json) file in server repository? That way, all clickhouse clients can use that as inputs for regression test to ensure backward compatibility.

**Comment by alexey-milovidov** [comment]
Here is the list: https://github.com/ClickHouse/ClickHouse/pulls?q=is%3Aopen+is%3Apr+label%3Arelease
