### ISSUE TITLE
Is clickhouse jdbc compatible with all clickhouse versions?

### ISSUE THREAD

**Issue by peterZhiFate** [ClickHouse/clickhouse-jdbc#692]

**Comment by zhicwu** [comment]
I wish but it should work with all [active releases](../../ClickHouse/pulls?q=is%3Aopen+is%3Apr+label%3Arelease). You can still try for older version like 18.14 or 19.16 but you may hit issue.

**Comment by peterZhiFate** [comment]
Okay,thanks!
