### ISSUE TITLE
Parser cannot parse backslashed value

### ISSUE THREAD

**Issue by kaifeur** [ClickHouse/clickhouse-jdbc#695]
Trying to execute query like this:
```sql
SELECT * FROM t WHERE col IN (?);
```
and using `preparedStatement.setObject(1, [some byte array])`.
So the resulting sql looks like
```sql
SELECT * FROM t WHERE col IN (\x12\x34\x56);
```
and then parser is failing with an exception: `Failed to parse the given SQL. If you believe the SQL is valid, please feel free to open an issue on Github with the following SQL and exception attached.`

**Comment by zhicwu** [comment]
Hi @rubtsovnyu, was this working before? The SQL is invalid - perhaps you meant something like `select 0x12`? Moreover, are you trying to issue a query like `select * from t where col in (1,2,3)`? If that's the case and you still want to use prepared statement, you may try something like below:
``` java
// values is a byte array
StringBuilder sql = new StringBuilder("select * from t where col in (");
for (byte b : values) {
  sql.append(",?");
}
if (sql.length() > 0) {
  sql.deleteCharAt(0);
} else {
  throw new IllegalArgumentException("at least one input is required");
}
sql.insert(0, "select * from t where col in (").append(')');
try (PreparedStatement ps = connection.preparedStatement(sql.toString())) {
  for(int i = 0; i< values.length; i++) {
    ps.setInt(i + 1, values[i]);
  }
  ps.execute...
}
```

**Comment by rubtsovnyu** [comment]
1. It is working on 0.1.54 (don't know the format it uses). And I don't know the version until it works. Now I'm using 0.3.0 (0.3.1 and 0.3.1-patch are giving the same result).
2. ClickHouse JDBC builds this SQL for me. Just check `ru.yandex.clickhouse.util.ClickHouseValueFormatter#formatBytes`.

**Comment by rubtsovnyu** [comment]
Reproducing snippet:

```sql
CREATE TABLE t
(
    col_1 Array(Int8)
) ENGINE = Memory;

INSERT INTO t
VALUES ([1,2,3,4]);
```

```java
String url = "jdbc:clickhouse://127.0.0.1:8123";
            ClickHouseDataSource dataSource = new ClickHouseDataSource(url);
            ClickHouseConnection connection = dataSource.getConnection();
            PreparedStatement prepareStatement = connection.prepareStatement("SELECT * FROM t WHERE col_1 IN (?)");
            prepareStatement.setObject(1, new byte[]{1,2,3,4});
            ResultSet resultSet = prepareStatement.executeQuery();
```

**Comment by zhicwu** [comment]
Thanks for the clarification. I added a unit test which can reproduce the issue even use `ClickHouseArray`.

This was introduced in commit 3be7a3c90a9a8a4bfef8aa0de8822b4bbf43f5b7, but before I roll it back, I need some time to digest what that was for.

**Comment by zhicwu** [comment]
I didn't change code but the issue should not exist in the new driver(com.clickhouse.jdbc.ClickHouseDriver).
