### ISSUE TITLE
AggregateFunction(groupBitmap,UInt64) support

### ISSUE THREAD

**Issue by booleguo** [ClickHouse/clickhouse-jdbc#698]
hello, my column define as AggregateFunction(groupBitmap,UInt64), but failed to convert ClickhouseBitMap.
error message like: 
No able to deserialize ClickhouseBitmap for too many bitmaps

**Comment by zhicwu** [comment]
What's the size of the bitmap? Is it more than 4,294,967,295? And which version of ClickHouse are you using? If it's 20.8 or early, I'd suggest to upgrade to a more recent version.

**Comment by booleguo** [comment]
20.10.2.20。data size is 20000000.

**Comment by zhicwu** [comment]
OK, I'll take a look tonight. Would be great if you can provide sample data to reproduce the issue if that's OK for you.

**Comment by booleguo** [comment]
create table string_labels (
`label` String,
`value` String,
`uv` AggregateFunction(groupBitmap, UInt64)
) ENGINE = AggregatingMergeTree()
partition by label
order by (label, value);

create tabel user_string_properties (
`uid` UInt64,
`label` String,
`value` String
)ENGINE=MergeTree()
order by uid;

create materialized view string_labels_mv to string_labels as
select label,
value,
groupBitmapState(uid) as uv
from user_string_properties
group by (label, value);

insert into user_string_properties 
select number as uid,
'gender' as label,
multiIf((number % 3) = 0, 'f', 'm') as value
from numbers(20000000);

query sql:
select groupBitmapMergeState(uv) as uv from string_labels where label = 'gender' and value = 'f';

**Comment by zhicwu** [comment]
Thanks @booleguo. I was able to reproduce the issue on 20.8, 20.10.2.20 and 20.10.7.4. However, it works well on 21.3 and above. 

From what I saw, the data returned from server is a bit different among these version(with or without flag and map size etc.). I'm not sure if it's worthy of fixing this from client-side - is it feasible for you to upgrade to a more recent stable/lts release?

**Comment by booleguo** [comment]
thanks for your answer。It's just produce on test cluster for inner team。
