### ISSUE TITLE
How to enable compression while using standard JDBC connection?

### ISSUE THREAD

**Issue by deltacat** [ClickHouse/clickhouse-jdbc#700]
We know extend api support compression.
But if using standard JDBC connection and an connection pool (such as DruidDataSource), seems not support compression.

How to enable compression in this case?

**Comment by zhicwu** [comment]
Hi @deltacat, LZ4 compression is enabled by default.

**Comment by deltacat** [comment]
> Hi @deltacat, LZ4 compression is enabled by default.

Thanks zhicwu.

And, do you mean, jdbc driver send compressed data via http by default?

**Comment by zhicwu** [comment]
Sorry I replied in a hurry. There are two options for compression:
* compress - defaults to `1`, meaning server will compress the data it sends to client
* decompress - default to `0`, meaning server will NOT decompress the data from client

Are you trying to load lots of data? I guess what you observed is probably related the second option.

**Comment by deltacat** [comment]
> Are you trying to load lots of data? I guess what you observed is probably related the second option.

yes, I'm trying to send lots of data to clickhouse, so I need save bandwidth.

**Comment by deltacat** [comment]
dear @zhicwu, I tried option2, use url like this: `jdbc:clickhouse://192.168.1.100:8123/test?decompress=1`

Is this usage is correct? seems it works for me: data load from 200Mbps to less 10Mbps. 

looks good. thanks.
