### ISSUE TITLE
How to set the 'union_default_mode' attribute on the connection string?

### ISSUE THREAD

**Issue by peterZhiFate** [ClickHouse/clickhouse-jdbc#701]
I execute this sql(SELECT c_ip4, c_ip6, NULL AS c_string, NULL AS c_fixstring FROM test.t_ip UNION SELECT NULL AS c_ip4, NULL AS c_ip6, c_string, c_fixstring FROM test.t_string) statement through the clickhouse jdbc driver, but the driver returns the following error.

error message: ClickHouse exception, code: 558, host: localhost, port: 8123; Code: 558, e.displayText() = DB::Exception: Expected ALL or DISTINCT in SelectWithUnion query, because setting (union_default_mode) is empty: While processing SELECT c_string, c_fixstring, NULL AS x, NULL AS y FROM test.t_string UNION SELECT NULL AS c_string, NULL AS c_fixstring, x, y FROM test.t_uuid (version 21.7.2.7 (official build))

How can I set this attribute value on the connection string?

**Comment by zhicwu** [comment]
Why not use `UNION ALL` or `UNION DISTINCT` in your query? `union_default_mode` is currently not available in settings but you can create a PR for the change.

**Comment by peterZhiFate** [comment]
Okay, I understand now, thanks

As for why not use UNION ALL or UNION DISTINCT directly, because this sql is generated by our product, not handwritten sql. In order not to change the existing logic, I would like to ask if this attribute can be set directly on the connection string.
Thanks again.

**Comment by wlam-tibco** [comment]
settings can be passed with the prefix clickhouse_setting_
```
jdbc:clickhouse:<HOST>:8443?ssl=true&clickhouse_setting_union_default_mode=DISTINCT
