### ISSUE TITLE
Pentaho PDI use JDBC to ClickHouse ,can not select 

### ISSUE THREAD

**Issue by qinlz-1** [ClickHouse/clickhouse-jdbc#702]
![image](https://user-images.githubusercontent.com/80371132/128697252-a03a0492-059e-4fde-bf12-b2e775eabe95.png)

**Comment by zhicwu** [comment]
Because the target column is `DateTime`? Perhaps you can change the format to something like `2021-07-11 12:12:12`?

**Comment by qinlz-1** [comment]
@zhicwu 
table stuctrure
![image](https://user-images.githubusercontent.com/80371132/128794699-611815de-0280-430e-aebb-8b1b7d2f60f9.png)
jdbc version : clickhouse-jdbc-0.1.54

**Comment by zhicwu** [comment]
> jdbc version : clickhouse-jdbc-0.1.54

Not sure if there's any specific reason of using an outdated version of the driver... What's the version of ClickHouse server by the way? Can you try [0.3.1-patch](../releases/download/v0.3.1-patch/clickhouse-jdbc-0.3.1-patch-shaded.jar)?
