### ISSUE TITLE
How to set allow_experimental_window_functions property?

### ISSUE THREAD

**Issue by peterZhiFate** [ClickHouse/clickhouse-jdbc#704]
When I execute this sql statement,
SELECT (ROW_NUMBER() OVER ( ORDER BY "SingleTable"."PRODUCT" ASC )) AS "c0" FROM "SingleTable"

But I can see that he reported the following error message.
SQL 错误 [48]: ClickHouse exception, code: 48, host: xa-dd2-db2, port: 8123; Code: 48, e.displayText() = DB::Exception: The support for window functions is experimental and will change in backwards-incompatible ways in the future releases. Set allow_experimental_window_functions = 1 to enable it. While processing 'row_number() OVER (ORDER BY 产品 ASC) AS c0' (version 21.7.6.39 (official build))

How do I set this property through the jdbc driver?

**Comment by peterZhiFate** [comment]
When I execute this sql statement, 
`SELECT (ROW_NUMBER() OVER ( ORDER BY "SingleTable"."PRODUCT" ASC )) AS "c0" FROM "SingleTable"`

But I can see that he reported the following error message.  
SQL 错误 [48]: ClickHouse exception, code: 48, host: xa-dd2-db2, port: 8123; Code: 48, e.displayText() = DB::Exception: The support for window functions is experimental and will change in backwards-incompatible ways in the future releases. Set allow_experimental_window_functions = 1 to enable it. While processing 'row_number() OVER (ORDER BY `产品` ASC) AS c0' (version 21.7.6.39 (official build))

How do I set this property through the jdbc driver?

**Comment by sherrychenzhang** [comment]
./clickhouse client --allow_experimental_window_functions = 1

**Comment by peterZhiFate** [comment]
Yes, I can execute the startup in this way on the client and the execution is successful.

But when I execute the java code through the clickhouse jdbc jar package, I still get the same error.

How do I set this attribute through clickhouse jdbc jar?

**Comment by sherrychenzhang** [comment]
have no idea, new to jdbc too, even do not know how to run jdbc. do you have any idea on how to run jdbc benchmark?

**Comment by den-crane** [comment]
1st way.

```
SELECT
    x,
    sum(x) OVER (PARTITION BY intDiv(x, 5))
FROM
(
    SELECT arrayJoin(range(10)) AS x
) settings  allow_experimental_window_functions = 1;
```
-----------------
2nd way.
Set session_id in jdbc driver: session_id = 'random_string'

```
set allow_experimental_window_functions = 1;

SELECT
    x,
    sum(x) OVER (PARTITION BY intDiv(x, 5))
FROM
(
    SELECT arrayJoin(range(10)) AS x
) settings  allow_experimental_window_functions = 1;
```
-----------
3d way

set in users profile at server

```
$ cat /etc/clickhouse-server/users.d/allow_experimental_window_functions.xml
<?xml version="1.0"?>
<yandex>
   <profiles>
       <default>
           <allow_experimental_window_functions>1</allow_experimental_window_functions>
       </default>
   </profiles>
</yandex>
```

**Comment by peterZhiFate** [comment]
Okay, I tried it successfully, thank you very much.
