### ISSUE TITLE
Does clickhouse jdbc preparedstatement support set timestamp with nanoseconds? 

### ISSUE THREAD

**Issue by KaimingWan** [ClickHouse/clickhouse-jdbc#709]
clickhouse jdbc version: 0.3.1

The column type is datetime64(6) in my clickhouse table. I use the following code to set timestamp value. When I execute query I find the precision is not correct. Expected value is '2021-09-01 00:00:00.123456' and the actually value is '2021-09-01 00:00:00.123'. 

```java
value = '2021-09-01 00:00:00.123456'
pstmt.setObject(i, value);
```

**Comment by zhicwu** [comment]
Sorry it does not work well at this point. Please refer to discussion in #608.

**Comment by KaimingWan** [comment]
@zhicwu Thanks, I will pay attention to the latest clickhouse driver.

**Comment by zhicwu** [comment]
Now it works in 0.3.2, but please consider to use setObject and LocalDateTime for better performance.
