### ISSUE TITLE
Add back readUnsignedLeb128 in ClickHouseRowBinaryInputStream

### ISSUE THREAD

**Issue by vonnagy** [ClickHouse/clickhouse-jdbc#710]
When using the **ClickHouseRowBinaryInputStream** we used to be able to manually read string, arrays, etc by calling _readUnsignedLeb128_ to get the length and then iterating through the elements. It was removed with version **0.3.0** (commit# 074a03041b579b3f7cc6b6dde80d34a4ec6c1879). See [here](https://github.com/ClickHouse/clickhouse-jdbc/commit/074a03041b579b3f7cc6b6dde80d34a4ec6c1879#diff-b565dcef1670970f020046105051be32733a468aac87fbedcd933c8c361301bcL37) for the change. Since the **ClickHouseRowBinaryInputStream** class interacts with the private instance of **DataInputStream** there is no current access to the information.

The following code could be added back.
```
public int readUnsignedLeb128() throws IOException {
    return Utils.readUnsignedLeb128(in);
}
```

**Comment by zhicwu** [comment]
Thanks for pointing this out @vonnagy. I'll add it back in next release. However, please be aware that extended API including `ClickHouseRowBinaryInputStream` will be removed from `clickhouse-jdbc` starting from 0.4, as it will be replaced by `clickhouse-client`.

**Comment by lucky** [comment]
> However, please be aware that extended API including `ClickHouseRowBinaryInputStream` will be removed from `clickhouse-jdbc` starting from 0.4, as it will be replaced by `clickhouse-client`.

Will there be any library support for `RowBinary(WithNamesAndTypes)` anywhere?

**Comment by zhicwu** [comment]
> Will there be any library support for `RowBinary(WithNamesAndTypes)` anywhere?

Yes. I'm going to create a PR tonight to upload new client, which is async by default and is built on top of gRPC and RowBinary format. With that, you can use `com.clickhouse.client.data.BinaryStreamUtils` to read/write most of data types(including Geo types) in RowBinary format. For nested data types like Array, Map, Nested, Tuple, and combined types(e.g. Array of Tuple in Nested column), you'll have to use methods in `ClickHouseRowBinaryDataProcessor`.

**Comment by zhicwu** [comment]
Merged into develop branch and will release in 0.3.2.

**Comment by zhicwu** [comment]
> Did this ever happen? Is it a part of this repo?

It's been merged into `develop` branch. 
https://github.com/ClickHouse/clickhouse-jdbc/blob/2a61ab3bf9477efc80b351ef176ebe69cf14be8f/clickhouse-jdbc/src/main/java/ru/yandex/clickhouse/util/ClickHouseRowBinaryInputStream.java#L72-L74
