### ISSUE TITLE
How to close Balancedatasource schedule thread?

### ISSUE THREAD

**Issue by nstang01** [ClickHouse/clickhouse-jdbc#716]
public BalancedClickhouseDataSource scheduleActualization(int delay, TimeUnit timeUnit) {
        ClickHouseDriver.ScheduledConnectionCleaner.INSTANCE.scheduleWithFixedDelay(new Runnable() {
            @Override
            public void run() {
                try {
                    actualize();
                } catch (Exception e) {
                    log.error("Unable to actualize urls", e);
                }
            }
        }, 0, delay, timeUnit);

        return this;
    }

When I use this thread in my code, how will I close it？

**Comment by zhicwu** [comment]
It's a daemon thread. Could you elaborate why you need to terminate the thread manually? Anyway, if you really need to do that, you'll have to put your code under same package and manually shutdown the executor service.
