### ISSUE TITLE
ClickHouseExceptionSpecifier returns ClickHouseUnknownException while underlying DB::Exception is actually known.

### ISSUE THREAD

**Issue by PavelRuban** [ClickHouse/clickhouse-jdbc#729]
As far as I understand ClickHouseExceptionSpecifier is trying to extract the code of DB::Exception from the error message generated by clickhouse-server. It should return new ClickHouseException initialized with that extracted code if extraction was successful.

Unfortunately it looks like actual error message format is different from the one getErrorCode() method is expecting:
![image](https://user-images.githubusercontent.com/2482396/134789989-1d6de6ee-c979-423b-9b8d-44e172709605.png)

So getErrorCode() returns -1 instead of actually received code. That means exception was not recognized, so specify() returns ClickHouseUnknownException instead of ClickHouseException(code). 

Also I found the string of such format could be returned from Exception::getExceptionMessage  (https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/Exception.cpp)
Line 476:  stream << "Code: " << e.code() << ". " << text;

So I suggest to look for dot as well as for comma in order to extract error code correctly.

**Comment by zhicwu** [comment]
This actually caused failures in integration test as well. It's been fixed and I'll come up with a PR to get it merged into develop branch.

**Comment by zhicwu** [comment]
Fixed in develop branch, will release in 0.3.2.
