### ISSUE TITLE
Select from map with LowCardinality keys returns ClickHouseUnknownException: ClickHouse exception, message: Parse exception: ByteFragment

### ISSUE THREAD

**Issue by vmnikulin** [ClickHouse/clickhouse-jdbc#730]
Hello, 

My setup
Clickhouse server version 21.9.4 revision 54449
Clickhouse client version 21.9.4.35 
JDBC version 0.3.1

Native client works
```
CREATE TABLE lcmap (m Map(LowCardinality(String), Int32)) ENGINE=Memory;
//...
INSERT INTO lcmap(m) VALUES ({'key1':1});

//...
select * from lcmap;
//...
┌─m──────────┐
│ {'key1':1} │
└────────────
```

But when I try to execute `select * from lcmap;` in Datagrip I get
```
<failed to load>
ru.yandex.clickhouse.except.ClickHouseUnknownException: ClickHouse exception, message: Parse exception: ByteFragment{[{'key1':1}], start=0, len=10}; null
	at ru.yandex.clickhouse.response.ClickHouseResultSet.getObject(ClickHouseResultSet.java:648)
	in JdbcHelperImpl.getObject(JdbcHelperImpl.java:321)
Caused by: java.lang.NullPointerException
	at java.base/java.util.Objects.requireNonNull(Objects.java:221)
	at ru.yandex.clickhouse.response.parser.ClickHouseMapParser.parse(ClickHouseMapParser.java:119)
	at ru.yandex.clickhouse.response.parser.ClickHouseMapParser.parse(ClickHouseMapParser.java:17)
	at ru.yandex.clickhouse.response.ClickHouseResultSet.getObject(ClickHouseResultSet.java:749)
	at ru.yandex.clickhouse.response.ClickHouseResultSet.getObject(ClickHouseResultSet.java:642)
	... 21 more
```

**Comment by zhicwu** [comment]
Thanks for reporting the issue. The driver does not support nested data types very well at this point. It understands `Map(String, Int32)` but not `Map(LowCardinality(String), Int32)`, `Map(String, Nullable(Int32))`, or `Map<String, Tuple(Int32, Array())>`. Actually these cases work in an in-development version, so I believe this will be addressed in next release.

**Comment by vmnikulin** [comment]
Thank you for your answer.
That is great.

I have tried to build `0.3.2-SNAPSHOT` from `develop` with `mvn package -DskipTests=true` and use `clickhouse-jdbc-0.3.2-SNAPSHOT-shaded.jar` in Datagrip. And I have got the same exception. 
Could you please give some advice on how to build the in-development version?

**Comment by zhicwu** [comment]
Sorry I'm in the middle of merging new gRPC client into develop branch. After which, I'll create another pull request by updating JDBC driver, clickhouse-jdbc module to be more specific, to use the new client in order to support more data types.

If you're familiar with Java, you may play with the new client in these two days to explore what's coming next.

**Comment by vmnikulin** [comment]
Great, thank you!
I am looking forward to the new version to see what is coming.

By the way, I made a quick fix in `ClickHouseColumnInfo.splitArgs` locally to fix the issue.

**Comment by zhicwu** [comment]
Tried the query on DBeaver, it works using the new JDBC driver.
