### ISSUE TITLE
RowBinary format support Map DataType

### ISSUE THREAD

**Issue by taylor12805** [ClickHouse/clickhouse-jdbc#744]
Since now ClickHouse support Map datatype, maybe there should be api to write Map datatype using RowBinary format. It is not quite easy because Map key value can both be defined as primitive types. 
I suppose we can define DataType class to include all necessary primitive types and then define generic 
`<T, R> void writeMap(T[] keys, R[] values, DataType keyType, DataType valueType)`
function in ClickHouseRowBinaryStream class? Or is there any better solution?

**Comment by taylor12805** [comment]
Looks quite awesome, will try it later

**Comment by zhicwu** [comment]
It's been merged into develop branch. Besides Java client, you can use the new JDBC driver(com.clickhouse.jdbc.ClickHouseDriver) to read/write Map data(using getObject/setObject method).
