### ISSUE TITLE
ALTER TABLE UPDATE statement run without default database

### ISSUE THREAD

**Issue by welyss** [ClickHouse/clickhouse-jdbc#750]
insert ok, alter table update can't take the default database,
found that in file "ClickHouseStatementImpl" method "getInputStream":
`boolean ignoreDatabase = parsedStmt.isRecognized() && !parsedStmt.isDML();`
ALTER TABLE UPDATE is Recognized to DDL, is there any option to change this logic

**Comment by zhicwu** [comment]
This has been fixed in develop branch. Make sure you use the new JDBC driver `com.clickhouse.jdbc.ClickHouseDriver`.

```sql
alter table test_date update ndate='2021-11-10' where ndate is null;

-- same as alter table test_date update ndate='2021-11-11' where no = 0 settings mutations_sync=1
update test_date set ndate='2021-11-11' where no = 0
```

**Comment by welyss** [comment]
thanks!I will check it on 0.3.2 release.
