### ISSUE TITLE
Nanoseconds existence check bug

### ISSUE THREAD

**Issue by oduvanov** [ClickHouse/clickhouse-jdbc#754]
https://github.com/ClickHouse/clickhouse-jdbc/blob/272d9c48b1d72a7605953b6c94d760f2895afafb/clickhouse-jdbc/src/main/java/ru/yandex/clickhouse/util/ClickHouseValueFormatter.java#L133

Guys, please, fix nanoseconds existence check bug. You should use 1_000_000_000 (nano) not 1_000_000 (micro) for this check.

**Comment by zhicwu** [comment]
Actually fixing the check won't help much as the old driver relied on text-based data format and parsing and it was painful to handle date time and especially time zone. You may now use new JDBC driver `com.clickhouse.jdbc.ClickHouseDriver` in 0.3.2 instead.

Will revisit this issue later together with TabSeparated format enhancement.

**Comment by zhicwu** [comment]
Close as the legacy driver has been removed and the issue does not exist in new driver.
