### ISSUE TITLE
Execute me. ClickHouseStatement batch insert bitmap data to DB will support in version 0.3.2??

### ISSUE THREAD

**Issue by akumalzw** [ClickHouse/clickhouse-jdbc#772]
Read the test code of version 0.3.2-test， it also mark like this:
        // FIXME too bad batching is not supported

It has any other way to batch insert bitmap datas to db?
Thanks..

**Comment by zhicwu** [comment]
Yes, it will be supported in 0.3.2. Please refer to examples at [here](../issues/661#issuecomment-985222705).

**Comment by akumalzw** [comment]
Tansks..
