### ISSUE TITLE
How to batch insert when insert bitmap with JDBC interface

### ISSUE THREAD

**Issue by czk97** [ClickHouse/clickhouse-jdbc#773]
Following the JDBC interface example, when I used the batch insert bitmap, the bitmap field value of clickhouse table was empty. Does not support batch bitmap insertion?  clichhouse JDBC version ： 0.3.1
https://github.com/ClickHouse/clickhouse-jdbc/issues/532#issuecomment-803593655

**Comment by zhicwu** [comment]
Duplicated with #661, there's examples and you can try it out using v[0.3.2-test2](../releases/tag/v0.3.2-test2).
