### ISSUE TITLE
Field LocalDateTime precision loss issue

### ISSUE THREAD

**Issue by ltl0814** [ClickHouse/clickhouse-jdbc#782]
Hi, when I use LocalDateTime as a parameter to execute sql , I found that you will format LocalDateTime to String with 'yyyy-MM-dd HH:mm:ss' , and so that it will discard the precision  after second. How could I do to reserve all precision(MilliSecond or NanoSecond)?

**Comment by zhicwu** [comment]
This is a bit tricky as we don't know if the target column supports nano seconds or not. However, starting from 0.3.2(try test builds at [here](../releases/tag/v0.3.2-test3)), you have below options:
* simple query - use `setString` to set formatted string instead, or [named parameter](../blob/48a6281ff348e5ca6ba80a3fdec6b9823ace905b/clickhouse-jdbc/src/test/java/com/clickhouse/jdbc/ClickHousePreparedStatementTest.java#L148-L164) if it's not too weird
* batched
  - use external table as in [here](../blob/48a6281ff348e5ca6ba80a3fdec6b9823ace905b/clickhouse-jdbc/src/test/java/com/clickhouse/jdbc/ClickHousePreparedStatementTest.java#L112-L127)
  - or input function for insertion like [this](../blob/48a6281ff348e5ca6ba80a3fdec6b9823ace905b/clickhouse-jdbc/src/test/java/com/clickhouse/jdbc/ClickHousePreparedStatementTest.java#L49-L68)
