### ISSUE TITLE
0.3.2 versions，Recommended database connection pool？

### ISSUE THREAD

**Issue by kiwimg** [ClickHouse/clickhouse-jdbc#786]
springboot project，Which database connection pool is recommended？

**Comment by zhicwu** [comment]
0.3.2 only supports http and grpc so connection pool is not very help. You can pick whatever you want. However, after tcp client being added into 0.3.3, you probably need a connection pool like HikariCP.

**Comment by darkleaf** [comment]
@zhicwu  can I share ClichouseClient across threads?

**Comment by zhicwu** [comment]
> @zhicwu can I share ClichouseClient across threads?

Yes, you can. But please keep in mind that the same `ClickHouseClient` instance may hold same "connection" to the server. Taking `clickhouse-http-client` as an example, the default implementation uses separate `HttpURLConnection` instance for each request. However, behind the scene, `HttpURLConnection` maintains a pool for reusing socket.

As long as the lifecycle of a ClickHouseClient instance is well managed, in most cases, you just use `ClickHouseRequest` for execution, for example:

```java
try (ClickHouseClient client = ClickHouseClient.newInstance()) {
    ClickHouseRequest<?> req = client.connect(server).format(ClickHouseFormat.RowBinaryWithNamesAndTypes);

    AtomicInteger i = new AtomicInteger(0);
    CountDownLatch c = new CountDownLatch(2);
    ClickHouseResponse queryResp = req.query("select 1").execute().get();
    Assert.assertEquals(i.incrementAndGet(), 1);

    try (ClickHouseResponse resp = req.query("select 2").execute().get()) {
        Assert.assertEquals(resp.firstRecord().getValue(0).asInteger(), 2);
        Assert.assertEquals(i.incrementAndGet(), 2);
    }

    req.query("select 3").execute().thenAccept(r -> {
        Assert.assertTrue(i.incrementAndGet() > 2);
        Assert.assertEquals(r.firstRecord().getValue(0).asInteger(), 3);
        c.countDown();
    });

    new Thread(() -> req.query("select 5").execute().thenAccept(r -> {
        Assert.assertTrue(i.incrementAndGet() > 2);
        Assert.assertEquals(r.firstRecord().getValue(0).asInteger(), 5);
        c.countDown();
    })).start();

    Assert.assertTrue(i.get() >= 2);
    Assert.assertTrue(c.await(3, TimeUnit.SECONDS));
    Assert.assertTrue(i.incrementAndGet() == 5);
    Assert.assertEquals(queryResp.firstRecord().getValue(0).asInteger(), 1);
}
```

**Comment by darkleaf** [comment]
So, I should use fresh ClickHouseClient per an incoming request and it's ok. Thanks!

**Comment by AntonOyung** [comment]
@zhicwu Is there a rough limit (or guideline) for when it's recommended we maintain a pool of ClickHouseClients instead of generating a new client per request? (Whether it's a limit of total open clients at any given time, or frequency of writes, or volume of writes, etc)?

I'm developing an application with frequent writes of high volume on multiple threads and it seems like it wouldn't be performant to generate new clients per request
