### ISSUE TITLE
How to use batch insert select

### ISSUE THREAD

**Issue by chen-shu-hao** [ClickHouse/clickhouse-jdbc#793]
Because I am not inserting a certain value, What I do is the real-time update of a large number of user data, and some cumulative operations，I cannot use the existing TSV, CSV and parquet. Instead, I need to query and then insert ，
insert into table2

(column_name(s))

select column_ name(s)

FROM table1;
,but I can only implement this one by one, not the effect I want

**Comment by chen-shu-hao** [comment]
https://github.com/ClickHouse/ClickHouse/issues/33245

**Comment by zhicwu** [comment]
Is the source a table or a query? How many sources you're facing?

It looks like you don't need batch insert at all, but a query like `insert into target_table (select * from table_1 union all select * from table_2 ... select * from table_n)`?

**Comment by chen-shu-hao** [comment]
1.I use replacingmergetree
2.insert into table2  （select col1 + 1，col2 - 2 from table1 union all select col2 + 1，col 3- 2  from table1）  ; 
I just want to insert some fields. You need all fields to be consistent. Is there any way to do it similar to jsoneachrow? When I do mass update, I update the fields when I set them, and ignore them when I don't set them
INSERT INTO UserActivity FORMAT JSONEachRow {"PageViews":5, "UserID":"4324182021466249494", "Duration":146,"Sign":-1} {"UserID":"4324182021466249494","PageViews":6,"Duration":185,"Sign":1}
3.Or do you have any other way to implement this requirement，thanks

**Comment by zhicwu** [comment]
It's not as convenient as JSONEachRow, but maybe you can use query like below? 

```sql
insert into table2(col1, col2, col3) 
(
  select col1 + 1，col2 - 2, UInt32(0) as col3 from table1
  union all
  select toUInt64(0) as col1, col2 + 1，col 3- 2 from table1
)
```
