### ISSUE TITLE
DBeaver unable to connect to Clickhouse

### ISSUE THREAD

**Issue by shaikhAbuzar** [ClickHouse/clickhouse-jdbc#794]
Whenever I try connecting to Clickhouse Instance it gives me the following error.
![image](https://user-images.githubusercontent.com/22410837/148210272-51b07a37-e502-4d25-82b0-fca06137ef6c.png)

I am using DBeaver 21.3.2

I have tried uninstalling, removing all the files from my system from the previous installation, rebooting my system, and then installing DBeaver again. But no luck.

**Comment by zhicwu** [comment]
Could you also provide version of ClickHouse and the jdbc driver used in DBeaver?

If you're running ClickHouse 20.7 or above, you can download [latest driver](https://github.com/ClickHouse/clickhouse-jdbc/releases/download/v0.3.2/clickhouse-jdbc-0.3.2-http.jar), and then go to Database -> Driver -> ClickHouse to update driver settings like below in DBeaver.
![image](https://user-images.githubusercontent.com/4270380/148305222-166f408c-9f69-4c6f-9be7-228470ae0ac6.png)

Submitted dbeaver/dbeaver#15118 to update driver to latest.
