### ISSUE TITLE
The most-effective batch insert (grpc, non-jdbc)

### ISSUE THREAD

**Issue by kbespalov** [ClickHouse/clickhouse-jdbc#795]
Hi!

Is there an example of an effective batched insert (grpc, non-jdbc) e.g. 100k parametrized (type-safe) rows using client ?
I couldn't find anything related. It would be great if examples appeared in the repository like this:

https://github.com/yandex-cloud/ydb-java-sdk/tree/master/examples/src/main/java/com/yandex/ydb/examples

Thanks!

**Comment by zhicwu** [comment]
Thanks for the suggestion. I thought about creating a folder just for examples. Will do that tonight and release it together with 0.3.1-patch1 on Sunday.

**Comment by zhicwu** [comment]
I think the most efficent way would be writing a gRPC client by yourself, because you have full control there. Anyway, I added [a few examples](https://github.com/ClickHouse/clickhouse-jdbc/blob/develop/examples/grpc/src/main/java/com/clickhouse/examples/jdbc/Main.java) and I hope they can be of use.

**Comment by kbespalov** [comment]
Very helpful, thanks!

**Comment by zhicwu** [comment]
> Very helpful, thanks!

You are welcome. IMO, gRPC works but it's not as mature as HTTP or TCP. If you prefer gRPC and don't have plan to switch to HTTP/TCP in the future, neither neither JDBC nor clickhouse-client should be used. Instead, you'd better consider to write your own client, which is similar as [ClickHouseGrpcClient](https://github.com/ClickHouse/clickhouse-jdbc/blob/v0.3.2-patch1/clickhouse-grpc-client/src/main/java/com/clickhouse/client/grpc/ClickHouseGrpcClient.java).
