### ISSUE TITLE
Pentaho Spoon Problem when I try to connect clickhouse table.

### ISSUE THREAD

**Issue by deniztek** [ClickHouse/clickhouse-jdbc#813]
I copied the JDBC folder into the /data-integration/lib and I build on clickhouse database on the generic database. Still, I am faced with a problem which is my spoon freezing when I try to upload the clickhouse table.
![clickhouseproblem](https://user-images.githubusercontent.com/97874273/149885131-9f307e3d-179b-4f07-b1b8-0759c3e7d056.png)

**Comment by zhicwu** [comment]
Did you check `system.query_log` to understand what was the query issued from PDI to ClickHouse?

**Comment by deniztek** [comment]
Hello, I got this error when I wrote system.query_log,

position 7 ('.'): .query_log. Expected one of: UNKNOWN, SHUTDOWN, KILL, SUSPEND, DROP DNS CACHE, DROP MARK CACHE, DROP UNCOMPRESSED CACHE, DROP INDEX MARK CACHE, DROP INDEX UNCOMPRESSED CACHE, DROP MMAP CACHE, DROP COMPILED EXPRESSION CACHE, STOP LISTEN QUERIES, START LISTEN QUERIES, RESTART REPLICAS, RESTART REPLICA, RESTORE REPLICA, DROP REPLICA, SYNC REPLICA, RELOAD DICTIONARY, RELOAD DICTIONARIES, RELOAD MODEL, RELOAD MODELS, RELOAD FUNCTION, RELOAD FUNCTIONS, RELOAD EMBEDDED DICTIONARIES, RELOAD CONFIG, RELOAD SYMBOLS, RESTART DISK, STOP MERGES, START MERGES, STOP TTL MERGES, START TTL MERGES, STOP FETCHES, START FETCHES, STOP MOVES, START MOVES, STOP REPLICATED SENDS, START REPLICATED SENDS, STOP REPLICATION QUEUES, START REPLICATION QUEUES, FLUSH LOGS, FLUSH DISTRIBUTED, STOP DISTRIBUTED SENDS, START DISTRIBUTED SENDS, START THREAD FUZZER, STOP THREAD FUZZER, END. (SYNTAX_ERROR) (version 21.12.3.32 (official build))

**Comment by zhicwu** [comment]
No I meant to query `system.query_log` or use `show processlist` on ClickHouse to see what's going on when PDI is stuck.

**Comment by deniztek** [comment]
I could not get the any significat result by using those command because program does not execute even I have just tried to select table. Hence, potential problem does not seen in the output.

**Comment by zhicwu** [comment]
Could you share the table structure if it's not senstive? Also what's the version of PDI you're using? 9.1? I'll try to reproduce the issue tomorrow.

**Comment by deniztek** [comment]
I'm currently using PDI version 9.2. 
You can find the detailed information about the data.
[clickhousehistv1.xlsx](https://github.com/ClickHouse/clickhouse-jdbc/files/7889206/clickhousehistv1.xlsx)

Thank you in advance ))))

**Comment by zhicwu** [comment]
Do you have the table creation DDL? I tried with a different table and it seems PDI issued a `select *` query, so maybe that's the reason. Also can you make sure the datasource is using `com.clickhouse.jdbc.ClickHouseDriver` as driver?

**Comment by deniztek** [comment]
I totally cannot execute when I load clickhouse database in table output. Curiously enough sometimes I could able to load clickhouse table in table input but executed so slowly (btw just load the smal data (500mb) fail to load big data (41gb))
I'm uploading clickhouse-jdbc-0.3.1-patch-shaded to the data integration/lib folder (attached in a file)
I'm little confused, what do you mean by saying table creation DDL. 
![clickhousee1](https://user-images.githubusercontent.com/97874273/150800374-b8bf93f4-6c37-4d22-947f-7d0d2aaff3e6.png)
thanks again for your help.

**Comment by deniztek** [comment]
Thank you, I'm waiting for your replay.

**Comment by deniztek** [comment]
hello is there any update?

**Comment by zhicwu** [comment]
> hello is there any update?

Sorry for getting back late on this. It didn't work, because the new driver had problem convert string to nested data types like array and tuple. Will fix this in patch4.

**Comment by deniztek** [comment]
Okey thank you very much. Also do you have any opinion about that issue (https://github.com/ClickHouse/clickhouse-odbc/issues/389) ? ODBC cannot bring the string codes which do not have fixed sizes; on the other hand, JDBC get bring those string codes correctly.

**Comment by zhicwu** [comment]
Sorry I forgot to mention that patch4 has been released. You may now download the driver from [here](https://github.com/ClickHouse/clickhouse-jdbc/releases/download/v0.3.2-patch4/clickhouse-jdbc-0.3.2-patch4-all.jar), put it under <pdi home>/lib directory, and delete the old driver in same directory. Lastly, when you create connection, please remember to use new driver `com.clickhouse.jdbc.ClickHouseDriver`.

I think it will still slow because PDI does not support stream, but please let me know how it goes.

**Comment by deniztek** [comment]
I am still getting not responding while trying to connect clickhouse table.
![clckhouse1](https://user-images.githubusercontent.com/97874273/153374757-ea67e570-9d39-43df-ad9f-001cd369b760.png)

**Comment by zhicwu** [comment]
I captured a `select * from <destination table>` query without any restriction of max rows from PDI, but I'm not sure how it was triggered.

Can you try to append `max_result_rows=7` in your connection string to verify? For example: `jdbc:ch://localhost/test` -> `jdbc:ch://localhost/test?max_result_rows=7`. This will limit all query results to 7 rows. It won't resolve your problem but it can be used to verify if the cause is on PDI.

**Comment by zhicwu** [comment]
Perhaps it's better to implement a plugin with custom datasource and steps(e.g. ClickHouse Table Input and Output) for PDI. However, it might not worthy of doing so because 1) Apache Nifi seems more popular; and 2) Apache Hop seems to be a successor of PDI.

**Comment by deniztek** [comment]
Hello, as you said I've tried to clickhouse input and output on the apache nifi program. However, I encountered some errors during to connecting the clickhouse. I've added DBCPConnection pool then in the configuration section I entered my clickhouse information but as you can see in the picture I got error in the database driver section. In order to solve this problem I compiled JDBC driver with maven but again I encountered an error. Do you have any idea/solution to handle this? Thank you
![apachenificlickhouse](https://user-images.githubusercontent.com/97874273/160837401-0bf14fa0-eb41-414e-a895-f06c772eb116.png)

**Comment by zhicwu** [comment]
@deniztek, the error message suggested you to check driver location. Perhaps you should remove `$NIFI_HOME/`?
