### ISSUE TITLE
are async inserts supported?

### ISSUE THREAD

**Issue by gauravphoenix** [ClickHouse/clickhouse-jdbc#820]
I can't seem to find a reference to `async_insert_mode` in the codebase. In this test, the config is set manually https://github.com/CurtizJ/ClickHouse/blob/f6191b98e74af57ae4ace34c21b269fedcf8ecbd/tests/queries/0_stateless/02015_async_inserts_4.sh#L7 so I am wondering if this jdbc client (when configured to use HTTP) supports async inserts or not

**Comment by zhicwu** [comment]
Please refer to below test case:

https://github.com/ClickHouse/clickhouse-jdbc/blob/c69c8a8c5a4c273beb3b61b940009072d7a4d85f/clickhouse-jdbc/src/test/java/com/clickhouse/jdbc/ClickHouseStatementTest.java#L124-L155

**Comment by gauravphoenix** [comment]
Thanks, that worked. I was trying something like that with BalancedClient but that didn't work but the example you gave just worked fine.

**Comment by zhicwu** [comment]
Good to know. If you want to use Java client for the same thing, you can try below one:

```java
// assume you're accessing the node using http protocol
ClickHouseRequest<?> request = client.connect(server);
try (ClickHouseResponse resp = request.set("async_insert", 1).set("wait_for_async_insert", 0).execute().get()) {
  ...
}
```
