### ISSUE TITLE
Does jdbc support HTTPS?

### ISSUE THREAD

**Issue by cantfu** [ClickHouse/clickhouse-jdbc#823]
Help want:

- Does clickhouse-jdbc support https connection?
- if not, do we have any solution?

**Comment by zhicwu** [comment]
Yes. Did you meet any issue?

**Comment by cantfu** [comment]
I hit this:
java.lang.RuntimeException: ru.yandex.clickhouse.except.ClickHouseUnknownException: ClickHouse exception, code: 1002, host: 21.112.108.209, port: 21422; sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

**Comment by cantfu** [comment]
I hit this:


java.lang.RuntimeException: ru.yandex.clickhouse.except.ClickHouseUnknownException: ClickHouse exception, code: 1002, host: xxx.xxx.xxx.xxx, port: 21422; sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

**Comment by zhicwu** [comment]
Not sure why you use old version of the driver. Did you set below connection setting?
```java
SSL_MODE("sslmode", "strict", "verify or not certificate: none (don't verify), strict (verify)"),
```
