### ISSUE TITLE
ClickHouseProperties.setKeepAliveTimeout(int keepAliveTimeout)

### ISSUE THREAD

**Issue by Nehoko** [ClickHouse/clickhouse-jdbc#831]
We're trying to update clickhouse-jdbc from 0.1.48 to 0.3.2-patch4 and faced with a problem: there is not method `setKeepAliveTimeout(int keepAliveTimeout)` which we was using.
Should we changed with something else? Or just remove it?

**Comment by zhicwu** [comment]
Yes, you can simply remove it as it's no longer required.
