### ISSUE TITLE
BalancedClickhouseDataSource; 负载均衡在0.3.2版本怎么支持以及后面版本怎么规划的的这个功能是？

### ISSUE THREAD

**Issue by kiwimg** [ClickHouse/clickhouse-jdbc#834]
ru.yandex.clickhouse.BalancedClickhouseDataSource; 负载均衡在0.3.2版本怎么支持以及后面版本怎么规划的的这个功能是？

**Comment by zhicwu** [comment]
> ru.yandex.clickhouse.BalancedClickhouseDataSource; 负载均衡在0.3.2版本怎么支持以及后面版本怎么规划的的这个功能是？

Since the driver uses http protocol by default, I'd suggest you using middleware like `chproxy`, `nginx` or `traefik` etc. for load balancing.

As to the driver itself, I hope to re-write `ClickHouseCluster` in 0.3.3, which will simplify the way to connect to multiple nodes, for example:
```java
// Java client
ClickHouseNode server1 = ClickHouseNode.of(...);
ClickHouseCluster cluster1 = ClickHouseCluster.of("cluster1", server1); // discover the rest nodes of cluster1
ClickHouseNodes nodes = ClickHouseNodes.of(server1, cluster1, ...); // list of nodes may or may not belong to a cluster

ClickHouseResponse resp = client.connect(nodes) // intention to connect to a node within the list
  .query("select 1")
  .execute() // pick one node from nodes and execute from there
  .get();

// JDBC driver will support multiple hosts(and protocols) in connection string like:
// jdbc:ch://ip1:port1,ip2:port2,.../database
```

**Comment by kiwimg** [comment]
thanks

**Comment by kiwimg** [comment]
现在 0.3.1 使用的 BalancedClickhouseDataSource。如果升级到 0.3.2版本， 怎么使用呢，对应的 BalancedClickhouseDataSource应该替换成什么？

**Comment by zhicwu** [comment]
Sorry I'll write a guide for upgrading legacy JDBC driver to new one.

> 如果升级到 0.3.2版本，对应的 BalancedClickhouseDataSource应该替换成什么？

As I mentioned [here](https://github.com/ClickHouse/clickhouse-jdbc/issues/904#issuecomment-1146907991), we'll only need to specify multiple hosts in connection string.

> 我理解 clickhouse-jdbc 、clickhouse-tcp-client、 clickhouse-http-client 这几个模块的作用，是不是 clickhouse-client 是一个通用的入口，然后指定不同协议就可以调用不同协议模块、

Correct. You may refer to the class diagram at [here](https://github.com/ClickHouse/clickhouse-jdbc/issues/570#issue-809823439). By the way, `clickhouse-cli-client` is available on develop branch. It implemented `clickhouse-client` interfaces like `clickhouse-http-client` and `clickhouse-grpc-client`, but it's actually a wrapper of ClickHouse native command line.
