### ISSUE TITLE
How to write data in bulk?

### ISSUE THREAD

**Issue by gauravphoenix** [ClickHouse/clickhouse-jdbc#843]
let's say I have a `byte[]` that represents a ClickHouse row in `RowBinary` format (we are reading it from a kafka consumer). What is the ideal way to insert data in CH in bulk using the HTTP client? 

Here is the Kafka read loop-
```java
  for (ConsumerRecord<String, byte[]> record : consumerRecords) {

       //byte[] is  a row of type RowBinary

     try {
          ClickHouseResponse clickHouseResponse = connection.createStatement().write().
              query("insert into data").
              format(ClickHouseFormat.RowBinary).
              data(new ByteArrayInputStream(record.value())).
              send().
              get();
        } catch (InterruptedException | ExecutionException | SQLException e) {
          e.printStackTrace();
        }


      }
```
This is obviously a bad idea to make inserts in a tight loop, but I can't seem to find an example how to do bulk inserts using the HTTP driver. 

I know I can handle it easily using JDBC batch interface but I am trying to avoid the serialization cost. The last time I tried JDBC I could see substantial time is spent in setting values of the prepared statements.

**Comment by zhicwu** [comment]
You can use `ClickHousePipedStream`, which is a single-producer to single-consumer piped stream. Basically, you write data on one side, and then read from the other side(usually in separate thread).

Serialization came with cost but I think it's affordable given the fact that you're using Kafka, meaning async and multiple consumers running in parallel, which should be faster enough? If you really need to minimize the overhead, perhaps you should consider Native format instead of RowBinary?

Below is the test case that I just added into integration test suite:
```java
@Test(groups = { "integration" })
public void testLoadRawData() throws Exception {
    ClickHouseNode server = getServer();
    ClickHouseClient.send(server, "drop table if exists test_load_raw_data",
            "create table test_load_raw_data(a Int64)engine=Memory").get();
    int rows = 10000000;

    try (ClickHouseClient client = getClient()) {
        ClickHouseRequest.Mutation request = client.connect(server).write()
                .table("test_load_raw_data")
                .format(ClickHouseFormat.RowBinary)
                // this is needed to get meaningful response summary
                .set("send_progress_in_http_headers", 1);
        ClickHouseConfig config = request.getConfig();

        CompletableFuture<ClickHouseResponse> future;
        // single producer → single consumer
        // important to close the stream *before* retrieving response
        try (ClickHousePipedStream stream = new ClickHousePipedStream(config.getMaxBufferSize(),
                config.getMaxQueuedRequests(), config.getSocketTimeout())) {
            // start the worker thread which transfer data from the input into ClickHouse
            future = request.data(stream.getInput()).send();
            // write bytes into the piped stream
            for (int i = 0; i < rows; i++) {
                BinaryStreamUtils.writeInt64(stream, i);
            }
        }

        ClickHouseResponseSummary summary;
        try (ClickHouseResponse response = future.get()) {
            summary = response.getSummary();
        }

        Assert.assertEquals(summary.getWrittenRows(), rows);
    }
}
```

Actually you can do the same thing using JDBC driver, although it's a little bit scary :p
```java
try (ClickHouseConnection conn = newConnection(new Properties());
        ClickHouseStatement stmt = conn.createStatement();
        PreparedStatement ps = conn.prepareStatement(
                // tt is short for temporary table
                "insert into test_jdbc_load_raw_data select * from {tt 'raw_data'}")) {
    Assert.assertFalse(stmt.execute("drop table if exists test_jdbc_load_raw_data; "
            + "create table test_jdbc_load_raw_data(s String)engine=Memory"), "Should not have result set");
    ClickHouseConfig config = stmt.getConfig();
    CompletableFuture<Integer> future;
    try (ClickHousePipedStream stream = new ClickHousePipedStream(config.getMaxBufferSize(),
            config.getMaxQueuedRequests(), config.getSocketTimeout())) {
        ps.setObject(1, ClickHouseExternalTable.builder().name("raw_data")
                .columns("s String").format(ClickHouseFormat.RowBinary)
                .content(stream.getInput()).build());
        future = CompletableFuture.supplyAsync(() -> {
            try {
                return ps.executeUpdate();
            } catch (SQLException e) {
                throw new CompletionException(e);
            }
        });

        // write bytes into the piped stream
        for (int i = 0; i < 101; i++) {
            BinaryStreamUtils.writeString(stream, Integer.toString(i));
        }
    }

    Assert.assertTrue(future.get() >= 0);
}
```

**Comment by gauravphoenix** [comment]
Thanks @zhicwu for great examples!

**Comment by gauravphoenix** [comment]
>perhaps you should consider Native format instead of RowBinary?

how do I go about using native format when using this client? (either JDBC or http/grpc?)

**Comment by zhicwu** [comment]
> how do I go about using native format when using this client? (either JDBC or http/grpc?)

Sorry for the late response. Native format is similar as RowBinary except it's organized by columns(actually blocks but similar). As of now, before v0.3.3 release, you have to use `BinaryStreamUtils` and extend its functionalities to support batch read/write(e.g. read multiple Int64 values from byte array), which could be tedious. What's more important, this requires changes not only in your Kafka consumers but also producers.

**Comment by gauravphoenix** [comment]
Are there plans of providing simpler ways to generate data in native format?

**Comment by zhicwu** [comment]
> Are there plans of providing simpler ways to generate data in native format?

In the `clickhouse-tcp-client` I'm working on, there'll be objects like `ClickHouseBlock` and `ClickHousePacket` etc. along with serialize and deserialize methods for this purpose. Once it's mature, I'm going to promote those classes to `clickhouse-client` so that we can use them in `clickhouse-http-client` as well.

**Comment by serega** [comment]
@zhicwu I am using your example to insert data in large batches (up to 100K rows, 40 columns. One column is  a big string).  Occasionally I get timeouts during writing data to the stream

```
for (int i = 0; i < rows; i++) {
     BinaryStreamUtils.writeInt64(stream, i);
}
```

In this case of a timeout I retry the whole batch.  As of now I haven't found a case where I found duplicate records, but I would still like to confirm if there is any notion of a transaction associated with `ClickHouseRequest.Mutation` and `ClickHouseResponse`. 
Can I assume that unless the following block of code succeeds no rows are written to the table?
```
try (ClickHouseResponse response = future.get()) {
            summary = response.getSummary();
}

```
