### ISSUE TITLE
Parse from Map(LowCardinality(?), ?)

### ISSUE THREAD

**Issue by AlexanderZavoykin** [ClickHouse/clickhouse-jdbc#846]
When a table has column of type Map with key type as LowCardinality, method _ClickHouseColumnInfo.parse(String typeInfo, String columnName, TimeZone serverTimeZone)_ does not work well, because _splitArgs(typeInfo, currIdx)_  (line ClickHouseColumnInfo::135) return one element array.

**Comment by zhicwu** [comment]
Thanks for reporting the issue. Looks like you're using legacy driver which is known having trouble to deal with nested types. I'd suggest you upgrade to latest driver and try again. FYI, below works for me:
```sql
drop table if exists test_lmap;
create table test_lmap(a Map(LowCardinality(String), Int32))engine=Memory;
insert into test_lmap values({ 'a' : 1 });
select * from test_lmap;
```

**Comment by AlexanderZavoykin** [comment]
Thank you for answer! I use the leatest version (0.3.2). Still getting the same problem when declaring some column as Map(LowCardinality(String),String).
I`m a little bit newbie in opening issues. So excuse me if the issue itself is not so informative as needed. Please, do ask me for any additional info.
Here is the screenshot. It seems that the closing bracket ")" still does not let to parse correctly the types of map key and value.
![image](https://user-images.githubusercontent.com/46527853/156123031-5934f8d8-a6da-4306-a88c-bc6cbbdd05f4.png)

**Comment by zhicwu** [comment]
> I use the leatest version (0.3.2). Still getting the same problem when declaring some column as Map(LowCardinality(String),String).

Please change maven groupId to `com.clickhouse`, the new version should be `0.3.2-patch5`. Also please use the new driver `com.clickhouse.jdbc.ClickHouseDriver`.
