### ISSUE TITLE
Unsupported data type: Bool

### ISSUE THREAD

**Issue by jnd77** [ClickHouse/clickhouse-jdbc#848]
Hi.

I noticed the method below does not handle the Bool type. Is there a reason, or is it an oversight ?

https://github.com/ClickHouse/clickhouse-jdbc/blob/3d921d444e7945859d674c736c2e3c3399ec6f02/clickhouse-client/src/main/java/com/clickhouse/client/ClickHouseValues.java#L950

Thanks.

**Comment by zhicwu** [comment]
Definitely oversight and thanks for pointing it out :) Will release patch6 in weekend to fix this.

**Comment by zhicwu** [comment]
Will release tomorrow after some more testing.
