### ISSUE TITLE
ClickHouse QueryID Issue

### ISSUE THREAD

**Issue by ltl0814** [ClickHouse/clickhouse-jdbc#870]
Hi , I have a scenario here , we need to get query ID before CH return result , because user don't know this query executed quickly or not , so we injected query ID by modifying the bytecode to override your queryID ,so that we can kill this query by accurate queryID,  but these days we upgrade CH to 0.3.2 ,we found that you have changed this code by this way(below image) , and this is a bit tricky to override queryID again. so could you please advise this for us ? and I think modify bytecode is not a good way to inject query ID....
![image](https://user-images.githubusercontent.com/42437316/158291679-446a4d77-6e5d-465b-919f-4630f2083761.png)

**Comment by zhicwu** [comment]
> we need to get query ID before CH return result

Perhaps you can call Statement.cancel() so that you don't have to know the query ID and kill the query manually?

**Comment by ltl0814** [comment]
emm... we don't use native jdbc(mybatis instead) , so it will be a little trouble to get statement . I mean that do we can find some ways to use my query ID not yours or give me some method to get your queryID so that I can kill query as I want ? : )

**Comment by zhicwu** [comment]
I see. Just did a quick search and it seems mybatis still does not support cancel.

Anyway, I think we need to enhance the driver to expose methods for setting/getting query id. Before that, I can only think of AOP to replace query id passed to Clickhouse request.query(sql, queryId).

**Comment by ltl0814** [comment]
good idea, thank you so much : )

**Comment by zhicwu** [comment]
I think there are a few issues requesting an interceptor and the ability to customize query id etc., I'll enhance the driver to expose an interface for this.

**Comment by zhicwu** [comment]
Starting from 0.3.2-patch11, you should be able to customize query ID and session ID by implementing ClickHouseRequestManager.

https://github.com/ClickHouse/clickhouse-jdbc/blob/27f8951cdc380bf1799f76efc21fc377fc6d5981/clickhouse-client/src/main/java/com/clickhouse/client/ClickHouseRequestManager.java#L16-L17

**Comment by lelewolf** [comment]
@ltl0814 Hello, I have a requirement similar to yours. I would like to ask how you use the query ID to cancel a query, and how effective it is in a distributed ClickHouse setup?

**Comment by ltl0814** [comment]
> @ltl0814 Hello, I have a requirement similar to yours. I would like to ask how you use the query ID to cancel a query, and how effective it is in a distributed ClickHouse setup?

sql : kill query where query_id = xxx  on cluster xxx
