### ISSUE TITLE
No more option to pass session_id

### ISSUE THREAD

**Issue by kassak** [ClickHouse/clickhouse-jdbc#871]
Since 0.3.2 there is no option to pass session_id to Driver.connect.
DataGrip actively uses it to provide interactive sessions.

That applies to `com.clickhouse.jdbc.ClickHouseDriver` for `ru*` everything is ok

**Comment by zhicwu** [comment]
Hi @kassak, you can set connection property `custom_http_params` to `session_id=mySessionId`, if you're not using gRPC, which is still experimental as of now.

My trial license has been expired, so I only tried on DBeaver.

**Comment by kassak** [comment]
Thanks!
Can we have it as driver property to match previous driver's interface?
Or compatibility is not addressed by the new driver?

**Comment by zhicwu** [comment]
I plan to add `custom_settings` in 0.3.3, so that nobody has to use above workaround, which is limited to http protocol. I think I can add `session_id` as well for backward compatibility, but maybe not all other properties in the legacy driver.
