### ISSUE TITLE
Writing in RowBinary

### ISSUE THREAD

**Issue by k3rnL** [ClickHouse/clickhouse-jdbc#875]
Hello,

I'm trying to implement a "Sink" in my application and I thought that the RowBinary format would be the fastest.

I simplified for now to write only 3 columns, but I don't understand why I get this error from CH:
```
Caused by: java.io.IOException: Code: 33, e.displayText() = DB::Exception: Cannot read all data. Bytes read: 0. Bytes expected: 1.: (at row 1)
 (version 21.8.11.4 (official build))
```
There is a hexdump of what I write with my program :
```
00000000: 494e 5345 5254 2049 4e54 4f20 7465 7374  INSERT INTO test
00000010: 5f71 7561 7274 6572 2046 4f52 4d41 5420  _quarter FORMAT
00000020: 526f 7742 696e 6172 790a 7b00 0000 0000  RowBinary.{.....
00000030: 0000 2419 145c c4e3 3900 6c34 9461 0a    ..$..\..9.l4.a.
```

If I dump the same data from the client I get this :
```
clickhouse-client -h ... -u ..--password ..--query "select toUInt64(123),toUInt64(16294506170423588),fromUnixTimestamp(1637102700) format RowBinary" | hexdump -C -v
00000000  7b 00 00 00 00 00 00 00  24 19 14 5c c4 e3 39 00  |{.......$..\..9.|
00000010  6c 34 94 61                                       |l4.a|
00000014
```
The difference I see are the "\n" (0x0A) in the generated POST body. Is this the issue ?

edit: I'm using the new API:
```
                request = client.connect(server)
                        .write()
                        .query("insert into " + table + " ("+columnList+") ")
                        .table(table)
                        .format(ClickHouseFormat.RowBinary)
                        .data(in)
                        .send();
```

**Comment by zhicwu** [comment]
Hi @k3rnL, could you share table DDL? If there's nullable column, you'll have to write a flag to indicate its value is null or not. Also you don't have to specify `table(table)` since you provided the query already.

**Comment by k3rnL** [comment]
How to precise which columns I want to write without .query() ? In this case I write all the columns, but in nominal usage it must be able to write few columns over the total available in a table

Yes, the doc was pretty clear about this, so I test if the column is nullable and write an extra byte in this case only. But I simplified the table to be sure I don't do any mistake with this.
There is the DLL : 
```
read = from.read(buffer)
create table test_quarter on cluster lo01
(
    _autoinc                                     UInt64,
    datetime                                     DateTime,
    ne                                           UInt64
)
     engine = Distributed('lo01', 'test_reinject', 'test_quarter_nd', ne);

create table test_quarter_nd on cluster lo01
(
    _autoinc                                     UInt64,
    datetime                                     DateTime,
    ne                                           UInt64
)
    engine = ReplicatedAggregatingMergeTree('/clickhouse/tables/{shard}/test_reinject/test_quarter', '{replica}')
        PARTITION BY toDate(datetime)
        ORDER BY (datetime, ne)
        SETTINGS index_granularity = 8192;

**Comment by zhicwu** [comment]
Sorry you have to use `.query("insert into <table>(<columns>)")` as of now, when you don't want to insert all columns. For your case, please remove `.table(table)` as it will override your query.

**Comment by k3rnL** [comment]
This solved my issue. Thanks a lot :)
