### ISSUE TITLE
DateTimeException when trying to parse Date objects into ClickHouseDateValue

### ISSUE THREAD

**Issue by PatrickTu** [ClickHouse/clickhouse-jdbc#876]
-----------

I am writing a service to ingest data into ClickHouse. I won't have the ability to modify the data type of each object prior to creating the `PreparedStatement`. As a result, to keep things generic, I am depending on `InputBasedPreparedStatement` to auto-resolve the data types by referencing the table's columns.

```java
...
preparedStatement.setObject(1, object);
...
```

There are cases where the upstream data source contains `java.util.Date` objects that get mapped to `com.clickhouse.client.data.ClickHouseDateValue` but results in an error when validating the time.

```java
Exception in thread "main" java.time.DateTimeException: Invalid value for EpochDay (valid values -365243219162 - 365241780471): 1488326400000
	at java.base/java.time.temporal.ValueRange.checkValidValue(ValueRange.java:312)
	at java.base/java.time.temporal.ChronoField.checkValidValue(ChronoField.java:717)
	at java.base/java.time.LocalDate.ofEpochDay(LocalDate.java:342)
	at com.clickhouse.client.data.ClickHouseDateValue.of(ClickHouseDateValue.java:56)
```

Code to reproduce the error above

```java
Date date = Date.from(Instant.now());
long time = date.getTime();
ClickHouseDateValue chdv = ClickHouseDateValue.of(time); // throws DateTimeException
```

----------------

Is there a way for me to override this behavior on my end? or should we work on creating a PR to make this method extensible?

```java
public ClickHouseDateValue update(long value) {
  this.set(LocalDate.ofEpochDay(value));
  return this;
}
```

**Comment by zhicwu** [comment]
Hi @PatrickTu, why not create an adaptor to convert legacy `java.util.Date` to recommended types like `java.time.LocalDate` or `java.time.LocalDateTime`?
