### ISSUE TITLE
How to use ClickHouseRowBinaryStream to write map?

### ISSUE THREAD

**Issue by gauravphoenix** [ClickHouse/clickhouse-jdbc#880]
I am using`ClickHouseRowBinaryStream` to write data like this 

```java
ByteArrayOutputStream byteArrayOutputStream = new ByteArrayOutputStream();
   ClickHouseRowBinaryStream stream = new ClickHouseRowBinaryStream(byteArrayOutputStream,
       TimeZone.getTimeZone(ZoneId.systemDefault()), new ClickHouseProperties());
   stream.writeString("foo");
   
```

there are no methods like `.writeMap`. How do I go about it?

**Comment by zhicwu** [comment]
Nested type like `Array`, `Tuple`, `Map` and `Object` etc. is a bit more complex than simple types. You may take [this](https://github.com/ClickHouse/clickhouse-jdbc/blob/3b0a353881349a4c3f7411c1ddfa62c4e7638dd7/clickhouse-client/src/main/java/com/clickhouse/client/data/ClickHouseRowBinaryProcessor.java#L380-L391) as an example to start with.

**Comment by gauravphoenix** [comment]
@zhicwu  thanks for the idea! I was able to make a simple map work like this- 

```java
ClickHouseMapValue chMapValue = ClickHouseMapValue.of(MYMAP, Integer.class, String.class);

ClickHouseRowBinaryProcessor.getMappedFunctions().serialize(chMapValue,
     new ClickHouseConfig(),
     ClickHouseColumn.of("my_map_column", "Map(Int32,String)")
     byteArrayOutputStream);
```
However, I can't make nested maps work. 
e.g. if I defined a Map like this in CH- 

`Map(Int32, Array(Tuple(String, Array(Int32))))`

and then try to serialize like this- 


```java
     ClickHouseMapValue chArrMapValue = ClickHouseMapValue.of(MY_NESTED_MAP, Integer.class, List.class);

      ClickHouseRowBinaryProcessor.getMappedFunctions().serialize(chArrMapValue,
          new ClickHouseConfig(),
          ClickHouseColumn.of("MY_NESTED_MAP", "Map(Int32, Array(Tuple(String, Array(Int32))))"),
          byteArrayOutputStream);

```

I do not get any errors, but when I query data in ClickHouse, instead of seeing the expected value, I see java memory references like this
```
 {2818:[('[I@6297a1b0',[]),('[I@5f4b22e9',[])],2819:[('[I@1ad991a8',[]),('[I@ec0b311',[])]}
```

Any suggestion on how to go about handling nested maps?

For debugging, I can see that when I call `chArrMapValue.toSqlExpression()` I see a perfectly valid SQL string. 
e.g. 
```
{2818 : ({'0.0.0.0' : [1,0]},{'0.0.0.1' : [2,0]}),2819 : ({'23' : [1,0]},{'22' : [2,0]})}
```

**Comment by zhicwu** [comment]
By default, ClickHouse data types are mapped to corresponding Java classes. For instances:
| ClickHouse Data Type | Java Class |
| ---------------------- | ---------- |
| Array                             | Object[] or primitive array like int[] |
| Tuple                             | List, usually immutable |
| Map                               | Map |
| Object/JSON                | List(because it's treated as Tuple with names and types) |

Note: Object/JSON will be supported starting from 0.3.2-patch8.

So `Map(Int32, Array(Tuple(String, Array(Int32))))` is mapped to something like `Map<Integer, List<?>[]>` in Java. Below code snippet demonstrates how to create such value in Java:
```java
Map<Integer, Object[]> nestedMap = new HashMap<>();
nestedMap.put(1, new List<?>[] {
    Arrays.asList("stringValue1", new int[] {1,2,3}),
    Arrays.asList("stringValue2", new int[] {4,5,6}),
    ...
});
...
```

> I do not get any errors, but when I query data in ClickHouse, instead of seeing the expected value, I see java memory references like this

What's the expected value? What you saw is Java objects representing the nested Map returned from ClickHouse.

> For debugging, I can see that when I call chArrMapValue.toSqlExpression() I see a perfectly valid SQL string

`toSqlExpression()` was primarily for building a SQL query, when you prefer SQL query(slow) over streaming.

**Comment by gauravphoenix** [comment]
Hi @zhicwu , 
when I query the table like `select * from table..\G` using the clichouse cli, I see something like this

```
map_array_column:      {2818:[('[I@91f2d03',[]),('[I@783e9af4',[])],2819:[('[I@1fcfd347',[]),('[I@47cc0519',[])]}
```

whereas the expected values are the real values e.g
```
{2818 : ({'0.0.0.0' : [1,0]},{'0.0.0.1' : [2,0]}),2819 : ({'23' : [1,0]},{'22' : [2,0]})}
```
here is how my map looks like

<img width="683" alt="image" src="https://user-images.githubusercontent.com/627662/159825712-0b49a4fb-89d8-4078-948e-e6d13911e3f7.png">

**Comment by gauravphoenix** [comment]
I think what's wrong here, the Tuple is expected to be a List but in my case, it is a Map, let me make some changes to see if that fixes it.

**Comment by zhicwu** [comment]
> I think I understand what's wrong here, the Tuple is expected to be a List but in my case, it is a Map, let me make some changes to see if that fixes it.

Yes, and `Array(Tuple(...))` should be mapped to `List<?>[]` not `List<Map<..>>`.

**Comment by zhicwu** [comment]
I have to admit the API should be improved as well. There are a few more features related on 0.3.3 branch, let me port some of the changes and get them merged into the upcoming patch release.
* `ClickHouseDataStreamFactory` will expose methods to get `ClickHouseSerializer` and `ClickHouseDeserializer` for given `ClickHouseFormat`
* `ClickHouseDataProcessor` will expose methods to read and write values
* Enhanced `ClickHouseInputStream` and `ClickHouseOutputStream` and new stream package

I'll also add some more examples and put them under examples/deser folder.
