### ISSUE TITLE
Problem with ClickHouseStreamCallback

### ISSUE THREAD

**Issue by Sidlight** [ClickHouse/clickhouse-jdbc#882]
We in the company use ClickHouseStreamCallback, from the package ru.yandex .clickhouse. Is it planned to transfer it, or is there an alternative?

**Comment by zhicwu** [comment]
There's no callback in new Client API but I can add it in the upcoming patch release. As of now, a workaround would be using `ClickHousePipedStream`, to write data on one side, and read from the other side.

**Comment by zhicwu** [comment]
`ClickHouseWriter` can be used in a similar way, please refer to [this](https://github.com/ClickHouse/clickhouse-jdbc/blob/f285b73d45597e29cf36dff4daf4cb4f9f53453a/clickhouse-client/src/test/java/com/clickhouse/client/ClientIntegrationTest.java#L1131-L1163).
