### ISSUE TITLE
mybatis deserialize  Map(String, Array (Nullable (DateTime64(3))) )  failed

### ISSUE THREAD

**Issue by YoKv** [ClickHouse/clickhouse-jdbc#886]
version: clickhouse-jdbc 0.3.2-patch7

```
CREATE TABLE data
(
    SIGN    Int8,
    VERSION UInt8,
    `DATE`  Map(String, Array (Nullable (DateTime64 (3))) ),
    pid     UInt64
) ENGINE = VersionedCollapsingMergeTree(SIGN, VERSION)
        ORDER BY (pid);

select data.DATE as "4ee9b4e9"
from data
where pid= 1432972998438363138;

i found BinaryStreamUtils.readNull  adn call  readBoolean(input)      thrown exception   

### Cause: java.sql.SQLException: Error
; uncategorized SQLException; SQL state [null]; error code [0]; Error

```
![foo](https://user-images.githubusercontent.com/15179941/161019048-92b61103-460d-4691-8f40-7a2220f5a2e9.jpg)

![debug](https://user-images.githubusercontent.com/15179941/161019059-9adc8281-3773-4b4c-be1a-398b81411364.jpg)

**Comment by zhicwu** [comment]
@YoKv, could you share a simple Java program using mybatis to reproduce the issue? It works fine at my end. As you can tell from below example, `Map(String, Array (Nullable (DateTime64 (3))) )` is mapped to `Map<String, LocalDateTime[]>` in Java - I'm not sure how mybatis handle that, but in general JDBC client should use `ResultSet.getObject()` to retrieve complex value and unwrap as needed.

```java
try (ClickHouseConnection conn = newConnection(new Properties());
        Statement stmt = conn.createStatement()) {
    stmt.execute("drop table if exists test_map_of_array; "
            + "create table test_map_of_array(id Int8, m Map(String, Array(Nullable(DateTime64(3))))) ENGINE = Memory; "
            + "insert into test_map_of_array values(1, { 'a' : [], 'b' : [ '2022-03-30 00:00:00.123', null ] })");
    ResultSet rs = stmt
            .executeQuery(
                    "select * from test_map_of_array order by id");
    Assert.assertTrue(rs.next());
    Assert.assertEquals(rs.getInt(1), 1);
    Map<?, ?> v = rs.getObject(2, Map.class);
    Assert.assertEquals(v.size(), 2);
    Assert.assertEquals(v.get("a"), new LocalDateTime[0]);
    Assert.assertEquals(v.get("b"),
            new LocalDateTime[] { ClickHouseDateTimeValue.ofNull(3, TimeZone.getDefault())
                    .update("2022-03-30 00:00:00.123").getValue(), null });
    Assert.assertFalse(rs.next());
}
```

**Comment by YoKv** [comment]
> @YoKv, could you share a simple Java program using mybatis to reproduce the issue? It works fine at my end. As you can tell from below example, `Map(String, Array (Nullable (DateTime64 (3))) )` is mapped to `Map<String, LocalDateTime[]>` in Java - I'm not sure how mybatis handle that, but in general JDBC client should use `ResultSet.getObject()` to retrieve complex value and unwrap as needed.
> 
> ```java
> try (ClickHouseConnection conn = newConnection(new Properties());
>         Statement stmt = conn.createStatement()) {
>     stmt.execute("drop table if exists test_map_of_array; "
>             + "create table test_map_of_array(id Int8, m Map(String, Array(Nullable(DateTime64(3))))) ENGINE = Memory; "
>             + "insert into test_map_of_array values(1, { 'a' : [], 'b' : [ '2022-03-30 00:00:00.123', null ] })");
>     ResultSet rs = stmt
>             .executeQuery(
>                     "select * from test_map_of_array order by id");
>     Assert.assertTrue(rs.next());
>     Assert.assertEquals(rs.getInt(1), 1);
>     Map<?, ?> v = rs.getObject(2, Map.class);
>     Assert.assertEquals(v.size(), 2);
>     Assert.assertEquals(v.get("a"), new LocalDateTime[0]);
>     Assert.assertEquals(v.get("b"),
>             new LocalDateTime[] { ClickHouseDateTimeValue.ofNull(3, TimeZone.getDefault())
>                     .update("2022-03-30 00:00:00.123").getValue(), null });
>     Assert.assertFalse(rs.next());
> }
> ```

okey

**Comment by YoKv** [comment]
https://github.com/YoKv/clickhouse-mybatis

i found  `    DATE   Map(String, Array (Nullable (DateTime64 (3, 'Asia/Shanghai'))) ) ` throw exception
but '    `DATE`   Map(String, Array (Nullable (DateTime64 (3))) )' not

**Comment by zhicwu** [comment]
Thnaks @YoKv. I can reproduce the issue and will fix it in weekend.
