### ISSUE TITLE
Localdatetime always  uses the server time zone

### ISSUE THREAD

**Issue by 779833371** [ClickHouse/clickhouse-jdbc#888]
clickhouse-jdbc version 0.3.1
clickhouse fieldtype : Nullable(DateTime)
clickhouse timezone:Asia/Shanghai
![46e4ee36e47961ed3ccac1c10d0518de](https://user-images.githubusercontent.com/30337595/161260827-f41895a6-64d7-4b74-a32c-d6b626f8f7eb.png)

the java entity type is LocalDateTime

now ,i  hava a record from clickhouse and the value is field start_time 2022-03-31 19:31:15, I use mybatis-pius to query the data.
but the java entity result is 2022-03-31 11:31:15,I track the code and found the value is changed in ru.yandex.clickhouse.response.parser.ClickHouseDateValueParser.dateTimeToLocalDateTime()

![ea8f9d13b1ce4ec33dd816bc8b4bca24](https://user-images.githubusercontent.com/30337595/161262222-56e92cd3-0b13-46ba-b3fe-875ee670c2d2.png)

and then return 2022-03-31 11:31:15.

![image](https://user-images.githubusercontent.com/30337595/161262578-b3e9a4c1-0364-4931-a3fa-e6bac0fedf3f.png)

I found the  columnInfo.getTimeZone() is afferent by ru.yandex.clickhouse.response.ClickHouseResultSet.

![8469a853efebbd3e8189ef6165065da4](https://user-images.githubusercontent.com/30337595/161263765-e8fff1d6-abee-45ca-9fb0-0231825ff131.png)

in ClickHOuseResultSet.java ,TimeZone is from  ((ClickHouseConnection)statement.getConnection()).getServerTimeZone();
I found the serverTimeZone field init in ru.yandex.clickhouse.ClickHouseConnectionImpl. initConnection
![c2b00e0fa3ee1124e3c8c92d14578b57](https://user-images.githubusercontent.com/30337595/161264573-30ba9c46-37b4-447e-85cc-43463405eb41.png)

so ,the serverTimeZone is equals clickhouse timezone , both are Asia/Shanghai.

In my app,I only want to query the fieldValue equals  clickhouse value,both are 2022-03-31 19:31:15,I dont know why  ClickHouseDateValueParser.dateTimeToLocalDateTime() trans the value to UTC time.

if this problem open in mysql ,i can add the serverTimezone=Asia/Shanghai after the connect url ,but clickhouse not have this connetcion param,i use the use_server_time_zone to the url but not use.

what should i do?

**Comment by zhicwu** [comment]
Hi @779833371, is there any specific reason of using legacy driver? If not, I'd strongly suggest you to upgrade to 0.3.2, which is a complete rewrite with improved timezone support. In addition, it is recommended to use LocalDateTime/OffsetDateTime etc instead of java.sql.Timestamp.

**Comment by 779833371** [comment]
> Hi @779833371, is there any specific reason of using legacy driver? If not, I'd strongly suggest you to upgrade to 0.3.2, which is a complete rewrite with improved timezone support. In addition, it is recommended to use LocalDateTime/OffsetDateTime etc instead of java.sql.Timestamp.


my java entity is used LocalDateTime not Timestamp, I upgrade to upgrade to 0.3.2 ,but useless

**Comment by zhicwu** [comment]
> my java entity is used LocalDateTime not Timestamp, I upgrade to upgrade to 0.3.2 ,but useless

You need to use the new driver `com.clickhouse.jdbc.ClickHouseDriver` or it won't change. Everything under `ru.yandex` will be removed.

**Comment by 779833371** [comment]
> 

i switch driver to com.clickhouse.jdbc.ClickHouseDriver but also useless 
![image](https://user-images.githubusercontent.com/30337595/161366859-f394eb82-0538-45f8-a3c8-f30f13813ea0.png)
i want to know why the value trans to UTC time in there, i track the code ,found  before call this method,value is 2022-03-31 19:31:15 ,equals database value,but my serverTimeZone is  Asia/Shanghai,and enter the if branch,so the value are changed to  2022-03-31 11:31:15

**Comment by 779833371** [comment]
> > my java entity is used LocalDateTime not Timestamp, I upgrade to upgrade to 0.3.2 ,but useless
> 
> You need to use the new driver `com.clickhouse.jdbc.ClickHouseDriver` or it won't change. Everything under `ru.yandex` will be removed.
> 
> And please refer to [this](https://github.com/ClickHouse/clickhouse-jdbc/blob/3b0a353881349a4c3f7411c1ddfa62c4e7638dd7/clickhouse-jdbc/src/test/java/com/clickhouse/jdbc/ClickHouseStatementTest.java#L511) and [this](https://github.com/ClickHouse/clickhouse-jdbc/blob/3b0a353881349a4c3f7411c1ddfa62c4e7638dd7/clickhouse-jdbc/src/test/java/com/clickhouse/jdbc/ClickHouseStatementTest.java#L622) for more information.

**Comment by 779833371** [comment]
I am sorry ,i only switch the driver-class-name but not upgeade pom.xml,  i use group id com.clickhouse an upgeade to 0.3.2,and the problem are resloved,thanks!
<dependency>
            <groupId>com.clickhouse</groupId>
            <artifactId>clickhouse-jdbc</artifactId>
            <version>0.3.2</version>
        </dependency>

**Comment by zhicwu** [comment]
Good to know. The latest version is 0.3.2-patch7, and patch8 will be released soon.

In case anyone else ran into similar issue, please refer to examples above and #623.
