### ISSUE TITLE
ClickHouseColumn bug when parsing a tuple type

### ISSUE THREAD

**Issue by jnd77** [ClickHouse/clickhouse-jdbc#889]
Hi.
There is a bug or unexpected behavior in ClickHouseColumn when parsing a tuple type:

`ClickHouseColumn.parse("col_name Tuple(s String, i Int64)")` is throwing the following exception:

```
java.lang.IllegalArgumentException: Unknown data type: s String
```

My use case retrieves the types with a `DESCRIBE TABLE` query and parsing them via `ClickHouseColumn.parse`.

**Comment by zhicwu** [comment]
Thanks @jnd77, I'm aware of this. Actually it's been fixed in my local in order to support Object/JSON data type.

**Comment by jnd77** [comment]
Ok great. :)

**Comment by zhicwu** [comment]
`ClickHouseColumn` was enhanced to support both `Object(a String, i Int64)` and `Tuple(a String, i Int64)`. However, as mentioned in ClickHouse/ClickHouse#35461, ClickHouse server will only return the latter even the column is defined as `Object('JSON')`.

**Comment by zhicwu** [comment]
Looks like still have issue :<

```sql
-- not working
select tuple(1)::Tuple(i Int32)

-- workaround(longer field name)
select tuple(1)::Tuple(i1 Int32)
```
