### ISSUE TITLE
How to connect to TLS enabled ClickHouse?

### ISSUE THREAD

**Issue by rajjat0602** [ClickHouse/clickhouse-jdbc#897]
I am having three file tls.crt , tls.key and ca.crt which are needed to connect to ClickHouse but i couldn't find and client or driver that accept these parameter to establish the connection with clickhouse in spring boot.

**Comment by zhicwu** [comment]
Turns out it was not fully implemented 😅 Just made it work and added a test for regression. Will release together 0.3.2-patch8.

**Comment by zhicwu** [comment]
Please refer to more information at [here](https://github.com/ClickHouse/clickhouse-jdbc/issues/523#issuecomment-1100788627).
