### ISSUE TITLE
ClickHouseValueFormatter#formatTimestamp will ignore millisencods

### ISSUE THREAD

**Issue by cofcool** [ClickHouse/clickhouse-jdbc#898]
When Timestamp type data as the sql parameter, ClickHouseValueFormatter.javaformatTimestamp 
```java
    public static String formatTimestamp(Timestamp time, TimeZone timeZone) {
        SimpleDateFormat formatter = getDateTimeFormat();
        formatter.setTimeZone(timeZone);
        StringBuilder formatted = new StringBuilder(formatter.format(time));
        // TODO implement a true prepared statement to format according to parameter type
        if (time != null && time.getNanos() % 1000000 > 0) {
            formatted.append('.').append(time.getNanos());
        }
        return formatted.toString();
    }
```

`time.getNanos() % 1000000 > 0` only get Micros and Nanos, is this correct?

**Comment by zhicwu** [comment]
Hi @cofcool, the legacy driver has problem dealing with timestamp and timezone along with stability issue. Have you tried to upgrade to new driver(more details in #608)?

> Maven groupId `ru.yandex.clickhouse` and legacy JDBC driver `ru.yandex.clickhouse.ClickHouseDriver` are deprecated.
> Please use new groupId `com.clickhouse` and driver `com.clickhouse.jdbc.ClickHouseDriver` instead. It's highly recommended to upgrade to 0.3.2+ and start to integrate the new JDBC driver for improved performance and stability.

**Comment by cofcool** [comment]
Thank you, upgrade to new version solved my problem👍

**Comment by zhicwu** [comment]
> Thank you, upgrade to new version solved my problem👍

Good to know. Please be aware that the new driver is NOT a drop-in replacement, because it's a complete re-write and the serialization/deserialization format was changed from TabSeparated to RowBinary, so you might want to do some more testing on staging environment.

**Comment by cofcool** [comment]
Ok, I should do more test, thank you for the replay, ClickHouse is so great.
