### ISSUE TITLE
How to upgrade 0.31 to 0.32?

### ISSUE THREAD

**Issue by kiwimg** [ClickHouse/clickhouse-jdbc#904]
How to upgrade 0.31 to 0.32?
Alibaba's Druid is used as the JDBC pool,

**Comment by zhicwu** [comment]
If you're using standard JDBC API, in general you only need to use the new driver class `com.clickhouse.jdbc.ClickHouseDriver`, which is actually the default.

I'm not familiar with Druid, but as long as the connection pool is not tightly coupled with legacy driver, the upgrade should be transparent in most cases.

**Comment by kiwimg** [comment]
0.3.1 use the driver: ru.yandex.clickhouse.ClickHouseDriver, Alibaba's Druid  source use ru.yandex.clickhouse.BalancedClickhouseDataSource

**Comment by zhicwu** [comment]
> 0.3.1 use the driver: ru.yandex.clickhouse.ClickHouseDriver, Alibaba's Druid source use ru.yandex.clickhouse.BalancedClickhouseDataSource

Sorry there's no `BalancedClickhouseDataSource` in the new JDBC driver. Starting from 0.3.2-patch10, you'll be able to specify multiple hosts in connection string, for examples:
* `jdbc:ch://(http://localhost),(tcp://localhost),(grpc://localhost)/test?connect_timeout=500&!auto_discovery&load_balancing_policy=FIRST_ALIVE&health_check_interval=15000`
* or `jdbc:ch:http://host1,(host3?auto_discovery&discovery_interval=60000&cluster=mine),(host5)/test?load_balancing_policy=ROUND_ROBIN&health_check_interval=15000`(host3 is the seed to discover all other nodes in cluster `mine` for load balancing).

I'm still adding more tests and have completed performance testing, so the release was deferred to next weekend.
