### ISSUE TITLE
Error with Prepared statement in Spark: ArrayIndexOutOfBoundsException : 0

### ISSUE THREAD

**Issue by shahsiddharth08** [ClickHouse/clickhouse-jdbc#907]
I am trying to read parquet files from GCS and writing the DataFrame in CH using clickhouse-jdbc driver. My code is working fine the 3rd option using PreparedStatement mentioned [here](https://github.com/ClickHouse/clickhouse-jdbc/tree/master/clickhouse-jdbc). However, when I use the recommended alternative (1st option using `INPUT` statement it fails with following error
```
java.lang.ArrayIndexOutOfBoundsException: 0
```

Code:

```
val stmt = conn.prepareStatement( "INSERT INTO test_database.test_lite SELECT oid, ts, cid, pid FROM INPUT('oid UInt32, ts DateTime, cid UInt32, pid String') FORMAT TabSeparatedWithNamesAndTypes")
          stmt.setLong(1, 101855018)
          stmt.setLong(2, 1609718400000L)
          stmt.setLong(3, 415265232)
          stmt.setString(4, "ddccc35e6dddf1d5b22b8ae1cfd87141cde1adae")

          stmt.addBatch()
val res = stmt.executeBatch()
```

Using Spark with Scala
Driver
```
<groupId>com.clickhouse</groupId>
<artifactId>clickhouse-jdbc</artifactId>
<version>0.3.2</version>
```

**Comment by zhicwu** [comment]
Hi @shahsiddharth08, could you try again by removing `FORMAT TabSeparatedWithNamesAndTypes` in your query? Besides, if you upgrade the driver the latest version `0.3.2-patch8`, `INSERT INTO test_database.test_lite` should work as well, but the difference is that the driver will issue a query `select * from test_database.test_lite where 0` for schema inferring before insertion.

**Comment by shahsiddharth08** [comment]
Able to make inserts using PreparedStatement but now I am getting TOO many parts exception. Closing this for now and will create a new question for the issue I am facing now.
