### ISSUE TITLE
about  use date  or localtime  to compare

### ISSUE THREAD

**Issue by SurelySomeday** [ClickHouse/clickhouse-jdbc#908]
```
        <dependency>
            <groupId>com.clickhouse</groupId>
            <artifactId>clickhouse-jdbc</artifactId>
            <version>0.3.2-patch8</version>
        </dependency>
```
```
When using 'Date' or 'LocalDatetime' to compare (yyyy-MM-dd hh:mm:ss:SSS), an exception occurs. 
But if the date is not accurate to milliseconds (yyyy-MM-dd hh:mm:ss) it is normal. 
You can use sql tests like 'select * from a where a.create_time>?'

```

**Comment by SurelySomeday** [comment]
Hi @zhicwu  , thank you for your reply.
I use the mybatis framework to manipulate clickhouses, and using 'setString' is not a great solution. I locate the mybatis source code, and actually mybatis already knows the type of the parameter and uses 'LocalDateTimeTypeHandler' to process it. So I tried to override 'LocalDateTimeTypeHandler' in my project, and when I called 'setObject', I removed the milliseconds of 'LocalDateTime', which was valid.
![image](https://user-images.githubusercontent.com/32257480/165771989-80585978-6bd9-4f1b-a54c-e08964a5a5fa.png)

The error in use is the same as the following scenario.
```
select now()>'2022-03-01 00:00:00'; //ok
select now()>'2022-03-01 00:00:00:000';  //Code: 53. DB::Exception: Cannot convert string 2022-03-01 00:00:00:000 to type DateTime: While processing now() > '2022-03-01 00:00:00:000'. (TYPE_MISMATCH)
```

**Comment by zhicwu** [comment]
@SurelySomeday, actually the driver will convert the value to String in this case, so it does not make much difference regardless you use setObject or setString :p

If you prefer to set value as binary(in RowBinary format), you can check [this](https://github.com/ClickHouse/clickhouse-jdbc/blob/f9f9683f5dd914f9f7785499478ab7c50307a677/clickhouse-jdbc/src/test/java/com/clickhouse/jdbc/ClickHousePreparedStatementTest.java#L906-L917) example but it's not a portable solution.

**Comment by yurifal** [comment]
I could be missing something obvious, but will this work? 
`select now()>'2022-03-01 00:00:00.000';`

**Comment by SurelySomeday** [comment]
@zhicwu First of all, thank you very much for replying to me in your busy schedule. I looked at mysql's jdbc code and they did a lot of judgment processing in 'setObject'. Our project, which originally used mysql, is currently moving to Clickhouse, so we found a lot of differences from mysql, but there are also many parts that are compatible without refactoring the code. In mysql jdbc, a lot of judgment is done on 'setObject' so he can handle the date problem. Please ask clickhouse-jdbc if it can learn from this approach, or whether there are any plans to support the processing of date.
![image](https://user-images.githubusercontent.com/32257480/165788725-d4e73a0e-8dd5-4770-bead-742cc53c57e9.png)
![image](https://user-images.githubusercontent.com/32257480/165789176-86cdd520-2537-4175-984c-06fb8757c8ec.png)
```
public void setLocalDateTime(int parameterIndex, LocalDateTime x, MysqlType targetMysqlType) {
        if (targetMysqlType == MysqlType.DATE) {
            this.setValue(parameterIndex, "'" + x.toLocalDate() + "'", MysqlType.DATE);
        } else {
            int fractLen = 6;
            if (this.columnDefinition != null && parameterIndex <= this.columnDefinition.getFields().length && parameterIndex >= 0) {
                fractLen = this.columnDefinition.getFields()[parameterIndex].getDecimals();
            }

            if ((Boolean)this.sendFractionalSeconds.getValue() && this.session.getServerSession().getCapabilities().serverSupportsFracSecs()) {
                x = TimeUtil.adjustNanosPrecision(x, fractLen, !this.session.getServerSession().isServerTruncatesFracSecs());
            } else {
                x = x.withNano(0);
            }

            StringBuilder sb;
            switch(targetMysqlType) {
            case TIME:
                sb = new StringBuilder("'");
                sb.append(x.toLocalTime().toString());
                if (sb.length() < 7) {
                    sb.append(":00");
                }

                sb.append("'");
                this.setValue(parameterIndex, sb.toString(), targetMysqlType);
                break;
            case DATETIME:
            case TIMESTAMP:
                sb = new StringBuilder("'");
                sb.append(x.toLocalDate());
                sb.append(" ");
                sb.append(x.toLocalTime().toString());
                if (sb.length() < 18) {
                    sb.append(":00");
                }

                sb.append("'");
                this.setValue(parameterIndex, sb.toString(), targetMysqlType);
            }
        }

    }
```

**Comment by zhicwu** [comment]
Thanks for the suggestion @SurelySomeday. Let me explain this in detail.

Unlike MySQL, ClickHouse has two datetime types for different precision: 4-byte `DateTime32` and 8-byte `DateTime64`. `DateTime` is an alias which can be mapped to any of the two depending on arguments you passed. In addition, ClickHouse does not support `PreparedStatement`, which means ClickHouse client has no way to infer data type except 1) parsing column definition like `a Int32, b LowCardinality(String)` ,or 2) issue a select query to get type returned from server. Lastly, client has to send substituted query(e.g. `select ?` -> `select 'value'`) to server for execution.

Getting back to your query `select * from a where create_time>?`, since it's difficult for JDBC driver to figure out what's the exact data type for the parameter, it has to guess based on your input - it's still hard to tell which one should use, so it went with the default one, which is DateTime64.

Actually, in new version of ClickHouse, datetime has been handled in a better way, at least below works well in 21.8 and 22.3:
```sql
create table a(t DateTime64(3))engine=Memory;
insert into a values('2022-04-29 12:34:56.789');
select * from a where t > '2022-04-29 00:00:00';
select * from a where t > '2022-04-29 00:00:00'::DateTime32;
select * from a where t > '2022-04-29 00:00:00'::DateTime64;
select * from a where t > '2022-04-29 00:00:00.123';
select * from a where t > '2022-04-29 00:00:00.123':DateTime64;
```

**Comment by SurelySomeday** [comment]
@zhicwu 
Thank you for your patience, from your reply I have a new understanding of clickhouse, for my needs I think I have a more perfect solution. Modify the 'datetime' type in the database to 'datetime64' so that it can be used normally. Finally, thank you sincerely.
