### ISSUE TITLE
NoClassDefFoundError: com/clickhouse/client/config/ClickHouseOption

### ISSUE THREAD

**Issue by Aload** [ClickHouse/clickhouse-jdbc#911]
It worked fine when I used Clickhouse-JDBC to run locally, but started reporting an error when the package went into the cluster.  I also added the ClickHouse-JDBC JAR to the Spark jars directory.  

env：
spark3.1.2
clickhouse-jdbc 0.3.2-patch8

![image](https://user-images.githubusercontent.com/13082598/165896335-e0d9f558-5627-47b0-ad11-654f71a80cbd.png)
![image](https://user-images.githubusercontent.com/13082598/165896446-ff70987c-82ed-4416-8398-210cddf2d56f.png)

**Comment by zhicwu** [comment]
Hi @Aload, it looks you did deploy all dependencies. Please use a shaded jar, the one with suffix like [clickhouse-jdbc-0.3.2-patch8-http.jar](https://github.com/ClickHouse/clickhouse-jdbc/releases/download/v0.3.2-patch8/clickhouse-jdbc-0.3.2-patch8-http.jar) or `-all` instead.

**Comment by Aload** [comment]
> Hi @Aload, it looks you did deploy all dependencies. Please use a shaded jar, the one with suffix like [clickhouse-jdbc-0.3.2-patch8-http.jar](https://github.com/ClickHouse/clickhouse-jdbc/releases/download/v0.3.2-patch8/clickhouse-jdbc-0.3.2-patch8-http.jar) or `-all` instead.

So I don't think there's a bag? The same problem occurs when I use both. 0.3.2-Patch8, Clickhouse-HTTP-client  
![image](https://user-images.githubusercontent.com/13082598/165934775-a053f8f6-d3dd-4ebc-8a53-f336f9def8a2.png)

![image](https://user-images.githubusercontent.com/13082598/165934721-12a4b5d1-f209-4a88-b898-141298d5ab5e.png)

**Comment by zhicwu** [comment]
Sorry I meant you did NOT deploy all dependencies. In order to use shaded jar in maven, you need to specify classifier, for example:

```xml
<dependency>
    <!-- will stop using ru.yandex.clickhouse starting from 0.4.0  -->
    <groupId>com.clickhouse</groupId>
    <artifactId>clickhouse-jdbc</artifactId>
    <version>0.3.2-patch8</version>
    <!-- below is only needed when all you want is a shaded jar -->
    <classifier>http</classifier>
    <exclusions>
        <exclusion>
            <groupId>*</groupId>
            <artifactId>*</artifactId>
        </exclusion>
    </exclusions>
</dependency>
```

**Comment by Aload** [comment]
> Sorry I meant you did NOT deploy all dependencies. In order to use shaded jar in maven, you need to specify classifier, for example:
> 
> ```
> <dependency>
>     
>     <groupId>com.clickhouse</groupId>
>     <artifactId>clickhouse-jdbc</artifactId>
>     <version>0.3.2-patch8</version>
>     
>     <classifier>http</classifier>
>     <exclusions>
>         <exclusion>
>             <groupId>*</groupId>
>             <artifactId>*</artifactId>
>         </exclusion>
>     </exclusions>
> </dependency>
> ```

Sorry, I don't quite catch your meaning.  I have also joined your POM.  It doesn't really make a difference  .

`<dependency>
    
    <groupId>com.clickhouse</groupId>
    <artifactId>clickhouse-jdbc</artifactId>
    <version>0.3.2-patch8</version>
    
    <classifier>http</classifier>
    <exclusions>
        <exclusion>
            <groupId>*</groupId>
            <artifactId>*</artifactId>
        </exclusion>
    </exclusions>
</dependency>`

**Comment by zhilinli123** [comment]
@zhicwu @Aload May I ask how to solve the problem at last?

**Comment by Aload** [comment]
> 

     <dependency>
                <groupId>com.clickhouse</groupId>
                <artifactId>clickhouse-jdbc</artifactId>
                <classifier>http</classifier>
                <version>0.3.2-patch7</version>
                <exclusions>
                    <exclusion>
                        <groupId>*</groupId>
                        <artifactId>*</artifactId>
                    </exclusion>
                </exclusions>
            </dependency>

**Comment by gulldan** [comment]
I have the same problem in pyspark
java.lang.NoClassDefFoundError: com/clickhouse/client/config/ClickHouseOption

env :
1) sparkConf.set('spark.jars.packages',
'com.github.housepower:clickhouse-spark-runtime-3.3_2.12:0.5.0,com.clickhouse:clickhouse-jdbc:0.4.0')
2) spark 3.3.1

**Comment by zhicwu** [comment]
> com.clickhouse:clickhouse-jdbc:0.4.0

It looks like you missed the classifier `all` or `http` as shown in above.

**Comment by gulldan** [comment]
> > com.clickhouse:clickhouse-jdbc:0.4.0
> 
> It looks like you missed the classifier `all` or `http` as shown in above.

sorry im using pyspark and not familiar with java stack.
i dont understand how to use POM.

also i can find -all / -http in maven 
https://repo1.maven.org/maven2/com/clickhouse/clickhouse-jdbc/0.4.0/clickhouse-jdbc-0.4.0-all.jar

but as i understand spark has spark.jars.ivySettings but ivy2 doesn't support classifier.

https://spark.apache.org/docs/latest/configuration.html

I tried to download and send it directly by adding 

sparkConf.set('spark.jars', 'http://local-repo/bins/clickhouse-jdbc-0.4.0-all.jar')  

but there is no changes 

`java.lang.NoClassDefFoundError: com/clickhouse/client/config/ClickHouseOption
`

Could you give me some advices?

**Comment by TheHett** [comment]
Help for gradle 
```
    // https://mvnrepository.com/artifact/com.clickhouse/clickhouse-jdbc
    implementation("com.clickhouse:clickhouse-jdbc:0.4.1:all")
```

**Comment by ivan-klass** [comment]
sbt:
```scala
("com.clickhouse" % "clickhouse-jdbc" % "0.4.1" classifier "all") % "runtime"
```
