### ISSUE TITLE
Question about the field names returned after the query

### ISSUE THREAD

**Issue by SurelySomeday** [ClickHouse/clickhouse-jdbc#912]
Hello, I have another question to ask.
When I use jdbc, I found that using something like 'select t.name, t.sex from table t', jdbc will return 't.name' as the field name, which will cause it to fail to map to the correct field. 
While adding 't.name as name' solves this problem, I'm designing the field 't.name' to be reduced to 'name'. Below is a comparison graph that I cut out from mysql-jdbc and clickhouse-jdbc.
#### in clickhouse
![image](https://user-images.githubusercontent.com/32257480/165951698-bdbd0887-8c0e-4364-af76-1f1e41eef77b.png)

#### in mysql
![image](https://user-images.githubusercontent.com/32257480/165953846-758e790d-cf5b-4320-a9e5-edf1771d5def.png)

**Comment by zhicwu** [comment]
New client option `rename_response_column` was added. It defaults to `NONE` for backward compatibility, but you can change it to `REMOVE_PREFIX` in order to remove prefix from response column names.
