### ISSUE TITLE
The 'getBigDecimal' method has a precision of 0 by default

### ISSUE THREAD

**Issue by SurelySomeday** [ClickHouse/clickhouse-jdbc#913]
When using a 'getBigDecimal' query, the 'ClickHouse DoubleValue' is returned, but when converting to 'BigDecimal', use 'scale=0' directly, which will result in a loss of precision. 
Although there is such a way as 'getBigDecimal(v, scale)', the current JDBC specification should be deprecated, and the method 'getBigDecimal(v)' is normally used. I think it would be better to use 'BigDecimal.valueOf(v)' to maintain the correct precision.
![image](https://user-images.githubusercontent.com/32257480/166088074-3b84ae44-18b7-4f69-b255-9e97ac905057.png)

**Comment by zhicwu** [comment]
Thanks @SurelySomeday, I'll fix this in patch9.
