### ISSUE TITLE
NPE when select a nullable field

### ISSUE THREAD

**Issue by liaoyt** [ClickHouse/clickhouse-jdbc#915]
version: 3.2.0
class: com.clickhouse.jdbc.ClickHouseResultSet
method: getDate getTimestamp

how to reproduce it:

```sql
# 1. create a table with nullable field
CREATE TABLE nullable_table
(
    `id` Int8,
    `field1` Nullable(Date),
    `field2` Nullable(DateTime)
)
ENGINE = MergeTree
PRIMARY KEY id
ORDER BY id

# 2. insert null values
insert into nullable_table(id) values (1);

```

and then select with jdbc interface 

![image](https://user-images.githubusercontent.com/12195059/166861602-2e78051a-6002-40c0-9a97-6216a8e89d1d.png)

![image](https://user-images.githubusercontent.com/12195059/166861559-f84f2b83-9d7f-4902-a2db-54ff3f284c45.png)

**Comment by zhicwu** [comment]
Thanks for reporting the issue. I believe it's been fixed in patch release. Could you upgrade driver to latest and try again?

**Comment by liaoyt** [comment]
@zhicwu Thanks you and I tried version 3.2.0-patch8 which works fine.

**Comment by mmkrish** [comment]
Hi Team, 

I am also facing the same issue and i have jdbc0.3.2 driver updated.  Could you pl help me to fix this issue .
