### ISSUE TITLE
column type is Array(Nullable(Int64))  But Null becomes 0 in the result returned

### ISSUE THREAD

**Issue by liumaojing** [ClickHouse/clickhouse-jdbc#924]
resultSet:
[3553669559,3571293165,3851086538,3090702645,3407263362]
[3874870412,3451171182,3922428704,3228944982,3590715072]
[NULL,3989698365,3521029982,NULL,NULL]
[NULL]
[3411652369,3144762202,3230150923,3581921969,3306736155]

getArray:
{0,3989698365,3521029982,0,0}

my code:
while (resultSet.next()) {
            Array array = resultSet.getArray(1);
            Object array1 = array.getArray();
}

version 0.2.3

**Comment by liumaojing** [comment]
> Thanks for reporting the issue. Primitive type should not be used for nullable types.
How do I get Array(Nullable(Int64)) results  ?Can you give me an example  ?

**Comment by zhicwu** [comment]
> How do I get Array(Nullable(Int64)) results ?Can you give me an example ?

Not your fault. It's a bug in the driver, not only the version you're using but also the latest. As I recalled, in 0.2.3, there's a connection property called `use_object_wrapper`, changing it to true will stop using primitive type, which might fix the issue at your end. However, I think the better way is to fix the issue and upgrade driver to latest.

**Comment by liumaojing** [comment]
> Starting from 0.3.2-patch9, `Array(Nullable(UInt64))` is mapped to `Long[]` instead of `long[]`.

import com.clickhouse.client.grpc.impl  
 why doesn't  this jar  import ?

**Comment by liumaojing** [comment]
> Starting from 0.3.2-patch9, `Array(Nullable(UInt64))` is mapped to `Long[]` instead of `long[]`.

I use getArray() function and it's still long[] ,I use   0.3.2-patch9 version

**Comment by liumaojing** [comment]
How Can I get Array(Nullable(Int64)) results ?Can you give me an example ?

**Comment by zhicwu** [comment]
> How Can I get Array(Nullable(Int64)) results ?Can you give me an example ?

Below case works for me:
```java
try (ClickHouseConnection conn = newConnection(new Properties());
        Statement stmt = conn.createStatement()) {
    ResultSet rs = stmt
            .executeQuery(
                    "select [null, 2, null]::Array(Nullable(UInt64))");
    Assert.assertTrue(rs.next());
    Assert.assertEquals(rs.getObject(1), new Long[] {null, 2L, null});
    Assert.assertEquals(rs.getArray(1).getArray(), new Long[] {null, 2L, null});
    Assert.assertFalse(rs.next());
}
```

**Comment by liumaojing** [comment]
Follow your example above，the following is the error log:

OpenJDK 64-Bit Server VM warning: Sharing is only supported for boot loader classes because bootstrap classpath has been appended
2022-05-18 10:17:36:215 +0800 [main] WARN ClickHouseDriver - ******************************************************************************************
2022-05-18 10:17:36:220 +0800 [main] WARN ClickHouseDriver - * This driver is DEPRECATED. Please use [com.clickhouse.jdbc.ClickHouseDriver] instead.  *
2022-05-18 10:17:36:220 +0800 [main] WARN ClickHouseDriver - * Also everything in package [ru.yandex.clickhouse] will be removed starting from 0.4.0. *
2022-05-18 10:17:36:220 +0800 [main] WARN ClickHouseDriver - ******************************************************************************************
Exception in thread "main" java.lang.AssertionError: expected:<ru.yandex.clickhouse.ClickHouseArray@d41f816> but was:<[Ljava.lang.Long;@5c2375a9>
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.failNotEquals(Assert.java:835)
	at org.junit.Assert.assertEquals(Assert.java:120)
	at org.junit.Assert.assertEquals(Assert.java:146)

**Comment by liumaojing** [comment]
> > How Can I get Array(Nullable(Int64)) results ?Can you give me an example ?
> 
> Below case works for me:
> 
> ```java
> try (ClickHouseConnection conn = newConnection(new Properties());
>         Statement stmt = conn.createStatement()) {
>     ResultSet rs = stmt
>             .executeQuery(
>                     "select [null, 2, null]::Array(Nullable(UInt64))");
>     Assert.assertTrue(rs.next());
>     Assert.assertEquals(rs.getObject(1), new Long[] {null, 2L, null});
>     Assert.assertEquals(rs.getArray(1).getArray(), new Long[] {null, 2L, null});
>     Assert.assertFalse(rs.next());
> }
> ```

Follow your example above,the error log is as follows:
OpenJDK 64-Bit Server VM warning: Sharing is only supported for boot loader classes because bootstrap classpath has been appended
2022-05-18 10:17:36:215 +0800 [main] WARN ClickHouseDriver - ******************************************************************************************
2022-05-18 10:17:36:220 +0800 [main] WARN ClickHouseDriver - * This driver is DEPRECATED. Please use [com.clickhouse.jdbc.ClickHouseDriver] instead.  *
2022-05-18 10:17:36:220 +0800 [main] WARN ClickHouseDriver - * Also everything in package [ru.yandex.clickhouse] will be removed starting from 0.4.0. *
2022-05-18 10:17:36:220 +0800 [main] WARN ClickHouseDriver - ******************************************************************************************
Exception in thread "main" java.lang.AssertionError: expected:<ru.yandex.clickhouse.ClickHouseArray@d41f816> but was:<[Ljava.lang.Long;@5c2375a9>
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.failNotEquals(Assert.java:835)
	at org.junit.Assert.assertEquals(Assert.java:120)
	at org.junit.Assert.assertEquals(Assert.java:146)
	at ru.yandex.clickhouse.testconn.main(testconn.java:38)

**Comment by zhicwu** [comment]
> 2022-05-18 10:17:36:220 +0800 [main] WARN ClickHouseDriver - * This driver is DEPRECATED. Please use [com.clickhouse.jdbc.ClickHouseDriver] instead. *

Can you switch to the exact driver shown above? If you need to stay with the legacy driver(ru.yandex.*), you may try `use_objects_in_arrays` property to see if it will work or not.

**Comment by liumaojing** [comment]
> > 2022-05-18 10:17:36:220 +0800 [main] WARN ClickHouseDriver - * 此驱动程序已弃用。请改用 [com.clickhouse.jdbc.ClickHouseDriver]。*
> 
> 您可以切换到上面显示的确切驱动程序吗？如果您需要继续使用旧版驱动程序（ru.yandex.*），您可以尝试`use_objects_in_arrays`使用属性，看看它是否可以工作。

use_objects_in_arrays ==true doesn't take effect, change the driver was successful,but the null values are gone.The length of the array([null, 2L, null]) is 3, but the return value is 2,I don't think it makes sense,Will it improve in future releases?

**Comment by liumaojing** [comment]
package com.clickhouse;


import com.clickhouse.jdbc.ClickHouseDataSource;
import java.sql.*;
import java.util.Properties;
class testconn {
    public static void main(String[] args) throws SQLException {
        ClickHouseDataSource cds;
        String url = "jdbc:clickhouse://hostname:8123";
        Properties cp = new Properties();
        cp.setProperty("user", "admin");
        cp.setProperty("password", "Dly9DvXcAT");
        cds = new ClickHouseDataSource(url, cp);
        Connection conn = cds.getConnection();
        Statement stmt = conn.createStatement();
        ResultSet resultSet = stmt
                .executeQuery("select [null, 2, null]");
        while (resultSet.next()) {
            Array array = resultSet.getArray(1);
            Object array1 = array.getArray();
            System.out.println(array1);
        }
    }
}

**Comment by liumaojing** [comment]
> > The length of the array([null, 2L, null]) is 3, but the return value is 2
> 
> I cannot reproduce this issue. Are you saying above test case not working for you? Could you post a complete program for reproducing?

package com.clickhouse;

import com.clickhouse.jdbc.ClickHouseDataSource;
import java.sql.*;
import java.util.Properties;
class testconn {
public static void main(String[] args) throws SQLException {
ClickHouseDataSource cds;
String url = "jdbc:clickhouse://hostname:8123";
Properties cp = new Properties();
cp.setProperty("user", "admin");
cp.setProperty("password", "Dly9DvXcAT");
cds = new ClickHouseDataSource(url, cp);
Connection conn = cds.getConnection();
Statement stmt = conn.createStatement();
ResultSet resultSet = stmt
.executeQuery("select [null, 2, null]");
while (resultSet.next()) {
Array array = resultSet.getArray(1);
Object array1 = array.getArray();
System.out.println(array1);
}
}
}


The length of the array([null, 2L, null]) is 3, but the return value is 2

**Comment by zhicwu** [comment]
Just tried the program and it works for me. I changed the last two lines to below:

```java
Short[] array1 = (Short[])array.getArray();
System.out.println(array1.length); // 3
System.out.println(Arrays.toString(array1));
```

**Comment by liumaojing** [comment]
Sorry, I was checking array in DEBUG mode for non-null values，The actual output is normal，Thank you very much for your help.

**Comment by liumaojing** [comment]
> Just tried the program and it works for me. I changed the last two lines to below:
> 
> ```java
> Short[] array1 = (Short[])array.getArray();
> System.out.println(array1.length); // 3
> System.out.println(Arrays.toString(array1));
> ```

After changing the driver,  ClickhouseDatasource is not  compatible  with Balanceddatasource,For Example ,actualize() function,Any suggestions so far?

**Comment by zhicwu** [comment]
There's no balanced datasource in the new driver as of now but it should not be very hard to add one. Will try to squeeze this feature into patch10.

**Comment by clliangchen** [comment]
> There's no balanced datasource in the new driver as of now but it should not be very hard to add one. Will try to squeeze this feature into patch10.

Has this been finally resolved?
