### ISSUE TITLE
Test fail with clickhouse 22.3.3.44

### ISSUE THREAD

**Issue by antip00** [ClickHouse/clickhouse-jdbc#934]
I tried to run mvn tests with clickhouse version 22.3.3.44 but it fails

I install jdk 11, mvn, clickhouse 22.3.3.44,
configurating JAVA_HOME,
add port.xml, users.xml into etc/clickhouse,
restart server and do mvn test

v0.3.2-patch8:
[INFO] clickhouse-java .................................... SUCCESS [ 11.844 s]
[INFO] clickhouse-client .................................. SUCCESS [ 43.277 s]
[INFO] clickhouse-grpc-client ............................. FAILURE [  8.567 s]
[INFO] clickhouse-http-client ............................. SKIPPED
[INFO] clickhouse-tcp-client .............................. SKIPPED
[INFO] clickhouse-jdbc .................................... SKIPPED
[INFO] clickhouse-benchmark ............................... SKIPPED

v0.3.1-patch:
[INFO] clickhouse-java .................................... SUCCESS [ 10.042 s]
[INFO] clickhouse-client .................................. SUCCESS [ 25.708 s]
[INFO] clickhouse-grpc-client ............................. SUCCESS [  0.016 s]
[INFO] clickhouse-http-client ............................. SUCCESS [  0.394 s]
[INFO] clickhouse-native-client ........................... SUCCESS [  0.017 s]
[INFO] clickhouse-jdbc .................................... FAILURE [  8.082 s]
[INFO] clickhouse-benchmark ............................... SKIPPED

**Comment by zhicwu** [comment]
Hi @antip00, could you post the errors as well? You may open surefire or failsafe test report to check details.
