### ISSUE TITLE
 Cannot parse object when I use fastjson to write a table 

### ISSUE THREAD

**Issue by jetliu1711** [ClickHouse/clickhouse-jdbc#946]
Hello,I have question with use fastjson to write a table ,table data type is Object('json'),but it make error like this:
ru.yandex.clickhouse.except.ClickHouseException: ClickHouse exception, code: 117, host: 127.0.0.1, port: 8123; Code: 117. DB::Exception: Cannot parse object: (at row 1)
: 
Row 1:
Column 0,   name: groupID,    type: String,         parsed text: "00001"
Column 1,   name: shopID,     type: String,         parsed text: "1010"
Column 2,   name: reportDate, type: Date,           parsed text: "1970-01-01"
Column 3,   name: orderKey,   type: String,         parsed text: "1"
Column 4,   name: shopName,   type: String,         parsed text: ""
Column 5,   name: json_data,  type: Object('json'), parsed text: "{ QUOTE>makeFinishStatus<SINGLE QUOTE>:0,<SINGLE QUOTE>cancelFoodAmount<SINGLE QUOTE>:0,<SINGLE QUOTE>foodVipPrice<SINGLE QUOTE>:0,<SINGLE QUOTE>foodCode<SINGLE QUOTE>:<SINGLE QUOTE>550A0002<SINGLE QUOTE>,<SINGLE QUOTE>sendBy<SINGLE QUOTE>:<SINGLE QUOTE><SINGLE QUOTE>},{<SINGLE QUOTE>foodPayPriceReal<SINGLE QUOTE>:0,<SINGLE QUOTE>isSFDetail<SINGLE QUOTE>:1,<SINGLE QUOTE>isBatching<SINGLE QUOTE>:0,<SINGLE QUOTE>foodSendAuthorizer<SINGLE QUOTE>:<SINGLE QUOTE><SINGLE QUOTE>,<SINGLE QUOTE>finalSugarContent<SINGLE QUOTE>:0,<SINGLE QUOTE>clientType<SINGLE QUOTE>:0,<SINGLE QUOTE>reportDate<SINGLE QUOTE>:20220405,<SINGLE QUOTE>areaName<SINGLE QUOTE>:<SINGLE QUOTE>快餐区<SINGLE QUOTE>,<SINGLE QUOTE>setFoodRemark<SINGLE QUOTE>:<SINGLE QUOTE><SINGLE QUOTE>,<SINGLE QUOTE>action<SINGLE QUOTE>:1,<SINGLE QUOTE>foodDiscountRate<SINGLE QUOTE>:10,<SINGLE QUOTE>tableID<SINGLE QUOTE>:0,<SINGLE QUOTE>makeEndfoodNumber<SINGLE QUOTE>:0,<SINGLE QUOTE>takeMoney<SINGLE QUOTE>:<SINGLE QUOTE><SINGLE QUOTE>,<SINGLE QUOTE>foodPractice<SINGLE QUOTE>:<SINGLE QUOTE><SINGLE QUOTE>,<SINGLE QUOTE>salesCommission<SINGLE QUOTE>:0,<SINGLE QUOTE>saasOrderKey<SINGLE QUOTE>:<SINGLE QUOTE><SINGLE QUOTE>,<SINGLE QUOTE>foodSendNumber<SINGLE QUOTE>:0,<SINGLE QUOTE>transferOperator<SINGLE QUOTE>:<SINGLE QUOTE><SINGLE QUOTE>,<SINGLE QUOTE>addFoodFlag<SINGLE QUOTE>:0,<SINGLE QUOTE>foodSubType<SINGLE QUOTE>:<SINGLE QUOTE>堂食<SINGLE QUOTE>,<SINGLE QUOTE>sendTime<SINGLE QUOTE>:0,<SINGLE QUOTE>makeStartTime<SINGLE QUOTE>:0,<SINGLE QUOTE>foodRealAmount<SINGLE QUOTE>:0,<SINGLE QUOTE>makeCallCount<SINGLE QUOTE>:0,<SINGLE QUOTE>setFoodCategoryName<SINGLE QUOTE>:<SINGLE QUOTE>饮品<SINGLE QUOTE>,<SINGLE QUOTE>unitAdjuvantNumber<SINGLE QUOTE>:0,<SINGLE QUOTE>basketName<SINGLE QUOTE>:<SINGLE QUOTE><SINGLE QUOTE>,<SINGLE QUOTE>makeEndNumber<SINGLE QUOTE>:0,<SINGLE QUOTE>unitAdjuvant<SINGLE QUOTE>:<SINGLE QUOTE><SINGLE QUOTE>,<SINGLE QUOTE>actionTime<SINGLE QUOTE>:20220405083631,<SINGLE QUOTE>promotionIDLst<SINGLE QUOTE>:<SINGLE QUOTE><SINGLE QUOTE>,<SINGLE QUOTE>orderBy<SINGLE QUOTE>:<SINGLE QUOTE>123|余婷<SINGLE QUOTE>,<SINGLE QUOTE>setFoodPriceAmount<SINGLE QUOTE>:0,<SINGLE QUOTE>foodCategoryCode<SINGLE QUOTE>:<SINGLE QUOTE>SAP3<SINGLE QUOTE>,<SINGLE QUOTE>isSameOrderActionBathcNo<SINGLE QUOTE>:<SINGLE QUOTE><SINGLE QUOTE>,<SINGLE QUOTE>foodRemark<SINGLE QUOTE>:<SINGLE QUOTE><SINGLE QUOTE>,<SINGLE QUOTE>kdsSplitProductCode<SINGLE QUOTE>:<SINGLE QUOTE>0<SINGLE QUOTE>,<SINGLE QUOTE>lastMakeTime<SINGLE QUOTE>:0,<SINGLE QUOTE>foodKey<SINGLE QUOTE>:<SINGLE QUOTE>5f74a1ce-6655-4166-a647-dedf6e497390<SINGLE QUOTE>,<SINGLE QUOTE>serveConfirmTime<SINGLE QUOTE>:0,<SINGLE QUOTE>cancelReason<SINGLE QUOTE>:<SINGLE QUOTE><SINGLE QUOTE>,<SINGLE QUOTE>seatNo<SINGLE QUOTE>:0,<SINGLE QUOTE>modifyReason<SINGLE QUOTE>:<SINGLE QUOTE><SINGLE QUOTE>,<SINGLE QUOTE>isSplit<SINGLE QUOTE>:<SINGLE QUOTE>false<SINGLE QUOTE>,<SINGLE QUOTE>propertyList<SINGLE QUOTE>:<SINGLE QUOTE><SINGLE QUOTE>,<SINGLE QUOTE>makeEndTime<SINGLE QUOTE>:0,<SINGLE QUOTE>makeBy<SINGLE QUOTE>:<SINGLE QUOTE><SINGLE QUOTE>,<SINGLE QUOTE>targetWcDevice<SINGLE QUOTE>:-1,<SINGLE QUOTE>itemKey<SINGLE QUOTE>:<SINGLE QUOTE>23b91ff0-8aad-435a-9b88-800230ea1347<SINGLE QUOTE>,<SINGLE QUOTE>makingMethod<SINGLE QUOTE>:0,<SINGLE QUOTE>foodCancelAuthorizer<SINGLE QUOTE>:<SINGLE QUOTE><SINGLE QUOTE>,<SINGLE QUOTE>createTime<SINGLE QUOTE>:20220405083549,<SINGLE QUOTE>foodProPrice<SINGLE QUOTE>:0,<SINGLE QUOTE>foodCategoryGroupName<SINGLE QUOTE>:<SINGLE QUOTE><SINGLE QUOTE>,<SINGLE QUOTE>foodRealPrice<SINGLE QUOTE>:0,<SINGLE QUOTE>foodNumber<SINGLE QUOTE>:1,<SINGLE QUOTE>parentItemKey<SINGLE QUOTE>:<SINGLE QUOTE>19fadc67-398c-45f8-93a2-9a238cb5efa6<SINGLE QUOTE>,<SINGLE QUOTE>actionBatchNo<SINGLE QUOTE>:<SINGLE QUOTE>d40afb6a1ac74d469a659a828fb1b304<SINGLE QUOTE>,<SINGLE QUOTE>isTempFood<SINGLE QUOTE>:0,<SINGLE QUOTE>lastRemindTime<SINGLE QUOTE>:0,<SINGLE QUOTE>thirdDeviceNo<SINGLE QUOTE>:<SINGLE QUOTE><SINGLE QUOTE>,<SINGLE QUOTE>foodBarCode<SINGLE QUOTE>:<SINGLE QUOTE><SINGLE QUOTE>,<SINGLE QUOTE>readyNumber<SINGLE QUOTE>:0,<SINGLE QUOTE>itemDetail<SINGLE }}"ERROR
Code: 117. DB::Exception: Cannot parse object. (INCORRECT_DATA) (version 22.5.1.2079 (official build))

: While executing ParallelParsingBlockInputFormat. (INCORRECT_DATA) (version 22.5.1.2079 (official build))

	at ru.yandex.clickhouse.except.ClickHouseExceptionSpecifier.specify(ClickHouseExceptionSpecifier.java:60)
	at ru.yandex.clickhouse.except.ClickHouseExceptionSpecifier.specify(ClickHouseExceptionSpecifier.java:30)
	at ru.yandex.clickhouse.ClickHouseStatementImpl.checkForErrorAndThrow(ClickHouseStatementImpl.java:1094)
	at ru.yandex.clickhouse.ClickHouseStatementImpl.sendStream(ClickHouseStatementImpl.java:1056)
	at ru.yandex.clickhouse.ClickHouseStatementImpl.sendStream(ClickHouseStatementImpl.java:1022)
	at ru.yandex.clickhouse.ClickHouseStatementImpl.sendStream(ClickHouseStatementImpl.java:1015)
	at ru.yandex.clickhouse.ClickHousePreparedStatementImpl.executeBatch(ClickHousePreparedStatementImpl.java:382)
	at ru.yandex.clickhouse.ClickHousePreparedStatementImpl.executeBatch(ClickHousePreparedStatementImpl.java:365)
	at com.hualala.com.Demo_json.main(Demo_json.java:1048)
Caused by: java.lang.Throwable: Code: 117. DB::Exception: Cannot parse object: (at row 1)

**Comment by zhicwu** [comment]
Hi @jetliu1711, thanks for reporting the issue. Legacy driver(ru.yandex.clickhouse.ClickHouseDriver) does not support `Object('JSON')`, so I'd suggest you to switch to new driver(com.clickhouse.jdbc.ClickHouseDriver).

If you prefer to stay on JDBC driver instead of Java client, you probably should use structured data instead of JSON string for better performance - try issue a query like `select (1,'a', ('b', 'c'), [1,2,3])::Tuple(id UInt32, a String, t Tuple(b LowCardinality(String), c Nullable(String)), d Array(Int8))` to understand how to structure the data. If you insist to use JSON, you may unwrap `Statement` and use Java client API instead, for example:
```java
Statement stmt = conn.createStatement();
ClickHouseRequest<?> req = stmt.unwrap(ClickHouseRequest.class);
req.write().format(ClickHouseFormat.JSONEachRow).table('mytable').data(myJsonInputStream).sendAndWait();
```

Lastly, I hope you understand JSON/Object('JSON') is an experimental feature, which is not production ready. I didn't try 22.5 but on 22.3 it sometimes leads to server stopped responding.
