### ISSUE TITLE
Incorrect update count (0.3.2-patch9)

### ISSUE THREAD

**Issue by Veirisa** [ClickHouse/clickhouse-jdbc#947]
Hi! 

In `com.clickhouse.jdbc.internal.ClickHouseStatementImpl#updateResult`:

```
...
// FIXME apparently this is not always true
if (currentUpdateCount <= 0L) {
    currentUpdateCount = 1L;
}
...
```

Yes, this isn’t always true :)

**Examples:**

```
Statement statement = connection.createStatement();
statement.execute(sql);
int updateCount = statement.getUpdateCount();
```

1. `String sql = “CREATE TABLE new_table(x INT) engine = Memory;”`
Expected `updateCount`: 0
Actual `updateCount`: 1

2. `String sql = "INSERT INTO new_table VALUES (1), (2), (3);"`
Expected `updateCount`: 3
Actual `updateCount`: 1

**Comment by zhicwu** [comment]
You got me :p

Have you tried `send_progress_in_http_headers` option like used [here](https://github.com/ClickHouse/clickhouse-jdbc/blob/c98c084e35ee68249274fcd273644545d90e82a3/clickhouse-client/src/test/java/com/clickhouse/client/ClientIntegrationTest.java#L1022)? With that, I think case 2 will be fixed but case 1 stays the same. Let me think how to tackle this without much parsing efforts.

**Comment by zhicwu** [comment]
Now the update count depends on two things: 1) SQL parser(a bit outdated); and 2) summary returned from server. Above two cases work as expected on 22.6+.
