### ISSUE TITLE
Question about BalancedClickhouseDataSource 

### ISSUE THREAD

**Issue by zcw5116** [ClickHouse/clickhouse-jdbc#949]
Old Driver [ru.yandex.clickhouse] has class BalancedClickhouseDataSource， which can be used for assigning multiple hosts，
New Driver [com.clickhouse.jdbc.ClickHouseDriver]， if plan to support BalancedClickhouseDataSource?

**Comment by zhicwu** [comment]
Hi @zcw5116, sorry the feature is still under testing. It will be part of 0.3.2-patch10 which hopefully can be released by this weekend.

Basically, there's no `BalancedClickhouseDataSource`. You just need to specify multiple endpoints in connection string. For examples:
1. load balancing among 3 endpoints
  `jdbc:ch://(http://localhost),(grpc://localhost),(tcp://localhost)/mydb?load_balancing_policy=random&health_check_interval=10000`
2. load balancing for specific cluster with node discovery
  `jdbc:ch:http://node1,(grpc://node2?auto_discovery),{node3?!auto_discovery}/mydb?cluster=cluster1&load_balancing_policy=roundRobin&health_check_interval=5000&discovery_interval=30000`
3. custom load balancing policy
  `jdbc:ch:http://node1,node2,node3/test?load_balancing_policy=com.my company.integration.clickhouse.DcAwarePolicy&health_check_interval=5000`

I noticed quite some connection refused errors during stress testing against master nodes(the ones running clickhouse-keeper), so I'm going to add naive failover tonight to address that.
