### ISSUE TITLE
Apostrophe in bind variables generate errors when driver is used with chproxy

### ISSUE THREAD

**Issue by ghaase67** [ClickHouse/clickhouse-jdbc#958]
The JDBC driver seems to replace ' by \' in the PreparedStatement binding (ClickHousePreparedStatementImpl).
This leads to ClickHouse exception code: 1002 when chproxy is used.
Any suggestion for a workaround for this?
One solution would likely be that the driver replaces ' by '' instead of \'

**Comment by ghaase67** [comment]
Yes the driver is old but the clickhouse db is too old for the 0.3.2  driver (Server < 20.7) and the problem occurs with 0.3.1-patch.
The problem also happens when using Dbeaver with the clickhoudse JDBC driver and executing the following SQL:
select '\''
According to the documentation this should work but it doesn't and it "simulates" what the driver is doing internally.
https://clickhouse.com/docs/en/sql-reference/syntax/ (String)

**Comment by zhicwu** [comment]
The query you provided has syntax issue. Did you mean `select ''''`? I tried both legacy and new drivers against ClickHouse 22.3, both of them work well.

**Comment by ghaase67** [comment]
Sorry my mistake. 
The test case is "select '\''" where ' is escaped by \'. "select ''''" with double quotes also works in our environment.
If you can't reproduce the problem you could close the issue as we are going to rewrite the code to dynamic SQL instead of using Prepared Statements and replace ' by '' in SQL.
Thanks for your help so far.

**Comment by ghaase67** [comment]
ah the editor is removing the backslah.
The test case is "select ''\\'" where ' is escaped by \\'.

**Comment by zhicwu** [comment]
Thanks @ghaase67. I tried `select '\''` using both drivers and they work just fine. What's the exact error you got from DBeaver? And version of ClickHouse server?
