### ISSUE TITLE
PreparedStatement insert batch sql  NullPointerException

### ISSUE THREAD

**Issue by airlenet** [ClickHouse/clickhouse-jdbc#964]
example code 

```       
<dependency>
            <groupId>com.clickhouse</groupId>
            <artifactId>clickhouse-jdbc</artifactId>
            <version>0.3.2-patch9</version>
 </dependency> `

```
    public static void main(String[] args) throws SQLException {
        String url = "jdbc:clickhouse://172.19.129.202:8123";
        String username = "default";
        String password = "123456";
        Properties properties = new Properties();
        properties.setProperty(ClickHouseDefaults.USER.getKey(), username);
        properties.setProperty(ClickHouseDefaults.PASSWORD.getKey(), password);
        List<Integer> partition = Arrays.asList(1, 2, 3);
        try (
                Connection connection = new com.clickhouse.jdbc.ClickHouseDriver().connect(url, properties);
               /*Connection connection = new ru.yandex.clickhouse.ClickHouseDriver().connect(url, properties);*/
                PreparedStatement statement = connection.prepareStatement("INSERT INTO device_user (device_type,device_sn,  timestamp, user_count)" +
                        " VALUES( ?,?,?,?),( ?,?,?,?)");
        ) {
            for (Integer i : partition) {
                statement.setString(1, "1");
                statement.setString(2, "1");
                statement.setTimestamp(3, new java.sql.Timestamp(System.currentTimeMillis()));
                statement.setLong(4, 1);

                statement.setString(5, "1");
                statement.setString(6, "1");
                statement.setTimestamp(7, new java.sql.Timestamp(System.currentTimeMillis()));
                statement.setLong(8, 1);
            }
            statement.execute();
        } catch (SQLException throwables) {
            throwables.printStackTrace();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
```

ru.yandex.clickhouse.ClickHouseDriver  can be used normally

 com.clickhouse.jdbc.ClickHouseDriver Error


```
java.lang.NullPointerException
	at com.clickhouse.jdbc.internal.ClickHouseConnectionImpl.prepareStatement(ClickHouseConnectionImpl.java:618)
	at com.clickhouse.jdbc.ClickHouseConnection.prepareStatement(ClickHouseConnection.java:104)
```

The details are as follows
```
                int startIndex = parsedStmt.getPositions().get(ClickHouseSqlStatement.KEYWORD_VALUES_START);
                int endIndex = parsedStmt.getPositions().get(ClickHouseSqlStatement.KEYWORD_VALUES_END);
```

**Comment by zhicwu** [comment]
Hi @airlenet, sorry for the inconvenience. It looks like the same issue as reported in #920. I need to merge one or two PRs before releasing patch10 to maven central, but can you try again using https://github.com/ClickHouse/clickhouse-jdbc/releases/tag/v0.3.2-patch10?

The way you use prepared statement is actually creating a insert query without telling the driver column types. It can be optimized by changing the query to `INSERT INTO device_user (device_type,device_sn,  timestamp, user_count)` (without the value expression) and use batch insert instead. That way, parameters will be streamed to server in binary format(not as part of the query), which should be faster(especially when you have more data to insert).

**Comment by airlenet** [comment]
I use springboot+mybatis+clickhouse to insert in batches and cannot use it（ `INSERT INTO device_user (device_type,device_sn, timestamp, user_count) `(without the value expression) and use batch insert instead ）

**Comment by zhicwu** [comment]
I see. You can use `INSERT INTO device_user (device_type,device_sn, timestamp, user_count) values(?,?,?,?)` instead.
