### ISSUE TITLE
Clickhouse subquery not allowed with CASE/IF statement

### ISSUE THREAD

**Issue by NileshSuthar** [ClickHouse/clickhouse-jdbc#965]
I am trying to filter data with the help of a condition in click house. This is the query:

    SELECT CASE
    
    WHEN EXISTS (
    
    SELECT * FROM (SELECT Time, Lon, Users FROM table1 ORDER BY Time DESC LIMIT 5) WHERE Users>=75
    
    )
    
    THEN ( * FROM (SELECT Time, Lon, Users FROM table1 ORDER BY Time DESC LIMIT 5) WHERE Users<75)
    
    ELSE ( * WHERE 0=1)
    
    END;

I had also tried simple IF condition in clickhouse but eve in that subquery didn't work. The query:

    SELECT if((SELECT count() FROM table1 WHERE Users>=75)>0, SELECT * FROM table1 WHERE Users<75, plus(2, 6));

Both time the basic error remains same:

    Code: 62, e.displayText() = DB::Exception: Syntax error: failed at position 77 ('default'): default.4g WHERE Users<75, plus(2, 6));
    . Expected one of: LIKE, GLOBAL NOT IN, end of query, AS, DIV, IS, OR, QuestionMark, BETWEEN, NOT LIKE, MOD, AND, Comma, alias, IN, ILIKE, Dot, NOT ILIKE, NOT, token, NOT IN, GLOBAL IN (version 21.3.20.1 (official build))

Is there any way to run subqueries within CASE/IF in click house ?

**Comment by zhicwu** [comment]
Hi @NileshSuthar, will CTE work for you? For example:

```sql
with a as (select count(1) c from system.query_log)
select if (a.c %2 = 0, 'a', 'b')
from a
```

**Comment by NileshSuthar** [comment]
Hi @zhicwu 
I tried this query but it also didn't work

with (select count() from table1 where Users>=75 ) as a
select if (a> 0, select count() from table1 where Users<75, 'b')

**Comment by zhicwu** [comment]
You may try below:

```sql
with a as (select count() t, countIf(event_time > now() - interval 1 hour) m from system.query_log)
select if (m > 0, t - m, 2+6)
from a
```

This has nothing to do with Java client or JDBC driver, so I'd suggest you asking the question in Slack/Telegram/ClickHouse repo to get better idea.
