### ISSUE TITLE
JAVA documentation for Clichouse-http-client

### ISSUE THREAD

**Issue by usmanq8** [ClickHouse/clickhouse-jdbc#966]
I wonder if you have complete documentation over clickhouse-http-client (Java) ?
As current doc are only over clickhouse DB and we need to go thru code on GIT.

**Comment by zhicwu** [comment]
Hi @usmanq8, `clickhouse-http-client` is an implementation of `clickhouse-client`, so you probably just need to check javadoc of the latter and [ClientIntegartionTest](https://github.com/ClickHouse/clickhouse-jdbc/blob/develop/clickhouse-client/src/test/java/com/clickhouse/client/ClientIntegrationTest.java) for usage.

If you're unclear about relationship among those modules, you may refer to below diagram. In general, unless you have very special reason, you just need to use generic interfaces/classes in clickhouse-client module, for instances: `ClickHouseNode(s)`, `ClickHouseClient`, `ClickHouseRequest` and `ClickHouseResponse`.

![image](https://user-images.githubusercontent.com/4270380/108149989-d4498180-710e-11eb-878a-d9c8d24ca268.png)
