### ISSUE TITLE
How Async_inserts option works using clickhouse-http-client (JAVA)

### ISSUE THREAD

**Issue by usmanq8** [ClickHouse/clickhouse-jdbc#967]
I was going thru following link and came across `ASYNC_INSERTS `for http client.
Is this also true while using clickhouse-http-client. if yes, how we can enable it. Also i tried using server property to be enabled in DB's config file but it does not seems to work as intended. Am i missing some thing

[https://clickhouse.com/blog/click-house-v2111-released](https://clickhouse.com/blog/click-house-v2111-released)

How can i monitor if async inserts are buffered and batched up using above property in INSERT cases.

**Comment by zhicwu** [comment]
Please refer to integration test at [here](https://github.com/ClickHouse/clickhouse-jdbc/blob/c98c084e35ee68249274fcd273644545d90e82a3/clickhouse-jdbc/src/test/java/com/clickhouse/jdbc/ClickHouseStatementTest.java#L173). If you use v0.3.2-patch10, you may also want to enable load balancing - see details at [here](https://github.com/ClickHouse/clickhouse-jdbc/pull/956#issue-1275801624).

**Comment by ermadan** [comment]
@zhicwu Looks like the test code enables async in Jdbc API wich is not ideal for heavy inserts. Can you explain how to enable it for a pure http client with ClickHouseNode/ClickHouseClient.send?

**Comment by zhicwu** [comment]
Hi @ermadan, you can use `ClickHouseRequest.option(ClickHouseHttpOption.CUSTOM_PARAMS, "async_insert=1,wait_for_async_insert=0")` to enable async insert, and then use `ClickHouseClient.send` to execute the query. Alternatively, you can specify the settings in connection string like `ClickHouseNode.of("http://HOST.clickhouse.cloud:8443/?user=default&password=PASSWORD&ssl=true&custom_http_params=async_insert=1,wait_for_async_insert=0")`.

If you don't want to be limited to http protocol or any client-side change, you may check [here](https://clickhouse.com/docs/en/cloud/bestpractices/asynchronous-inserts/#enabling-asynchronous-inserts) and use INSERT statement with settings or profile instead.
