### ISSUE TITLE
ParameterMetaData  return NULL 

### ISSUE THREAD

**Issue by ArvinLovegood** [ClickHouse/clickhouse-jdbc#972]
// 0.3.2-patch10    
@Override
    public ParameterMetaData getParameterMetaData() throws SQLException {
        // TODO Auto-generated method stub
        return null;
    }

// old version  in package:   ru.yandex.clickhouse
    @Override
    public ParameterMetaData getParameterMetaData() throws SQLException {
        throw new SQLFeatureNotSupportedException();
    }

why not stay the same ?
It is easy to cause  a NullPointerException.

**Comment by zhicwu** [comment]
I should implement this method instead.
