### ISSUE TITLE
Maven dependencies a gone

### ISSUE THREAD

**Issue by kassak** [ClickHouse/clickhouse-jdbc#973]
After changing maven dependency from `0.3.2-patch9` to `0.3.2-patch10`, I've got `ClassNotFoundException` for `com.clickhouse.client.config.ClickHouseOption`

Looking into https://mvnrepository.com/artifact/com.clickhouse/clickhouse-jdbc/0.3.2-patch10 and https://mvnrepository.com/artifact/com.clickhouse/clickhouse-jdbc/0.3.2-patch9

I see that there are no more dependencies in corresponding section

**Comment by zhicwu** [comment]
Thanks for the report. Could you add `all` or `http` classifier in your pom file? For example:

```xml
<dependency>
    <groupId>com.clickhouse</groupId>
    <artifactId>clickhouse-jdbc</artifactId>
    <version>0.3.2-patch10</version>
    <classifier>http</classifier>
    <exclusions>
        <exclusion>
            <groupId>*</groupId>
            <artifactId>*</artifactId>
        </exclusion>
    </exclusions>
</dependency>
```

**Comment by kassak** [comment]
That helped, thanks

**Comment by zhicwu** [comment]
Thanks for confirming. It was a change by accident, but I'll take the chance to make `http` as the default jar in next release, so that you can later revert the workaround.

```xml
<!-- same as using http classifer with all dependencies excluded-->
<dependency>
    <groupId>com.clickhouse</groupId>
    <artifactId>clickhouse-jdbc</artifactId>
    <version>0.3.3</version>
</dependency>
```
