### ISSUE TITLE
why clear all compile dependencies in 0.3.2-patch10?

### ISSUE THREAD

**Issue by IcebergXTY** [ClickHouse/clickhouse-jdbc#986]
In 0.3.2-patch9 version, there are many dependencies like [this](https://mvnrepository.com/artifact/com.clickhouse/clickhouse-jdbc/0.3.2-patch9)

![image](https://user-images.githubusercontent.com/15325243/177681597-fc72ccc3-f30e-4fb9-9050-ad62c8e7b9f8.png)

but in 0.3.2-patch10 version, there are none dependencies, so it will lead to compile and running error.

![image](https://user-images.githubusercontent.com/15325243/177681704-74d3542f-4e14-4daa-92ef-697569ea943e.png)

So when I upgrade to 0.3.2-patch10, I should refer to 0.3.2-patch9's dependencies and add them by myself. What is the consideration for this behavior?

**Comment by ilittle-cnri** [comment]
Devs say issue will be fixed in next release. See https://github.com/ClickHouse/clickhouse-jdbc/issues/973 for a workaround.

**Comment by zhicwu** [comment]
Hi @IcebergXTY, please see my comments below:

> So when I upgrade to 0.3.2-patch10, I should refer to 0.3.2-patch9's dependencies and add them by myself.

You just need to add classifer `http` or `all` as mentioned in readme.

> What is the consideration for this behavior?

Sorry it was an unintentional change but it helps to enforce using shaded jar to avoid potential lib conflict.

**Comment by IcebergXTY** [comment]
> You just need to add classifer `http` or `all` as mentioned in readme.

Thank you for your reply, it works well now.

> Sorry it was an unintentional change but it helps to enforce using shaded jar to avoid potential lib conflict.

That's all right. It's a great idea to use shaded jar.😜
