### ISSUE TITLE
timezone set use_server_time_zone=UTC+8,select now();datetime 8 hours less than now

### ISSUE THREAD

**Issue by XiaoMingPass** [ClickHouse/clickhouse-jdbc#987]
clickhouse-jdbc：
```yml
clickhouse:
          url: jdbc:clickhouse://XXX.XXX.XXX.XXX:8123/data-base?use_time_zone=UTC+8&use_server_time_zone=UTC+8
```
pom：
``` xml
  <dependency>
            <groupId>com.clickhouse</groupId>
            <artifactId>clickhouse-jdbc</artifactId>
            <version>0.3.2-patch10</version>
        </dependency>
```

exec sql : select now();
result：2022-07-07T10:37:44.000+00:00(8 hours less than now)
reality：2022-07-07T18:37:44.000+00:00()

How to set JDBC parameters to execute normal results like MySQL?

**Comment by zhicwu** [comment]
Hi @XiaoMingPass, I'm not sure what you are trying to achieve. If it's just about getting timestamp with preferred timezone, you don't have to specific `use_time_zone` and `use_server_time_zone` parameters in connection string, instead you just use query below - the last column returns `OffsetDateTime` in Java.

```sql
select now() now, timezone() serverTz, now::DateTime('Asia/Shanghai') nowWithTz
```
