### ISSUE TITLE
Duplicated lz4 classes in 0.3.2-patch10

### ISSUE THREAD

**Issue by pan3793** [ClickHouse/clickhouse-jdbc#989]
<img width="486" alt="image" src="https://user-images.githubusercontent.com/26535726/178199912-b96e4fbd-d71c-4ab6-adfe-1dcf3b162c0d.png">

<img width="484" alt="image" src="https://user-images.githubusercontent.com/26535726/178199774-b3061f73-9307-42f8-a534-1062b61075aa.png">

**Comment by zhicwu** [comment]
Yes, I noticed that yesterday when cleaning up pom files 😭
